### ISSUE TITLE
SSAWM.Rdata

### ISSUE THREAD

**Issue by anniehang** [ben-domingue/irw#10]
[SSAWM.csv](https://github.com/ben-domingue/irw/files/14526452/SSAWM.csv)
in line69
This is the source of the data: https://osf.io/hp4gs/

**Comment by ben-domingue** [comment]
hi @anniehang ! 
first, thanks so much for help with this :)
i'm trying to decide if this is germane. it looks aggregated scores across tasks, yeah? if so it might be a little out-of-bounds of the irw. the last one was aggregates across raters which i could live with but i'm less inclined to take this one esp as only two items. are there no data on the individual responses?
