### ISSUE TITLE
Spelling-to-pronunciation transparency ratings for the 20,000 most frequently written English words

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#110]
paper. https://link.springer.com/article/10.3758/s13428-023-02205-2#data-availability
data. https://github.com/ashleyaedwards/SpellingToPronunciationTransparencyRatings

**Comment by KingArthur0205** [comment]
Working on this

**Comment by KingArthur0205** [comment]
@ben-domingue Just in case this gets overlooked. :)

**Comment by ben-domingue** [comment]
sorry, had missed this! 
this dataset is interesting and requires a decision. here, the object being rated is the *word* not the person. so i will change `item` to `id` but the question is then whether to: 
- make the person-level `id` the `item`
- make `item=1` for all of them and then make person-level `id` a `rater` column. 
i think i want to go with the first but want to think on this for a second.

**Comment by ben-domingue** [comment]
can also look at how we handled the gymnastic/figure-skating data. should make it consistent with those.

**Comment by ben-domingue** [comment]
OK let's do:
- an `item` column that is constant across all responses. 
- a `rater` column that is the person id. 

I modified above code to do this. See here: https://github.com/ben-domingue/irw/blob/main/data/spelling2pronounce_edwards2023.R

**Comment by KingArthur0205** [comment]
Oh, now I understand how we should handle the rating task. Thanks so much for your help! :))

**Comment by ben-domingue** [comment]
in this case, i didn't understand what i wanted! so you couldn't have possibly known! ;)
