### ISSUE TITLE
Measuring the variability of personality traits with interval responses: Psychometric properties of the dual-range slider response format

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#112]
https://link.springer.com/article/10.3758/s13428-024-02394-4

All data and analysis scripts for this article are available at the Open Science Framework (OSF): https://osf.io/gfzew/. The study was not preregistered.

**Comment by LynnYiningLu** [comment]
I am working on this.

**Comment by ben-domingue** [comment]
email sent re license on 12-16-2024
