### ISSUE TITLE
Probing apathy in children and adolescents with the Apathy Motivation Index–Child version

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#114]
https://link.springer.com/article/10.3758/s13428-023-02184-4

**Comment by KingArthur0205** [comment]
Working on this. Expected to return work today?(hopefully)

**Comment by KingArthur0205** [comment]
This dataset contians many rows. For ease of review, I have written some simple docomentation for understanding:

1. **External Questionnaries**: The dataset includes aggregate scores from external questionnaires used to validate the constructs discussed in the paper. These questionnaires correspond to the columns ```OCICV_total```, ```BIS_CV_total```, ```MFQ_total```, ```SCARED_total```, and ```WASIIQ```. As only the aggregate scores were provided, the individual questionnaire data have been excluded.
2. **No Detailed Responses for AES(Automatic Evaluation Scale):** Columns related to the AES, such as ```AES_behavioral```, ```AES_emotional```, and others, have been removed. These columns contained non-missing values only for those in Sample 1 (n=43). As only aggregate scores were provided for these fields, they have also been excluded.
3.  **Sample Column Removal:** The ```sample``` column has been removed. Although the dataset originally included 2 independent groups, the measures applied to both were identical, leading to their merger into a single group.
4. **Removal of ```Group``` Column:** The ```group```s indicated participants of different ages. I am removing this column for the same reason above. :)

**Comment by KingArthur0205** [comment]
Processed Data:
[AMI_CV.csv](https://github.com/user-attachments/files/16775994/AMI_CV.csv)

Code:
```
# Paper:https://link.springer.com/article/10.3758/s13428-023-02184-4
# Data: https://osf.io/t5js9/
library(tidyr)
library(dplyr)

data <- read.csv("./combined_data.csv")
data <- data |>
  select(userID, age, AMI_CV_1:AMI_CV_18) |> # Keep only items and relevant columns
  rename(id=userID)
data$id <- as.integer(rownames(data)) # Encode the ids of participants
data <- pivot_longer(data, cols=-c(age, id), names_to='item', values_to='resp')

save(data, file="AMI_CV.Rdata")
write.csv(data, "AMI_CV.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
i have two questions:
1. i see 194 and not 191 participants (see paper, they note n=191). that's not the biggest deal, perhaps they excluded 3 respondents. but i wanted to flag this to see if you had any thoughts. 
2. we have 18 items. that is surely this: "The original, adult AMI is an 18-item self-report questionnaire which assesses apathy in terms of behavioural activation (tendency to self-initiate goal-directed behaviour), social motivation (level of engagement in social interactions) and emotional sensitivity (level of emotional engagement) using a five-point Likert scale (range 0–4; (Supplementary Table 1; Ang et al., [2017](https://link.springer.com/article/10.3758/s13428-023-02184-4#ref-CR1)))." *right?* i just wanted to confirm given the above note you had left. 

i think we are fine here just wanted to make sure i'm following.

**Comment by KingArthur0205** [comment]
1. I just reviewed the data and think that there are 2 participants(userID 8387 and 8885) that have been counted twice. I think this might be a mistake?
The remaining one participant is userId 9937 because they declared their gender to be "other". The author removed them to "preserve homogeniety of variance."
3. Yes this is what I meant.

**Comment by ben-domingue** [comment]
can we remove 8387, 8885, and 9937 just to be on the safe side? 
thank you!!

**Comment by KingArthur0205** [comment]
Certainly! Another insight gained(Hooray!)
