### ISSUE TITLE
Filling the gap: Cloze probability and sentence constraint norms for 807 European Portuguese sentences

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#115]
https://link.springer.com/article/10.3758/s13428-023-02196-0

**Comment by KingArthur0205** [comment]
Working on this.
[Data](https://osf.io/85xy3/) for paper

**Comment by KingArthur0205** [comment]
The paper provides data with responses to each item, but it does not specify **which participant** gave each response. 

Unfortunately, this makes the data likely unprocessable.
