### ISSUE TITLE
Missing Code and Data: The Internal Representations Questionnaire (IRQ)

### ISSUE THREAD

**Issue by KingArthur0205** [ben-domingue/irw#126]
There is a [script file](https://github.com/ben-domingue/irw/blob/main/data/irq.R) with the same name as issue title in our repository, but neither the data nor script is completed. Perhaps I can take a look and process it if needed?

**Comment by ben-domingue** [comment]
hm. good eye. i likely decided this data wasn't 'in scope' but had started a file for processing. i likely need to delete this file.

**Comment by KingArthur0205** [comment]
I have made a PR to delete this file. :)
