### ISSUE TITLE
Veterans Affairs SSVF Survey 2016-17.Rdata

### ISSUE THREAD

**Issue by Lynn99kek** [ben-domingue/irw#13]
this is the source: https://www.data-liberation-project.org/datasets/va-ssvf-survey-data/`
[Veterans Affairs SSVF Survey 2016-17.csv](https://github.com/ben-domingue/irw/files/14590642/Veterans.Affairs.SSVF.Survey.2016-17.csv)

**Comment by Lynn99kek** [comment]
I am so sorry the csv file attatched above is wrong, here is the file: 
[Veterans Affairs SSVF Survey 2016-17.csv](https://github.com/ben-domingue/irw/files/14591913/Veterans.Affairs.SSVF.Survey.2016-17.csv)

**Comment by ben-domingue** [comment]
for this one, i think we should get rid of 6s perhaps? i looked at the documentation and couldn't find anything about those. 

> table(df$resp)

     1      2      3      4      5      6 
137208 129396  10728  24186  39205     61

**Comment by Lynn99kek** [comment]
OK! Here  is the revised version!
[Veterans Affairs SSVF Survey 2016-17.csv](https://github.com/ben-domingue/irw/files/14765549/Veterans.Affairs.SSVF.Survey.2016-17.csv)
