### ISSUE TITLE
Some students are more equal: Performance in Author Recognition Test and Title Recognition Test modulated by print exposure and academic background

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#137]
again, check whether this is duplciative author recognition test data

https://link.springer.com/article/10.3758/s13428-023-02330-y#data-availability
The raw data used for analysis and an example of the questionnaire as given to the participants are publicly available at https://osf.io/s6j2e/?view_only=7e8f0f874570449eb7ce0865f6d9e38b.

**Comment by KingArthur0205** [comment]
We don’t have this data yet.

However, the available datasets only provide aggregate statistics for the Author Recognition Test and Title Recognition Test. The only item-level data included is the number of hours each participant spent reading various genres of texts.

**Comment by ben-domingue** [comment]
thank you!

**Comment by KingArthur0205** [comment]
：）
