### ISSUE TITLE
Beyond Frequency: Evaluating the Validity of Assessing the Context, Duration, Ability, and Botherment of Depression and Anxiety Symptoms in South Brazil

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#160]
https://doi.org/10.1037/pas0001323

All data, study design, analysis plan, and analysis code for this study
have been made publicly available at the Open Science Framework
and can be accessed at https://osf.io/p8j2v. Preregistration with study
design and hypotheses is available at https://osf.io/gtm2j (Brümmer &
Hoffmann, 2021).

**Comment by KingArthur0205** [comment]
Working on this

**Comment by KingArthur0205** [comment]
Notes about processing this dataset:
1. **Removal of demographic data:** Removed columns ```Date_of_birth```, ```state```, ```skin_color```, ```sexual_orientation```, ```martial_status```, ```religion```, ```kids```, ```family_income```, ```cohabitants```, ```educational_attainment```, ```educational_years```, ```working_status```. These information were collected in the first section of the questionnarie.
2. **Removal of Unattended Tests**: For the participants in study 2, they didn't receive the items ```promis_dep_...``` and the values for those columns were NA. I have deleted these in the processed dataset.
3. **LTE-Q**: The dataset contains a column that lists only the questions clicked by participants from the 12-question questionnaire. For example, if a participant experienced 5 out of the 12 events, the ```lte_event``` column would contain those 5 events, separated by commas. I would like to separate this column into 12 individual items to maintain consistency with the format of the other questions in the questionnaire.

**Comment by ben-domingue** [comment]
1. sounds good
2. ok
3. yes that is perfect. thank you!!

**Comment by KingArthur0205** [comment]
> 3\. **LTE-Q**: The dataset contains a column that lists only the questions clicked by participants from the 12-question questionnaire. For example, if a participant experienced 5 out of the 12 events, the `lte_event` column would contain those 5 events, separated by commas. I would like to separate this column into 12 individual items to maintain consistency with the format of the other questions in the questionnaire.

I just realized that they have these listed as separate items. I simply deletd the `lte_event` as it is just a summary of responses of the separate columns

Processed Data(Too big as csv):
[BF_Brummer$Hoffman_2021.csv.zip](https://github.com/user-attachments/files/16874196/BF_Brummer.Hoffman_2021.csv.zip)

Code:
```
# Paper: https://doi.org/10.1037/pas0001323
# Data: https://osf.io/p8j2v
library(dplyr)
library(tidyr)

df <- readRDS("./Depression_and_anxiety_question_framing_data_set.Rds")
df <- df |>
  select(-Framing_sequence, -Sex, -Date_of_birth, # Removal of demographic data
         -state, -skin_color, -sexual_orientation, 
         -marital_status, -religion, -kids, -family_income, 
         -cohabitants, -educational_attainment, -educational_years, 
         -working_status, -Date_of_interview, -lte_events) |>
  rename(id=ID, group=Study, date=Date_time_of_interview, age=Age)
df$date <- as.numeric(as.POSIXct(df$date, format="%d/%m/%Y %H:%M:%S", tz="UTC")) # Change date to Unix timestamp

df <- df %>% # Mutate column value types for merging purpose
  mutate(across(-c(id, age, group, date), as.double)) 
df <- pivot_longer(df, cols=c(-id, -group, -date, -age), names_to='item', values_to='resp')

df <- df %>% # Filter out unattempted items of Study Group 2
  filter(!(grepl("^promis_dep", item) & group == "Study 2 - Frame primed by symptom" & is.na(resp)))
df <- df %>%
  filter(!(grepl("^promis_anx", item) & group == "Study 2 - Frame primed by symptom" & is.na(resp)))
na_count <- which(is.na(df$resp))

save(df, file="BF_Brummer$Hoffman_2021.Rdata")
write.csv(df, "BF_Brummer$Hoffman_2021.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
> This dataset includes various questionnaires with different scales (3-point, 4-point, 5-point, True/False). I assume we don’t need to re-scale them, as the scales are intrinsic to the design of each questionnaire. Please let me know if this assumption is incorrect. :)

@ben-domingue Please let me know if you have any suggestion on this :)

**Comment by ben-domingue** [comment]
> This dataset includes various questionnaires with different scales (3-point, 4-point, 5-point, True/False). I assume we don’t need to re-scale them, as the scales are intrinsic to the design of each questionnaire. Please let me know if this assumption is incorrect. :)

That's right. It's fine for some items to have 3-points (0/1/2 or 1/2/3) and some to have 4-points. The true/false ones would need to be rescaled however. @KingArthur0205

**Comment by KingArthur0205** [comment]
> That's right. It's fine for some items to have 3-points (0/1/2 or 1/2/3) and some to have 4-points. The true/false ones would need to be rescaled however. @KingArthur0205

Got it! In this one the True/False values are encoded as 1/0s in the datasets already. Thanks for the clarification

**Comment by KingArthur0205** [comment]
PR created for this issue: https://github.com/ben-domingue/irw/pull/176

Please let me know if there is any changes needed. :)

**Comment by ben-domingue** [comment]
split to different scales and added, see code @KingArthur0205 for small change ;)
https://github.com/ben-domingue/irw/blob/main/data/BF_BrummerHoffman_2021.R

**Comment by KingArthur0205** [comment]
> split to different scales and added, see code @KingArthur0205 for small change ;)
> 
> https://github.com/ben-domingue/irw/blob/main/data/BF_BrummerHoffman_2021.R

Hooray job is done. See u tomorrow (on GitHub)! Have a great day
