### ISSUE TITLE
Covid-19 affects taste independent of taste–smell confusions: results from a combined chemosensory home test and online survey from a large global cohort 

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#164]
https://academic.oup.com/chemse/article/doi/10.1093/chemse/bjad020/7205685#412854156

Data and code are available in the project GitHub repository (https://github.com/GCCR/GCCR004) with Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License (CC BY-NC-ND 4.0; https://creativecommons.org/licenses/by-nc-nd/4.0/).

**Comment by KingArthur0205** [comment]
The GitHub link appears to be broken, and I also checked the "Data Availability" section of the paper, which returned a 404 error.

**Comment by ben-domingue** [comment]
i emailed the authors, we'll see if they respond.
