### ISSUE TITLE
Resistance.RData

### ISSUE THREAD

**Issue by anniehang** [ben-domingue/irw#17]
[Resistance.csv](https://github.com/ben-domingue/irw/files/14611954/Resistance.csv)

line 77

this is the source of the data: https://link.springer.com/article/10.3758/s13428-022-01876-7#data-availability

**Comment by ben-domingue** [comment]
confirming that the resp=5 options are ok. i think they are based on my perusal of the paper. i'm going to add this data to the irw but let me know if you agree.

**Comment by anniehang** [comment]
I think the options of resp=5 are ok, and we can add the data to the IRW.

**Comment by ben-domingue** [comment]
great!
