### ISSUE TITLE
approaches_to_text_study1.Rdata &  approaches_to_text_study2.Rdata

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#20]
@anniehang see lines 10 & 11 [here](https://docs.google.com/spreadsheets/d/1nhPyvuAm3JO8c9oa1swPvQZghAvmnf4xlYgbvsFH99s/edit#gid=0). maybe i already got these! :scream:

**Comment by ben-domingue** [comment]
if you agree we can close this issue and scratch that data out on the group data work sheet.

**Comment by anniehang** [comment]
ok！

**Comment by ben-domingue** [comment]
@anniehang let me know what you think but maybe we already have this data. apologies, maybe a pointer that we should check the reference in the master sheet prior to serious work :)

**Comment by anniehang** [comment]
it's ok! I can move on to process another data :)
