### ISSUE TITLE
Estimating Explanatory Extensions of Dichotomous and Polytomous Rasch Models: The eirm Package in R

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#209]
[check that we don't have this already]

https://www.mdpi.com/2624-8611/3/3/23
https://osf.io/eapd8/

**Comment by KingArthur0205** [comment]
Working on this. Don't think we have this yet.

**Comment by KingArthur0205** [comment]
This paper includes 1 dataset, which has already been processed into the long format.

A few notes on the operations done to the dataset:
1. Deletion of the ```agree``` column: The author encoded "strongly agree" and "agree" as 1 and stored in the extra column ```agree```. Deleted
2. Deletion of the ```position``` column: Indicator of the demonstration sequence of all items. Deleted.

**Comment by KingArthur0205** [comment]
Data:
[EEEDPRM_Bulut_2021.csv](https://github.com/user-attachments/files/16917241/EEEDPRM_Bulut_2021.csv)

Code:
```
# Paper: https://www.mdpi.com/2624-8611/3/3/23
# Data: https://osf.io/eapd8/
library(haven)
library(dplyr)
library(tidyr)

df <- read.csv("./rse_long.csv")
df <- df |>
  select(-country, -wording, -position, -gender2, -agree) |>
  rename(id = person, rsp=response)

save(df, file="EEEDPRM_Bulut_2021.Rdata")
write.csv(df, "EEEDPRM_Bulut_2021.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
three things:
1. change column `rsp` -> `resp`. i would change this myself but i wanted to confer about the others.
2. the `position` column is the order in which the items are presented? let's actually keep this. an ex-student and i have (a paper)[https://osf.io/preprints/psyarxiv/hn2p5] coming out about this, more data on position would be valuable. 
3. confirming that you do not think we are throwing data away with the deletion of the `agree` column. correct? the 0/1/2/3 responses seem ok; data from another rosenberg scale that i have is similarly in 4 categories

**Comment by KingArthur0205** [comment]
> three things:
> 
> 1. change column `rsp` -> `resp`. i would change this myself but i wanted to confer about the others.

On it

> 2. the `position` column is the order in which the items are presented? let's actually keep this. an ex-student and i have (a paper)[https://osf.io/preprints/psyarxiv/hn2p5] coming out about this, more data on position would be valuable.

On it

> 3. confirming that you do not think we are throwing data away with the deletion of the `agree` column. correct? the 0/1/2/3 responses seem ok; data from another rosenberg scale that i have is similarly in 4 categories

Yes. 0/1 in the resp columns are mapped to 0 in ```agree```, and 2/3 are mapped to 1 in ```agree```

**Comment by ben-domingue** [comment]
perfect, if you can tweak 1 & 2 that'd be great!

**Comment by KingArthur0205** [comment]
Updated in the cell above.

**Comment by KingArthur0205** [comment]
PR for this issue: https://github.com/ben-domingue/irw/pull/213
