### ISSUE TITLE
Psychometric Properties, Factor Structure, and Validity of the Sensitivity to Threat and Affiliative Reward Scale (STARS) in Children and Adults

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#211]
https://osf.io/5qxv6/

need to search for paper

**Comment by KingArthur0205** [comment]
Paper: https://pubmed.ncbi.nlm.nih.gov/36245403/

Woring on this

**Comment by KingArthur0205** [comment]
This paper mentions that 3 samples were collected. However, only the dataset of the 1st sample is provided in the OSF repository.

***Sample 1***: 303 parents completed the Sensitivity to Threat and Affiliative Reward Scale (STARS) survey, which includes 64 items. The No. of items and participants aligns with the provided dataset.
***Sample 2***: Missing
***Sample 3***: Missing

The following columns are deleted as they are either demographic data or aggregate stats: ```site```, ```Edbinary```(Parent Education), ```MonInc```(Monthly Income), ```Childage```, ```childsex```, ```childeth```(Child Ethnicity), ```parentage```, ```parented```, ```parentsex```, ```parenteth```, ```BISsinhib```, ```BASDrive```, BASFun```, ```BASRR```, ```BASTOT```, ```SDPconp```, ```ICU```, ```CBCLODD```, ```CBCLADHD```, ```PhysicalAffiliation```, ```SocialThreat```, ```NonSocThreat```, ```Affiliation_items```, ```Threat_items```, ```NonPhysicalAffiliation```.

**Comment by KingArthur0205** [comment]
Data:
[STARSinCA_Perlstein_2022.csv](https://github.com/user-attachments/files/16915085/STARSinCA_Perlstein_2022.csv)

Code:
```
# Paper: https://pubmed.ncbi.nlm.nih.gov/36245403/
# Data: https://osf.io/5qxv6/
library(haven)
library(dplyr)
library(tidyr)

df <- read_sav("STARS_Sample1.sav")
colnames(df) <- gsub("\\s*\\(.*\\)", "", colnames(df)) # Remove column labels
df <- lapply(df, function(x) { attr(x, "label") <- NULL; x })
df <- as.data.frame(df)

df <- df |>
  select(ID, starts_with("STAR")) |>
  rename(id=ID)
df[df == -9999] <- NA
df <- pivot_longer(df, cols=-id, names_to="item", values_to = "resp")

save(df, file="STARSinCA_Perlstein_2022.Rdata")
write.csv(df, "STARSinCA_Perlstein_2022.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
excellent and don't worry about a pull request, i just dropped code into a file and am pushing now
