### ISSUE TITLE
The Perceptions of Bilingualism Scales

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#212]
https://osf.io/preprints/psyarxiv/s32zb
https://osf.io/yw7t2/?view_only=

**Comment by KingArthur0205** [comment]
Working on this

**Comment by KingArthur0205** [comment]
Data:
Dataset 1: [PBS_Surrain_2019_PoB.csv](https://github.com/user-attachments/files/16914585/PBS_Surrain_2019_PoB.csv)
Dataset 2: [PBS_Surrain_2019_PoB+.csv](https://github.com/user-attachments/files/16914586/PBS_Surrain_2019_PoB%2B.csv)

Code:
```
# Paper: https://osf.io/preprints/psyarxiv/s32zb
# Data: https://osf.io/yw7t2/?view_only=
library(dplyr)
library(tidyr)
library(haven)

# ------ Process Dataset 1 ------
study1_df <- read_dta("./2019_07_07_PoB_OSF.dta")
colnames(study1_df) <- gsub("\\s*\\(.*\\)", "", colnames(study1_df)) # Remove column labels
study1_df <- lapply(study1_df, function(x) { attr(x, "label") <- NULL; x })
study1_df <- as.data.frame(study1_df)

study1_df <- study1_df |>
  select(-qualtrics, -mturk, -yearsed, -p_ed, -spansurv, -female, -bornUS, 
         -yrs_us, -imm_age, -region, -KIDItotalpts, -femchild, 
         -p1spks_ch, -p2spks_ch, -parent, -L1EngNoL2, -p1spksch_imputed, 
         -L1_derived, -L2_derived) |>
  rename(age=p_age)
study1_df <- pivot_longer(study1_df, cols=-c(id, age), names_to="item", values_to="resp")

# ------ Process Dataset 2 ------
study2_df <- read_dta("./PoB_TPS_2022_OSF_keyvars.dta")
colnames(df) <- gsub("\\s*\\(.*\\)", "", colnames(study2_df)) # Remove column labels
study2_df <- lapply(study2_df, function(x) { attr(x, "label") <- NULL; x })
study2_df <- as.data.frame(study2_df)

study2_df <- study2_df |>
  select(-yearsed, -spansurv, -female, -bornUS, -region, -zipcode,
         -homeusage, -langback, -perclote_2016, -logplote_2016, -mturk, 
         -meanPOBp_6item, -age_cat, -tellstories, -talkchild, -sing, -read,
         -MUNE_reads_dich, -RQ2_sample, -meanPOB10) |>
  rename(id=ResponseID, age=p_age)
study2_df <- pivot_longer(study2_df, cols=-id, names_to="item", values_to="resp")

save(study1_df, file="PBS_Surrain_2019_PoB.Rdata")
write.csv(study1_df, "PBS_Surrain_2019_PoB.csv", row.names=FALSE)
save(study2_df, file="PBS_Surrain_2019_PoB+.Rdata")
write.csv(study2_df, "PBS_Surrain_2019_PoB+.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
I'm a little confused here. They seem to have an 8 item scale (POB+) and a 13 item scale (POB). When I look at items I see and 17 for POB+ and 22 for POB. Something is off. I'm noting a 'age' and 'race' item which are definitely wrong but I'm not entirely sure how we went from 8->17 and 13->22. 

@KingArthur0205 flagging some issues

**Comment by KingArthur0205** [comment]
This dataset contains a set of "POB" questions and an additional set of 8 "POB+" questions for each of the datasets, which are the ```POBPlus_x``` columns in the dataset.

**Comment by ben-domingue** [comment]
Two questions: 
1. age and race still need to go though, correct? 
2. are the POB+ items the same across both? if so i might be inclined to jam this into a single dataset (while perhaps including a little info about the sample). 

if the answer to 2 is yes let me look at the raw data a little more. 
thank you!!

**Comment by KingArthur0205** [comment]
> 1. age and race still need to go though, correct?

Yes, sorry I need to wake up.

> 2. are the POB+ items the same across both? if so i might be inclined to jam this into a single dataset (while perhaps including a little info about the sample).

Yes, the 2 POB+ questions are the same across 2 datasets. However, the POB questions are different. Perhaps we can merge the POB+ questions into an additional dataset.

**Comment by ben-domingue** [comment]
i'd actually vote to just put them all in the same dataset. let me make a general observation as it might help. suppose we have 3 blocks of items, `x1 x2 x3` and two groups of people `g1 g2`. if we then have a case wherein
```
,x1,x2,x3  
g1,X,X,0  
g2,0,X,X  
```
such that 
- `g1` takes `x1` and `x2`
- `g2` takes `x2` and `x3`

there are lots of ways of 'equating' things such that all the items are on the same scale. this depends on the `x1` and `x3` items being somewhat interchangeable which i'd argue that they are here (more or less). thus i'd be inclined to just chunk everything together.

**Comment by KingArthur0205** [comment]
Understood. Then, in this way we might need to change the naming of the POB questions. Maybe insert their labels(full questions) into the names of those PoB items :)

**Comment by KingArthur0205** [comment]
Code and data updated in the post above. I have added an extra column ```group``` to indicate their different origins.

**Comment by ben-domingue** [comment]
this structure is great! 
![image](https://github.com/user-attachments/assets/4f4b3b1b-38d1-427f-b7b4-4eab8f746f5b)

**Comment by ben-domingue** [comment]
done and i added code. nice!

**Comment by KingArthur0205** [comment]
> done and i added code. nice!

Thx! I was just about to create PR. :)

**Comment by KingArthur0205** [comment]
Should probably do it faster next time:)

**Comment by ben-domingue** [comment]
no worries ;)
i don't know how messy the PR is. i can also add code from my end if it is work on your side.

**Comment by KingArthur0205** [comment]
> no worries ;) i don't know how messy the PR is. i can also add code from my end if it is work on your side.

No no no, it doesn't bother me at all. I actually enjoying creating PR cz it gives me this weird sense of achievement of getting somethign done. :)

**Comment by ben-domingue** [comment]
ha! i shall leave it to you then
