### ISSUE TITLE
Psychometric evaluation of the Santa Clara Brief Compassion Scale in the Czech environment (SCBCS)

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#245]
https://osf.io/h9ktr/

https://www.tandfonline.com/doi/abs/10.1080/13674676.2020.1850666

**Comment by KingArthur0205** [comment]
**Santa Clara Brief Compassion Scale (SCBCS_df) **: 572 participants. The SCBCS contains five items on a seven point Likert Scale which correspond to the intensity with which the respondent experiences compassion (from 1 – not at all true for me, to 7 – very true for me).

**Daily Spiritual Experience Scale (SPIRIT_df)**:572 participants.15 – item version. This scale measures the subjective connection with the transcendent on a scale from one (always) to six (never).

**Comment by KingArthur0205** [comment]
AHHH another one without license. Sorry :(

Data:
[PeSCBCSCe_Novak_2020_CSV.zip](https://github.com/user-attachments/files/17329073/PeSCBCSCe_Novak_2020_CSV.zip)

Code:
```
# Paper:https://www.tandfonline.com/doi/abs/10.1080/13674676.2020.1850666
# Data: https://osf.io/h9ktr/

library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)
library(readr)
library(readxl)
library(sas7bdat)

remove_na <- function(df) {
  df <- df[!(rowSums(is.na(df[, -which(names(df) %in% c("id", "date"))])) == (ncol(df) - 2)), ]
  return(df)
}

data_df <- read_csv("data_share.csv")

data_df <- data_df %>%
  rename(id = ID)

SCBCS_df <- data_df |>
  select(starts_with("SCBCS"), id)
SCBCS_df  <- remove_na(SCBCS_df)
SCBCS_df <- pivot_longer(SCBCS_df, cols=-c(id), names_to="item", values_to="resp")

save(SCBCS_df, file="PeSCBCSCe_Novak_2020_SCBCS.Rdata")
write.csv(SCBCS_df, "PeSCBCSCe_Novak_2020_SCBCS.csv", row.names=FALSE)

SPIRIT_df <- data_df |>
  select(starts_with("SPIRIT"), id)
SPIRIT_df <- remove_na(SPIRIT_df)
SPIRIT_df <- pivot_longer(SPIRIT_df, cols=-c(id), names_to="item", values_to="resp")

save(SCBCS_df, file="PeSCBCSCe_Novak_2020_SPIRIT.Rdata")
write.csv(SCBCS_df, "PeSCBCSCe_Novak_2020_SPIRIT.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
ship pull request in case they approve data?  @KingArthur0205

**Comment by KingArthur0205** [comment]
PR for issue: https://github.com/ben-domingue/irw/pull/611

**Comment by ben-domingue** [comment]
approved 10-29-2024 @ben-domingue

**Comment by KingArthur0205** [comment]
@ben-domingue I just checked and the data files seem to be already included both in dictionary and on Redivis.

**Comment by ben-domingue** [comment]
@KingArthur0205 they are on dictionary but i don't think on redivis? i am adding them to redivis now.
