### ISSUE TITLE
Psychometric validation of the polish version of the emotional style questionnaire

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#273]
https://link.springer.com/article/10.1007/s12144-022-03323-4

https://osf.io/twzq4/

**Comment by KingArthur0205** [comment]
working on it

**Comment by KingArthur0205** [comment]
1. **ESQ_df**: There were552 participants in Study 1, 418 participants in Study 2, and 976 participants in Study 3. Responses were measured on a scale from 1 to 7. 

    In the 1st waves of both Study 1 and Study 2, 24 items were administered, while 14 items were administered in the 2nd waves. For Study 3, 10 items were administered in the first wave, and 14 items in the second wave. 

2. **study2_LOTR_df:** This dataset includes participants only from Study 2, with 403 participants completing the questionnaire in both the 1st and 2nd waves. In the 1st wave, there were 10 items, while there were 3 items in the second wave. Responses were measured on a scale from 1 to 5, which is **inconsistent with the paper** indicating the LOTR scale should range from 1 to 7.

3. **study2_AttentControl_df:** This dataset includes participants only from Study 2, with 407 participants completing the questionnaire in both the 1st and 2nd waves. In the 1st wave, there were 20 items, while there were 11 items in the second wave. Responses were measured on a scale from 1 to 4.

4. **study2_BIDR_df:** This dataset includes participants only from Study 2, with 405 participants completing the questionnaire in both the 1st and 2nd waves. In the 1st wave, there were 40 items, while there were 20 items in the second wave. Responses were measured on a scale from 1 to 7.

5. **study2_MAIA_df:** This dataset includes participants only from Study 2, with 405 participants completing the questionnaire in both the 1st and 2nd waves. In the 1st wave, there were 32 items, while there were 5 items in the 2nd wave. Responses were measured on a scale from 1 to 6, which is **inconsistent with the publication** that describes a six-point Likert scale ranging from 0 (“it does not apply to me at all”) to 6 (“it applies to me very much”).

6. **study2_MAAS_df:** This dataset includes participants only from Study 2, with 405 participants completing the questionnaire in the first wave, where 15 items were administered. Responses were measured on a scale from 1 to 6.

7. **study2BRC_df:** This dataset includes participants only from Study 2, with 410 participants completing the questionnaire in the first wave, where 4 items were administered. Responses were measured on a scale from 1 to 5.

8. **study2_AQ_df:** This dataset includes participants only from Study 2, with 405 participants completing the questionnaire in both the first and second waves. In both waves, 10 items were administered. Responses were measured on a scale from 1 to 4.

**Comment by KingArthur0205** [comment]
Data:
[PvPvESQ_Gasiorowska_2021_Rdata.zip](https://github.com/user-attachments/files/17245856/PvPvESQ_Gasiorowska_2021_Rdata.zip)
[PvPvESQ_Gasiorowska_2021_CSV.zip](https://github.com/user-attachments/files/17245817/PvPvESQ_Gasiorowska_2021_CSV.zip)

Code:
```
# Paper: https://link.springer.com/article/10.1007/s12144-022-03323-4
# Data: https://osf.io/twzq4/files/osfstorage
library(haven)
library(dplyr)
library(tidyr)

remove_na <- function(df) {
  df <- df[!(rowSums(is.na(df[, -which(names(df) %in% c("id"))])) == (ncol(df) - 1)), ]
  return(df)
}

study1test_df <- read_sav("Study 1 + test retest.sav")
study1_df <- read_sav("Study 1 + language equivalence.sav") 
study2_df <- read_sav("Study 2.sav") 
study3_df <- read_sav("Study 3 - 3 PL sample + new US sample.sav") 

# ------ Dataset Pre-process ------

study1_df[] <- lapply(study1_df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})

study1test_df <- study1test_df |>
  filter(ACH1_valid != 0)

study1test_df <- study1test_df |>
  filter(ACH2_valid != 0)

study1_df <- study1_df |>
  filter(ACH1_valid != 0)

study1_df <- study1_df |>
  filter(ACH2_valid != 0)

study1_df <- study1_df %>%
  mutate(id = row_number() )

study2_df[] <- lapply(study2_df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})

study2_df <- study2_df |>
  filter(valid != 0)

study2_df <- study2_df %>%
  mutate(id = row_number() )

study3_df[] <- lapply(study3_df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})

study3_df <- study3_df |>
  filter(study == 6)

study3_df <- study3_df %>%
  mutate(id = row_number() )

# -----ESQ dataset
study1ESQ_df <- study1_df |>
  select(starts_with("ESQ"),id, -ends_with("_R"))

study1ESQ_df  <- remove_na(study1ESQ_df )
study1ESQ_df  <- pivot_longer(study1ESQ_df , cols=-c(id), names_to="item", values_to="resp")

study1ESQR_df <- study1_df |>
  select(matches("^ESQ.*_R$"), id)

study1ESQR_df  <- remove_na(study1ESQR_df )
study1ESQR_df  <- pivot_longer(study1ESQR_df , cols=-c(id), names_to="item", values_to="resp")

study1ESQ_df $wave <- 0
study1ESQR_df$wave <- 1

study1_ESQ_df <- rbind(study1ESQ_df,study1ESQR_df )

study2ESQ_df <- study2_df |>
  select(starts_with("ESQ"),id, -ends_with("_R"))

study2ESQ_df  <- remove_na(study2ESQ_df )
study2ESQ_df  <- pivot_longer(study2ESQ_df , cols=-c(id), names_to="item", values_to="resp")

study2ESQR_df <- study2_df |>
  select(matches("^ESQ.*_R$"), id)

study2ESQR_df  <- remove_na(study2ESQR_df )
study2ESQR_df  <- pivot_longer(study2ESQR_df , cols=-c(id), names_to="item", values_to="resp")

study2ESQ_df $wave <- 0
study2ESQR_df$wave <- 1

study2_ESQ_df <- rbind(study2ESQ_df,study2ESQR_df )

study3ESQ_df <- study3_df |>
  select(starts_with("ESQ"),id, -ends_with("_R"))

study3ESQ_df  <- remove_na(study3ESQ_df )
study3ESQ_df  <- pivot_longer(study3ESQ_df , cols=-c(id), names_to="item", values_to="resp")

study3ESQR_df <- study3_df |>
  select(matches("^ESQ.*_R$"), id)

study3ESQR_df  <- remove_na(study3ESQR_df )
study3ESQR_df  <- pivot_longer(study3ESQR_df , cols=-c(id), names_to="item", values_to="resp")

study3ESQ_df $wave <- 0
study3ESQR_df$wave <- 1

study3_ESQ_df <- rbind(study3ESQ_df,study3ESQR_df )

ESQ_df <- rbind(study1_ESQ_df,study2_ESQ_df, study3_ESQ_df )

save(ESQ_df, file="PVPVESQ_Gasiorowska_2021_ESQ.Rdata")
write.csv(ESQ_df, "PVPVESQ_Gasiorowska_2021_ESQ.csv", row.names=FALSE)

# -----LOTR Revised dataset 
study2LOTR_df <- study2_df |>
  select(starts_with("LOTR"), id, -LOTR)

study2LOTR_df  <- remove_na(study2LOTR_df)
study2LOTR_df  <- pivot_longer(study2LOTR_df , cols=-c(id), names_to="item", values_to="resp")

study2LOTRR_df  <- study2_df |>
  select(matches("^LOTR.*_R$"), id)

study2LOTRR_df   <- remove_na(study2LOTRR_df)
study2LOTRR_df <- pivot_longer(study2LOTRR_df, cols=-c(id), names_to="item", values_to="resp")

study2LOTR_df  $wave <- 0
study2LOTRR_df  $wave <- 1

study2_LOTR_df <- rbind(study2LOTR_df,study2LOTRR_df )

save(study2_LOTR_df, file="PVPVESQ_Gasiorowska_2021_study2_LOTR.Rdata")
write.csv(study2_LOTR_df, "PVPVESQ_Gasiorowska_2021_study2_LOTR.csv", row.names=FALSE)

# -----AttentControl dataset 
study2AttentControl_df <- study2_df |>
  select(starts_with("AttentControl"), id, , -ends_with("_r"))

study2AttentControl_df  <- remove_na(study2AttentControl_df )
study2AttentControl_df  <- pivot_longer(study2AttentControl_df  , cols=-c(id), names_to="item", values_to="resp")


study2AttentControlR_df  <- study2_df |>
  select(matches("^AttentControl.*_R$"), id)

study2AttentControlR_df   <- remove_na(study2AttentControlR_df)
study2AttentControlR_df  <- pivot_longer(study2AttentControlR_df, cols=-c(id), names_to="item", values_to="resp")

study2AttentControl_df   $wave <- 0
study2AttentControlR_df  $wave <- 1

study2_AttentControl_df <- rbind(study2AttentControl_df,study2AttentControlR_df )

save(study2_AttentControl_df, file="PVPVESQ_Gasiorowska_2021_study2_AttentControl_df.Rdata")
write.csv(study2_AttentControl_df, "PVPVESQ_Gasiorowska_2021_study2_AttentControl_df.csv", row.names=FALSE)

# -----BIDR dataset 
study2BIDR_df <- study2_df |>
  select(starts_with("BIDR"), id, -ends_with("_r"))

study2BIDR_df  <- remove_na(study2BIDR_df )
study2BIDR_df  <- pivot_longer(study2BIDR_df , cols=-c(id), names_to="item", values_to="resp")

study2BIDRR_df  <- study2_df |>
  select(matches("^BIDR.*_r$"), id)

study2BIDRR_df   <- remove_na(study2BIDRR_df)
study2BIDRR_df  <- pivot_longer(study2BIDRR_df, cols=-c(id), names_to="item", values_to="resp")

study2BIDR_df$wave <- 0
study2BIDRR_df$wave <- 1

study2_BIDR_df <- rbind(study2BIDR_df,study2BIDRR_df )

save(study2_BIDR_df, file="PVPVESQ_Gasiorowska_2021_study2_BIDR_df.Rdata")
write.csv(study2_BIDR_df, "PVPVESQ_Gasiorowska_2021_study2_BIDR_df.csv", row.names=FALSE)

# ----- MAIA dataset 
study2MAIA_df <- study2_df |>
  select(starts_with("MAIA"), id, -ends_with("_r"),-MAIA)

study2MAIA_df <- remove_na(study2MAIA_df)
study2MAIA_df  <- pivot_longer(study2MAIA_df, cols=-c(id), names_to="item", values_to="resp")

study2MAIAR_df  <- study2_df |>
  select(matches("^MAIA.*_r$"), id)

study2MAIAR_df   <- remove_na(study2MAIAR_df)
study2MAIAR_df  <- pivot_longer(study2MAIAR_df, cols=-c(id), names_to="item", values_to="resp")

study2MAIA_df$wave <- 0
study2MAIAR_df$wave <- 1

study2_MAIA_df <- rbind(study2MAIA_df,study2MAIAR_df )

save(study2_MAIA_df, file="PVPVESQ_Gasiorowska_2021_study2_MAIA_df.Rdata")
write.csv(study2_MAIA_df, "PVPVESQ_Gasiorowska_2021_study2_MAIA_df.csv", row.names=FALSE)

# ----- MAAS dataset 
study2MAAS_df <- study2_df |>
  select(starts_with("MAAS"), id, -MAAS)

study2MAAS_df <- remove_na(study2MAAS_df)
study2MAAS_df <- pivot_longer(study2MAAS_df, cols=-c(id), names_to="item", values_to="resp")

save(study2MAAS_df, file="PVPVESQ_Gasiorowska_2021_study2MAAS_df.Rdata")
write.csv(study2MAAS_df, "PVPVESQ_Gasiorowska_2021_study2MAAS_df.csv", row.names=FALSE)

# ----- BRC dataset 
study2BRC_df <- study2_df |>
  select(starts_with("BRC"), id, -BRC)

study2BRC_df <- remove_na(study2BRC_df)
study2BRC_df <- pivot_longer(study2BRC_df, cols=-c(id), names_to="item", values_to="resp")

save(study2BRC_df, file="PVPVESQ_Gasiorowska_2021_study2BRC_df.Rdata")
write.csv(study2BRC_df, "PVPVESQ_Gasiorowska_2021_study2BRC_df.csv", row.names=FALSE)

# ----- AQ dataset 
study2AQ_df <- study2_df |>
  select(starts_with("AQ"), id, -ends_with("_r"))

study2AQ_df <- remove_na(study2AQ_df)
study2AQ_df  <- pivot_longer(study2AQ_df, cols=-c(id), names_to="item", values_to="resp")

study2AQR_df  <- study2_df |>
  select(matches("^AQ.*_r$"), id)

study2AQR_df <- remove_na(study2AQR_df )
study2AQR_df <- pivot_longer(study2AQR_df, cols=-c(id), names_to="item", values_to="resp")

study2AQ_df$wave <- 0
study2AQR_df$wave <- 1

study2_AQ_df <- rbind(study2AQ_df, study2AQR_df)

save(study2_AQ_df, file="PVPVESQ_Gasiorowska_2021_study2_AQ_df.Rdata")
write.csv(study2_AQ_df, "PVPVESQ_Gasiorowska_2021_study2_AQ_df.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
@KingArthur0205 say more? i'm not quite sure i follow

**Comment by KingArthur0205** [comment]
> 2. **study2_LOTR_df:** This dataset includes participants only from Study 2, with 403 participants completing the questionnaire in both the 1st and 2nd waves. In the 1st wave, there were 10 items, while there were 3 items in the second wave. Responses were measured on a scale from 1 to 5, which is **inconsistent with the paper** indicating the LOTR scale should range from 1 to 7.

The scale of this dataset is 1 to 5. However, in the paper the author suggested the scale to be 1 to 7.

> 5. **study2_MAIA_df:** This dataset includes participants only from Study 2, with 405 participants completing the questionnaire in both the 1st and 2nd waves. In the 1st wave, there were 32 items, while there were 5 items in the 2nd wave. Responses were measured on a scale from 1 to 6, which is **inconsistent with the publication** that describes a six-point Likert scale ranging from 0 (“it does not apply to me at all”) to 6 (“it applies to me very much”).


Similarly, the author suggested a 0-6 scale in the paper, but no 0s are found in the datasets.

**Comment by ben-domingue** [comment]
OK so to confirm you are flagging idiosyncracies between the data and the reporting but you are confident that the data you've got posted above is the best we can do given the resources they have posted? @KingArthur0205

**Comment by KingArthur0205** [comment]
Yes, I just double-checked the paper and they didn't mention any techniques/processing of the 2 datasets mentioend above. Everything else should be good :)

**Comment by ben-domingue** [comment]
note to self: i sent email to author re license

**Comment by KingArthur0205** [comment]
@ben-domingue I don't think that these different scales can be combined as they have different set of items. However, ERQ has data collected from 3 studies, and I have combined them into 1 dataset.

I actually spotted another problem within the code(specifically when processing ERQ). It would be great if you can use the latest data and code :)

**Comment by ben-domingue** [comment]
OK i have updated these. Closing this now pending email from author.

**Comment by KingArthur0205** [comment]
Oh I just realized this is a legacy one that was created before introducing the "need license" label :((

**Comment by ben-domingue** [comment]
yeah apologies.
