### ISSUE TITLE
spelling assessment_study1&2

### ISSUE THREAD

**Issue by anniehang** [ben-domingue/irw#29]
[spelling assessment_study1.csv](https://github.com/ben-domingue/irw/files/14784525/spelling.assessment_study1.csv)
[spelling assessment_study2.csv](https://github.com/ben-domingue/irw/files/14784528/spelling.assessment_study2.csv)

line 81
this is the source of the data: https://link.springer.com/article/10.3758/s13428-022-01834-3#Ack1

**Comment by ben-domingue** [comment]
thank you! @anniehang where did you pull the data from?

**Comment by ben-domingue** [comment]
note to bd: these data are in /pub/

**Comment by ben-domingue** [comment]
but need to be added to metadata

**Comment by ben-domingue** [comment]
Where does one go to download the data? I can't quite figure that part out.

**Comment by anniehang** [comment]
At the end of the article, a link to download the data is provided.
https://osf.io/7tuwr/?view_only=c62d60752bbd48fa8dd7cc3ee092ea51
