### ISSUE TITLE
Assessing psychological flexibility: The psychometric properties of the Czech translation of the CompACT questionnaire

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#295]
https://ceskoslovenskapsychologie.cz/index.php/csps/article/view/370

https://osf.io/cwjxq/

**Comment by ben-domingue** [comment]
Monica Chen & I

**Comment by Monicaxichen** [comment]
[VA scale_CompACT_Ptacek 2024.csv](https://github.com/user-attachments/files/17332597/VA.scale_CompACT_Ptacek.2024.csv)

**Comment by Monicaxichen** [comment]
[BA scale_CompACT_Ptacek 2024.csv](https://github.com/user-attachments/files/17332599/BA.scale_CompACT_Ptacek.2024.csv)

**Comment by Monicaxichen** [comment]
[OE scale_CompACT_Ptacek 2024.csv](https://github.com/user-attachments/files/17332600/OE.scale_CompACT_Ptacek.2024.csv)

**Comment by ben-domingue** [comment]
@Monicaxichen i have one question and a request. i think what we are getting is the 17 item COMPACT scale they discuss in the abstract [here](https://ceskoslovenskapsychologie.cz/index.php/csps/article/view/370). we have 18 items in total across the 3 files you sent so i just wanted to see if you had any insight into the 17/18 difference. 

and in this case i think we want the 3 scales together. i'll acknowledge that there is frequently some ambiguity about whether to split or lump. my goal is to generally lump things together that are thought of as being part of one measure and i think the 3 subscales here meet that requirement.

**Comment by Monicaxichen** [comment]
Hi Ben,

I got it. You are right.

My bad, I accidently included VA5 which should not be in the 17items scale. Must be my mistake when dropping items from the original data.

Sure. That makes sense to keep three scales in one file. I will modify that and upload new file soon.



Best,
Monica

From: Ben Domingue ***@***.***>
Date: Thursday, October 10, 2024 at 2:11 PM
To: ben-domingue/irw ***@***.***>
Cc: Monica (Xi) Chen ***@***.***>, Mention ***@***.***>
Subject: Re: [ben-domingue/irw] Assessing psychological flexibility: The psychometric properties of the Czech translation of the CompACT questionnaire (Issue #295)

@Monicaxichen<https://github.com/Monicaxichen> i have one question and a request. i think what we are getting is the 17 item COMPACT scale they discuss in the abstract here<https://ceskoslovenskapsychologie.cz/index.php/csps/article/view/370>. we have 18 items in total across the 3 files you sent so i just wanted to see if you had any insight into the 17/18 difference.

and in this case i think we want the 3 scales together. i'll acknowledge that there is frequently some ambiguity about whether to split or lump. my goal is to generally lump things together that are thought of as being part of one measure and i think the 3 subscales here meet that requirement.

**Comment by ben-domingue** [comment]
@Monicaxichen no worries! and thank you :)

**Comment by Monicaxichen** [comment]
[CompACT_Ptacek 2024.csv](https://github.com/user-attachments/files/17334842/CompACT_Ptacek.2024.csv)

**Comment by Monicaxichen** [comment]
[Codebook_CompACT_Ptacek 2024..xlsx](https://github.com/user-attachments/files/17334843/Codebook_CompACT_Ptacek.2024.xlsx)

**Comment by Monicaxichen** [comment]
import excel "/Users/xichen85/Desktop/Ben/CompACT/Assessing psychological fle
> xibility.xlsx", sheet("Sheet 1 - Dataset (2)") firstrow allstring
(60 vars, 299 obs)

. drop Pohlavi Pohlavi_kod Vek

. drop OE4R VA5 OE6R

. drop OE13

. drop OE18R

. drop OE20

. drop S1 A2 D3 A4 D5 S6 A7 S8 A9 D10 S11 S12 D13 S14 A15 D16 D17 S18 A19 A20 D
> 21 AAQ1 AAQ2 AAQ3 AAQ4 AAQ5 AAQ6 AAQ7 SWL1 SWL2 SWL3 SWL4 SWL5

. rename OE2R OE2

. rename VA1 Q1

. rename OE2 Q2

. rename BA3R Q3

. rename VA7 Q4

. rename OE8R Q5

. rename BA9R Q6

. rename VA10 Q7

. rename OE11R Q8

. rename BA12R Q9

. rename VA14 Q10

. rename OE15R Q11

. rename BA16R Q12

. rename VA17 Q13

. rename BA19R Q14

. rename VA21 Q15

. rename OE22 Q16

. rename VA23 Q17

. reshape long Q, i(ID) j (resp)
(j = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17)

Data                               Wide   ->   Long
-----------------------------------------------------------------------------
Number of observations              299   ->   5,083       
Number of variables                  18   ->   3           
j variable (17 values)                    ->   resp
xij variables:
                          Q1 Q2 ... Q17   ->   Q
-----------------------------------------------------------------------------



. destring ID, replace 
ID: all characters numeric; replaced as int

. sort ID

. save "/Users/xichen85/Desktop/Ben/CompACT/CompACT.dta"
file /Users/xichen85/Desktop/Ben/CompACT/CompACT.dta saved

. 
. export delimited using "/Users/xichen85/Desktop/CompACT_Ptacek 2024.csv"
file /Users/xichen85/Desktop/CompACT_Ptacek 2024.csv saved

.

**Comment by KingArthur0205** [comment]
@Monicaxichen Hi Monica, I'm Arthur and am helping Ben with some QC.

Great job! Just flagging a few potential tweaks we could make:
1. Rename "ID" to "id"
2. Rename "Q" to "item"
3. Should the "resp" and "item"(Q) columns be swapped?
4. It seems we might need four separate CSV files, one for each of the following scale.
![截屏2024-10-15 00 05 39](https://github.com/user-attachments/assets/7a936440-4d43-4cc4-b13d-2b37c40ce8f7)
5. I think it's fine to leave the item names as they are, as it provides context on how the items map to the original questionnaire especially since we're deleting a few items. Do you agree with what we can do here?

**Comment by Monicaxichen** [comment]
Hi Arthur, 
Thank you for pointing things out. 
Yes, we can rename the 1 and 2. I can swap the 3-- good catch.  for 4, sure, I can make three other datasets. I was under the impression maybe we only want the items for the purpose of this study (to test the CompACT sclae), but if items from the other three scales are needed, I can certainly work on that. 
Thanks!

**Comment by Monicaxichen** [comment]
and yes to 5. I included a codebook for the item mapping, and that should be helpful.

**Comment by KingArthur0205** [comment]
No problem, glad that I can help : )

**Comment by KingArthur0205** [comment]
> and yes to 5. I included a codebook for the item mapping, and that should be helpful. 

Thanks! This is extremely nice to have when we are working and collaborating internally. 

However, unfortunately we may not be able to upload it to Redivis and provide it for external researchers. So we need to try to make it clear in the datasets if possible. : (

Hope this helps!

**Comment by Monicaxichen** [comment]
Totally make sense to me. Will work on that. Thanks !

**Comment by Monicaxichen** [comment]
[CompACT_Ptacek 2024.csv](https://github.com/user-attachments/files/17380738/CompACT_Ptacek.2024.csv)

**Comment by Monicaxichen** [comment]
import excel "/Users/xichen85/Desktop/Ben/CompACT/Assessing psychological fle
> xibility.xlsx", sheet("Sheet 1 - Dataset (2)") firstrow allstring
(60 vars, 299 obs)

. drop Pohlavi Pohlavi_kod Vek

. drop OE4R VA5 OE6R

. drop OE13

. drop OE18R

. drop OE20

. drop S1 A2 D3 A4 D5 S6 A7 S8 A9 D10 S11 S12 D13 S14 A15 D16 D17 S18 A19 A20 D
> 21 AAQ1 AAQ2 AAQ3 AAQ4 AAQ5 AAQ6 AAQ7 SWL1 SWL2 SWL3 SWL4 SWL5

. rename OE2R OE2

. rename VA1 Q1

. rename OE2 Q2

. rename BA3R Q3

. rename VA7 Q4

. rename OE8R Q5

. rename BA9R Q6

. rename VA10 Q7

. rename OE11R Q8

. rename BA12R Q9

. rename VA14 Q10

. rename OE15R Q11

. rename BA16R Q12

. rename VA17 Q13

. rename BA19R Q14

. rename VA21 Q15

. rename OE22 Q16

. rename VA23 Q17

. reshape long Q, i(ID) j (resp)
(j = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17)
. destring ID, replace 
ID: all characters numeric; replaced as int
. rename ID id
rename Q item
rename resp item 
rename item resp
rename resp resp1
rename item resp
rename resp1 item 
destring item, replace
label define VA23 1 "VA1" 2 "OE2R" 3 "BA3R" 4 "VA7" 5 "OE8R" 6 "BA9R" 7 "VA10" 8 "OE11R" 9 "BA12R" 10 "VA14" 11 "OE15R" 12 "BA16R" 13 "VA17" 14 "BA19R" 15 "VA21" 16 "OE22" 17 "VA23"
label values item VA23

save "/Users/xichen85/Desktop/Ben/CompACT_Ptacek 2024/CompACT_Ptacek 2024..dta", replace
export delimited using "/Users/xichen85/Desktop/CompACT_Ptacek 2024.csv"

**Comment by KingArthur0205** [comment]
Hi @Monicaxichen, This looks great! Let me know when you finish the other 3 and I can take a look

**Comment by Monicaxichen** [comment]
Will do.   :)

**Comment by Monicaxichen** [comment]
[DASS-21.csv](https://github.com/user-attachments/files/17415576/DASS-21.csv)

**Comment by Monicaxichen** [comment]
@KingArthur0205 just uploaded the DASS-21 processed file

**Comment by Monicaxichen** [comment]
[AAQ_II.csv](https://github.com/user-attachments/files/17415787/AAQ_II.csv)

**Comment by Monicaxichen** [comment]
import excel "/Users/xichen85/Desktop/Ben/CompACT_Ptacek 2024/Assessing psychological flexibility.xlsx", sheet("Sheet 1 - Dataset (2)") firstrow case(lower) allstring
drop pohlavi pohlavi_kod vek va1 oe2r ba3r oe4r va5 oe6r va7 oe8r ba9r va10 oe11r ba12r oe13 va14 oe15r ba16r va17 oe18r ba19r oe20 va21 oe22 va23 s1 a2 d3 a4 d5 s6 a7 s8 a9 d10 s11 s12 d13 s14 a15 d16 d17 s18 a19 a20 d21
drop swl1 swl2 swl3 swl4 swl5

reshape long aaq, i(id) j(resp)
rename resp item
rename aaq resp

label define aaq7 1 "aaq1" 2 "aaq2" 3 "aaq3" 4 "aaq4" 5 "aaq5" 6 "aaq6" 7 "aaq7"
label values item aaq7
destring id, replace
sort id
sort id item
save "/Users/xichen85/Desktop/Ben/CompACT_Ptacek 2024/AAQ_II.dta"
export delimited using "/Users/xichen85/Desktop/new.csv"

**Comment by Monicaxichen** [comment]
[SWLS.csv](https://github.com/user-attachments/files/17415961/SWLS.csv)

**Comment by Monicaxichen** [comment]
import excel "/Users/xichen85/Desktop/Ben/CompACT_Ptacek 2024/Assessing psychological flexibility.xlsx", sheet("Sheet 1 - Dataset (2)") firstrow case(lower) allstring
drop pohlavi pohlavi_kod vek va1 oe2r ba3r oe4r va5 oe6r va7 oe8r ba9r va10 oe11r ba12r oe13 va14 oe15r ba16r va17 oe18r ba19r oe20 va21 oe22 va23 s1 a2 d3 a4 d5 s6 a7 s8 a9 d10 s11 s12 d13 s14 a15 d16 d17 s18 a19 a20 d21 aaq1 aaq2 aaq3 aaq4 aaq5 aaq6 aaq7
reshape long swl, i(id) j(resp)
rename resp item
rename swl resp
label define swl5 1 "swl1" 2 "swl2" 3 "swl3" 4 "swl4" 5 "swl5"
label values item swl5
destring id, replace
sort id item
save "/Users/xichen85/Desktop/Ben/CompACT_Ptacek 2024/SWLS.dta"
export delimited using /Users/xichen85/Desktop/new.csv

**Comment by Monicaxichen** [comment]
@KingArthur0205  DASS-21, AAQ_II and SWLS processed files uploaded. I used the scale name to label the file name, but please change file names to the format/type you prefer.

**Comment by KingArthur0205** [comment]
Nice work Monica! Let me take a look and I will get back to u later : )

**Comment by KingArthur0205** [comment]
@Monicaxichen I’ve reviewed these, and they look great! One minor suggestion for future file names: we could use abbreviations of the paper title, the first author’s last name, the year of publication, and the subscales.

For example, SWLS could be named "APFCompact_Ptacek_024_SWLS.csv". I'm changing these and sending them to Ben for this one, so don't worry about them.

@ben-domingue This one is good to be uploaded. ; )

**Comment by KingArthur0205** [comment]
@Monicaxichen Feel free to make a PR about the code. They go under the data directory. If you have some difficulty using Git/GitHub, let me know and I have a few really nice videoes that I can share that may possibly help.

**Comment by Monicaxichen** [comment]
> @Monicaxichen Feel free to make a PR about the code. They go under the data directory. If you have some difficulty using Git/GitHub, let me know and I have a few really nice videoes that I can share that may possibly help.

Sure, would you mind to share the videos.... Happy to learn how to do this.  :)

**Comment by KingArthur0205** [comment]
@Monicaxichen This is a great guide: https://www.youtube.com/watch?v=jRLGobWwA3Y

**Comment by KingArthur0205** [comment]
@Monicaxichen @ben-domingue I'm adding the datasets to the dictionary. Will close this issue once Monica makes a PR for the code

**Comment by KingArthur0205** [comment]
@Monicaxichen Feel free to let me know if there is any challenge in uploading the code. I can also do it on my end if that's easier for you :)

**Comment by Monicaxichen** [comment]
Sure. I will try it on Monday.   Got a few projects came in this week and things got delayed.  Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Monicaxichen** [comment]
@KingArthur0205 Hi Arthur, I watched the video you sent and still have a bit uncertainty here. Maybe for this one, can you do the PR for the code (all codes for the 4 scales are all uploaded in this issue. Thanks. I will try to learn more about Github....

**Comment by KingArthur0205** [comment]
@Monicaxichen Hi Monica, no problem. I understand Git/Github can be quite challenging, and I'm still learning a lot myself.

I will go ahead and let you know when the PR is created. : )

**Comment by Monicaxichen** [comment]
Thanks, Arthur!!!
This is so interesting.  Yeah… I am excited to learn more Github things with you.

Monica

From: Arthur Pan ***@***.***>
Date: Tuesday, October 22, 2024 at 7:40 AM
To: ben-domingue/irw ***@***.***>
Cc: Monica (Xi) Chen ***@***.***>, Mention ***@***.***>
Subject: Re: [ben-domingue/irw] Assessing psychological flexibility: The psychometric properties of the Czech translation of the CompACT questionnaire (Issue #295)

A quick tip for Github, you can actually create a code block with a pair of triple quotes: """. : ) For example:

This is code

**Comment by KingArthur0205** [comment]
@Monicaxichen Hi Monica, I noticed that the code for COMPACT is note updated. Could you please share the code with me so that I can make a PR of the code. 

Cheers

**Comment by KingArthur0205** [comment]
@KingArthur0205 Note to self: Code re COMPACT still needs to be added.

**Comment by Monicaxichen** [comment]
import excel "/Users/xichen85/Desktop/Ben/CompACT/Assessing psychological fle
> xibility.xlsx", sheet("Sheet 1 - Dataset (2)") firstrow allstring
(60 vars, 299 obs)

. drop Pohlavi Pohlavi_kod Vek

. drop OE4R VA5 OE6R

. drop OE13

. drop OE18R

. drop OE20

. drop S1 A2 D3 A4 D5 S6 A7 S8 A9 D10 S11 S12 D13 S14 A15 D16 D17 S18 A19 A20 D
> 21 AAQ1 AAQ2 AAQ3 AAQ4 AAQ5 AAQ6 AAQ7 SWL1 SWL2 SWL3 SWL4 SWL5

. rename OE2R OE2

. rename VA1 Q1

. rename OE2 Q2

. rename BA3R Q3

. rename VA7 Q4

. rename OE8R Q5

. rename BA9R Q6

. rename VA10 Q7

. rename OE11R Q8

. rename BA12R Q9

. rename VA14 Q10

. rename OE15R Q11

. rename BA16R Q12

. rename VA17 Q13

. rename BA19R Q14

. rename VA21 Q15

. rename OE22 Q16

. rename VA23 Q17

. reshape long Q, i(ID) j (resp)
(j = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17)

Data                               Wide   ->   Long
-----------------------------------------------------------------------------
Number of observations              299   ->   5,083       
Number of variables                  18   ->   3           
j variable (17 values)                    ->   resp
xij variables:
                          Q1 Q2 ... Q17   ->   Q
-----------------------------------------------------------------------------



. destring ID, replace 
ID: all characters numeric; replaced as int


. rename ID id
rename Q item
rename resp item 
rename item resp
rename resp resp1
rename item resp
rename resp1 item 
destring item, replace
label define VA23 1 "VA1" 2 "OE2R" 3 "BA3R" 4 "VA7" 5 "OE8R" 6 "BA9R" 7 "VA10" 8 "OE11R" 9 "BA12R" 10 "VA14" 11 "OE15R" 12 "BA16R" 13 "VA17" 14 "BA19R" 15 "VA21" 16 "OE22" 17 "VA23"
label values item VA23

save "/Users/xichen85/Desktop/Ben/CompACT_Ptacek 2024/CompACT_Ptacek 2024..dta", replace
export delimited using "/Users/xichen85/Desktop/CompACT_Ptacek 2024.csv"

**Comment by Monicaxichen** [comment]
@KingArthur0205 here it is. Sorry...

**Comment by KingArthur0205** [comment]
@Monicaxichen Thank you! : ) Now i can add this before I go to bed in case I forget tmr.

**Comment by Monicaxichen** [comment]
[like]  Monica (Xi) Chen reacted to your message:
________________________________
