### ISSUE TITLE
Psychometric Properties of the Connor-Davidson Resilience Scale (CD-RISC) in Spanish Adolescents

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#312]
https://pubmed.ncbi.nlm.nih.gov/38311907/

https://osf.io/f7rp3/

**Comment by KingArthur0205** [comment]
**KIDSCREEN–10(KIDS_df)**: 463 participants rated the 10-item questionnaire on 5-point Likert scale. 

**(The Strength and Difficulties Questionnaire(SDQ_df)**: 463 partcipants, the 25-item scale, on a 3-point Likert scale (0 = not true, 1 = somewhat true, and 2 = certainly true). 

**The Connor-Davison Resilience Scal(CDRISC_df)**:463 partcipants, the 25-item scale assesses resilience on a 5-point Likert scale ranging from 0 (not true at all) to 4 (true all the time).

**The Revised Child Anxiety and Depression Scale−30(RCADS30_df )**: 463 partcipants, 5-item subscales corresponding to 6 factors assessing anxiety and depression symptoms(30 items in total). Items are rated on a 4-point Likert scale ranging from 0 (never) to 3 (always).

**Comment by ben-domingue** [comment]
email sent to author. you can ship PR all the same.
