### ISSUE TITLE
The Inventory of Complicated Grief—A Systematic Psychometric Review and Conceptual Replication Study of the Structural Validity

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#315]
https://journals.sagepub.com/doi/full/10.1177/10731911221100980?casa_token=ASmsszZXA5UAAAAA%3AJD4vM4gs0P2zREqkCeiTFIeF-Gcezfnu0nqETPbS-II7RYcdx0xOefXsJSuBNV0jXPfcztNTuIs

https://osf.io/vmcsg/

**Comment by saviranadela** [comment]
The ICG consists of 19 items (Lumbeck et al., 2012). Individuals describe the currently experienced emotional, cognitive, and behavioral states on a 5-point unipolar frequency scale from “0” (never) to “4” (always).

study 1: 359 participants
study 2: 259 participants

**Comment by saviranadela** [comment]
files: 
[icg_schakowski_2023.zip](https://github.com/user-attachments/files/18136069/icg_schakowski_2023.zip)

code:
```
library(tidyr)
library(dplyr)

dat1 <- read.csv("raw_data_study1.csv", sep = ";", header = TRUE)
dat2 <- read.csv("raw_data_study2.csv", sep = ";", header = TRUE)

dat1 <- dat1 %>%
  rename(id = ID) %>%
  pivot_longer(-id,
               values_to = "resp",
               names_to = "item")

dat2 <- dat2 %>%
  rename(id = ID) %>%
  pivot_longer(-id,
               values_to = "resp",
               names_to = "item")

write.csv(dat1, "icg_schakowski_2023_study1.csv", row.names=FALSE)
write.csv(dat2, "icg_schakowski_2023_study2.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
cc: @ben-domingue @KingArthur0205

**Comment by saviranadela** [comment]
PR: https://github.com/ben-domingue/irw/pull/743

**Comment by ben-domingue** [comment]
I'm emailing the authors for permission. 
@saviranadela it might be worth double-checking whether the data are licensed as some don't have posted licenses and should be "data--need license" rather than "data queue" label [my fault]

**Comment by saviranadela** [comment]
oops forgot to check that! will do next time
