### ISSUE TITLE
Psychometric properties of the Buss–Perry Aggression Questionnaire-short form among law enforcement officers

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#320]
https://osf.io/bskn9/

https://onlinelibrary.wiley.com/doi/full/10.1002/ab.22145?casa_token=QXUD6ZFr1ZcAAAAA%3AnzAjMerEA2wCU5covWgKzZ-9XFKzJaOqsk1dZGN4RcS4JiwEoEbvAyUrJXb-sCKBkze5bDmBpGFGFA

**Comment by KingArthur0205** [comment]
This paper claims to provide post-intervention data for all questionnaires, but only data from the BPAQ-SF is available. Here is how I approached this @ben-domingue  Would you mind confirming if this is a feasible approach?:

The participants were divided into three groups: one uncontrolled group, one that received stress management education, and one that underwent mindfulness resilience training. I added a ```treat``` column to differentiate between the two intervention groups and the no-control group, while retaining the group column to represent their original classification.

Additionally, since data was collected both before and after the treatment, I introduced a wave column to indicate the respective time points of data collection.

**Comment by KingArthur0205** [comment]
Data:
[BPAQ CFA dataset final_RMH.csv](https://github.com/user-attachments/files/17013808/BPAQ.CFA.dataset.final_RMH.csv)
[BPAQ_Christopher_2024_BPAQSF.csv](https://github.com/user-attachments/files/17013810/BPAQ_Christopher_2024_BPAQSF.csv)
[BPAQ_Christopher_2024_FFMQSF.csv](https://github.com/user-attachments/files/17013815/BPAQ_Christopher_2024_FFMQSF.csv)
[BPAQ_Christopher_2024_OBSI.csv](https://github.com/user-attachments/files/17013822/BPAQ_Christopher_2024_OBSI.csv)
[BPAQ_Christopher_2024_PCL5.csv](https://github.com/user-attachments/files/17013823/BPAQ_Christopher_2024_PCL5.csv)
[BPAQ_Christopher_2024_PROMIS.csv](https://github.com/user-attachments/files/17013824/BPAQ_Christopher_2024_PROMIS.csv)
[BPAQ_Christopher_2024_SCSS.csv](https://github.com/user-attachments/files/17013826/BPAQ_Christopher_2024_SCSS.csv)


Code: 
```
# Paper: https://onlinelibrary.wiley.com/doi/full/10.1002/ab.22145?saml_referrer
# Data: https://osf.io/bskn9/
library(dplyr)
library(tidyr)
library(haven)

# Remove participants whose responses are all NAs
remove_na <- function(df) {
  df <- df[!(rowSums(is.na(df[, -which(names(df) == "id")])) == (ncol(df) - 1)), ]
  return(df)
}

df <- read.csv("BPAQ CFA dataset final_RMH.csv")
# ------ Process BPAQSF Dataset ------ 
bpaqsf_df <- df |>
  select(id, starts_with("bpaqsf"), -bpaqsf_aggTotal_b, 
         -bpaqsf_physAgg_b, -bpaqsf_verbAgg_b, -bpaqsf_anger_b,
         -bpaqsf_hostility_b, -bpaqsf_aggTotal_p, -bpaqsf_physAgg_p,
         -bpaqsf_verbAgg_p, -bpaqsf_anger_p, -bpaqsf_hostility_p, group)

bpaqsf_df$treat <- ifelse(bpaqsf_df$group %in% c(2, 3), 1, ifelse(bpaqsf_df$group == 1, 0, NA))
base_bpaqsf_df <- bpaqsf_df |>
  select(id, ends_with("b"), group, treat)
treat_bpaqsf_df <- bpaqsf_df |>
  select(id, ends_with("p"), group, treat)
names(base_bpaqsf_df) <- gsub("_b$", "", names(base_bpaqsf_df))
names(treat_bpaqsf_df) <- gsub("_p$", "", names(treat_bpaqsf_df))

treat_bpaqsf_df <- pivot_longer(treat_bpaqsf_df, cols=-c(id, group, treat), names_to="item", values_to="resp")
base_bpaqsf_df <- pivot_longer(base_bpaqsf_df, cols=-c(id, group, treat), names_to="item", values_to="resp")

treat_bpaqsf_df$wave <- 0
base_bpaqsf_df$wave <- 1
bpaqsf_df <- rbind(treat_bpaqsf_df, base_bpaqsf_df)

save(bpaqsf_df, file="BPAQ_Christopher_2024_BPAQSF.Rdata")
write.csv(bpaqsf_df, "BPAQ_Christopher_2024_BPAQSF.csv", row.names=FALSE)
# ------ Process PROMIS Dataset ------ 
promis_df <- df |>
  select(id, starts_with("promis"), -promis_sleep1r_b, -promis_sleep2r_b, -promis_alcScreen_b)
promis_df<- promis_df[, !grepl("score", names(promis_df), ignore.case = TRUE)]
promis_df <- remove_na(promis_df)
promis_df <- pivot_longer(promis_df, cols=-id, names_to="item", values_to="resp")

save(promis_df, file="BPAQ_Christopher_2024_PROMIS.Rdata")
write.csv(promis_df, "BPAQ_Christopher_2024_PROMIS.csv", row.names=FALSE)
# ------ Process PCL-5 Dataset ------
pcl5_df <- df |>
  select(id, starts_with("pcl"), -pcl5_ptsd_b)
pcl5_df <- remove_na(pcl5_df)
pcl5_df <- pivot_longer(pcl5_df, cols=-id, names_to="item", values_to="resp")

save(pcl5_df, file="BPAQ_Christopher_2024_PCL5.Rdata")
write.csv(pcl5_df, "BPAQ_Christopher_2024_PCL5.csv", row.names=FALSE)
# ------ Process PSS-10 Dataset ------
pss10_df <- df |>
  select(id, starts_with("pss"), -ends_with("r_b"), -pss_stress_b)
pss10_df <- remove_na(pss10_df)
pss10_df <- pivot_longer(pss10_df, cols=-id, names_to="item", values_to="resp")

save(pss10_df, file="BPAQ_Christopher_2024_PCL5.Rdata")
write.csv(pss10_df, "BPAQ_Christopher_2024_PCL5.csv", row.names=FALSE)
# ------ Process OLBI Dataset ------
obi_df <- df |>
  select(id, starts_with("obi"), -ends_with("r_b"), -obi_burnout_b)
obi_df <- remove_na(obi_df)
obi_df <- pivot_longer(obi_df, cols=-id, names_to="item", values_to="resp")

save(obi_df, file="BPAQ_Christopher_2024_OBSI.Rdata")
write.csv(obi_df, "BPAQ_Christopher_2024_OBSI.csv", row.names=FALSE)
# ------ Process SCS-SF Dataset ------
scssf_df <- df |>
  select(id, starts_with("scssf"), -ends_with("r_b"), -scssf_selfComp_b)
scssf_df <- remove_na(scssf_df)
scssf_df <- pivot_longer(scssf_df, cols=-id, names_to="item", values_to="resp")

save(scssf_df, file="BPAQ_Christopher_2024_SCSS.Rdata")
write.csv(scssf_df, "BPAQ_Christopher_2024_SCSS.csv", row.names=FALSE)
# ------ Process FFMQ-F Dataset ------
ffmqsf_df <- df |>
  select(id, starts_with("ffmqsf"), -ends_with("r_b"), -ffmqsf_mindfulness_b)
ffmqsf_df <- remove_na(ffmqsf_df)
ffmqsf_df <- pivot_longer(ffmqsf_df, cols=-id, names_to="item", values_to="resp")

save(ffmqsf_df, file="BPAQ_Christopher_2024_FFMQSF.Rdata")
write.csv(ffmqsf_df, "BPAQ_Christopher_2024_FFMQSF.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
your approach is super sensible. send a pull request?

**Comment by KingArthur0205** [comment]
PR for this issue: https://github.com/ben-domingue/irw/pull/321

**Comment by ben-domingue** [comment]
handling this one now. one note: i think we should start processing only things with a clear license. if you see something without a clear license, note that in a comment to the issue and tag me. i'll take care of the rest!

**Comment by ben-domingue** [comment]
no worries! just trying to keep us from wheel-spinning ;)

hey @KingArthur0205 what is this one? BPAQ CFA dataset final_RMH.csv
the others are clearly some scale or another but this one is more ambiguous

**Comment by KingArthur0205** [comment]
> no worries! just trying to keep us from wheel-spinning ;)
> 
> hey @KingArthur0205 what is this one? BPAQ CFA dataset final_RMH.csv the others are clearly some scale or another but this one is more ambiguous

@ben-domingue That was the original dataset. I accidentally uploaded it the 1st time but deleted it and updated the cell afterwards. This should be the final list of datasets:
<img width="419" alt="截屏2024-09-16 20 04 38" src="https://github.com/user-attachments/assets/d5cab5ea-4047-4669-9bfc-53596431db28">
