### ISSUE TITLE
Psychometric Evaluation of the Swedish Version of the Empathic Experience Scale (EES)

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#325]
https://psycnet.apa.org/fulltext/2025-05941-001.html

https://osf.io/fr7wz/

**Comment by ben-domingue** [comment]
@KingArthur0205 note i am flagging data that need license clarification separately from here on.

**Comment by KingArthur0205** [comment]
> @KingArthur0205 note i am flagging data that need license clarification separately from here on.

Got it, I will also double check for the previous issues and future issues moving forward.

**Comment by ben-domingue** [comment]
yeah you can switch anything with `data queue` to `data---needs license` and i'll start emailing those people (and closing after i've emailed)

**Comment by ben-domingue** [comment]
email sent

**Comment by ben-domingue** [comment]
Andreas Sarling <andreas.sarling@gmail.com> 9-20-2024

**Comment by saviranadela** [comment]
805 final participants
30 items (15 VE + 15 IU)
Responses 1-5

**Comment by saviranadela** [comment]
file: 
[ees_sarling_2024.zip](https://github.com/user-attachments/files/18135948/ees_sarling_2024.zip)

code:
```
library(tidyr)
library(dplyr)

data <- read.table("EES_data.txt", sep = ",", header = TRUE)

data <- data %>%
  rename(id = Response.ID, cov_age = Age, cov_gender = Gender, cov_nationality = Nationality, study = Study) %>%
  select(-age_group) %>%
  pivot_longer(VE1:IU15,
               values_to = "resp",
               names_to = "item")

data_ve <- data %>%
  filter(grepl("VE", item))

data_iu <- data %>%
  filter(grepl("IU", item))

write.csv(data_ve, "ees_sarling_2024_vicarious_experience.csv", row.names=FALSE)
write.csv(data_iu, "ees_sarling_2024_intuitive_understanding.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
PR: https://github.com/ben-domingue/irw/pull/742

**Comment by ben-domingue** [comment]
done! note that i actually decided to merge these two back together. even if discussed separately, i think subscales of an established measure can be lumped together

**Comment by saviranadela** [comment]
ohh TIL! thanks Ben
