### ISSUE TITLE
Moral Disengagement in the Workplace: Validity and Psychometric Properties of the Polish Work Moral Disengagement Scale

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#334]
https://osf.io/rxb5y/ [License: CC-By Attribution 4.0 International ]

https://osf.io/preprints/psyarxiv/rgy4a

**Comment by KingArthur0205** [comment]
Working on this

**Comment by KingArthur0205** [comment]
PR created for this issue: https://github.com/ben-domingue/irw/pull/346
