### ISSUE TITLE
Psychometric properties of the Turkish version of the Aspiration Index and the relationship between aspirations and subjective well-being

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#344]
https://www.inderscienceonline.com/doi/abs/10.1504/IJHD.2023.131527

https://osf.io/psgk8/

**Comment by ben-domingue** [comment]
permission via email

**Comment by KingArthur0205** [comment]
This paper includes a dataset for 2 studies. Both studies use the same set of questions. (35 items on a 7-point scale) 
**Note:** Missing response to an item is replaced with the average of the respondent's other responses to the construct.

1. **Study 1**: 265 participants. 
2. **Study 2** 208 participants.

**Comment by KingArthur0205** [comment]
Data:
[Aspirations_Sonmez_2022.csv](https://github.com/user-attachments/files/17045097/Aspirations_Sonmez_2022.csv)

Code:
```
# Paper: https://www.inderscienceonline.com/doi/abs/10.1504/IJHD.2023.131527
# Data: https://osf.io/psgk8/
library(haven)
library(dplyr)
library(tidyr)

df <- read_sav('Aspirations_CFA.sav')
df <- df |>
  rename(id=ParticipantNo) |>
  select(id, starts_with("Asp"))
df <- pivot_longer(df, cols=-id, values_to = "resp", names_to="item")

save(df, file="Aspirations_Sonmez_2022.Rdata")
write.csv(df, "Aspirations_Sonmez_2022.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
PR for this issue: https://github.com/ben-domingue/irw/pull/369

**Comment by ben-domingue** [comment]
are these .5 values right @KingArthur0205 ? just confirming
```
> table(df$resp)

   1    2 2.75    3    4    5  5.5 5.75    6    7 
1018  702    1 1020 1757 2425    1    2 3168 6461 
```

**Comment by ben-domingue** [comment]
they seem like they may cause problems. even if they are scaled that way originally, i would vote we remove them or round them (and note this in the code).

**Comment by KingArthur0205** [comment]
> they seem like they may cause problems. even if they are scaled that way originally, i would vote we remove them or round them (and note this in the code).
<img width="1309" alt="截屏2024-09-18 15 37 20" src="https://github.com/user-attachments/assets/c097f3da-4e65-4206-9c8c-72fb580afec1">

The authors didn't put any label or instruction to indicate which values are originally missing. I think the best way would be round them to the nearest integer values.

**Comment by ben-domingue** [comment]
ah! i actually vote we cut them. the mean imputation can be done by others if they would like but those are, in my book, not valid responses (which is the hallmark of the thing we want in the IRW.

**Comment by KingArthur0205** [comment]
Code 

> ah! i actually vote we cut them. the mean imputation can be done by others if they would like but those are, in my book, not valid responses (which is the hallmark of the thing we want in the IRW.

Copied, I will go ahead and close the PR as well. Thanks again for clarifying :)

**Comment by ben-domingue** [comment]
i think i already merged the PR so maybe need a new one?

**Comment by KingArthur0205** [comment]
> i think i already merged the PR so maybe need a new one?

I don't think we had any issues as I just closed it. The previous PR was for the other two datasets I worked on today

**Comment by ben-domingue** [comment]
confirming this data needs to be updated, yes? just trying to keep up ;)

**Comment by KingArthur0205** [comment]
> confirming this data needs to be updated, yes? just trying to keep up ;)

Yes, I'm editing the code. :) Will get back once I'm finished

**Comment by ben-domingue** [comment]
perfect @KingArthur0205 thank you. 
i'll assume you'll add code in next PR
