### ISSUE TITLE
Dumas, D., Organisciak, P., & Doherty, M. D. (2020). Measuring divergent thinking originality with human raters and text-mining models: A psychometric comparison of methods. Psychology of Aesthetics, Creativity, and the Arts. https://doi.org/10/ghcsqq

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#345]
https://osf.io/qcmex/

**Comment by KingArthur0205** [comment]
Working on this.
License: CC-By Attribution 4.0 International

**Comment by KingArthur0205** [comment]
This paper measures the thinking originality of human thiking. 92 participants were involved, each presented with 10 items, for which they provided 4 alternative (creative) uses. These responses were subsequently rated by 4 human raters.

Here’s how I plan to approach this. @ben-domingue, would you mind reviewing it and offering your advice? :)
1. ```id```: The ```id``` column should be the original item.(e.g, book, brick, fork)
2. ```item```: The ```item``` column should be the creative response of participants.(e.g., book as weapon, fork as comb)
3. ```rater```: Have a ```rater``` column that reflects which one of the 4 human raters rated this response
4. ```resp```: The ```resp``` should be the score given by one of the 4 human raters on the creative use.
5. ```participant```: Have this extra column to indicate the participant. Or perhaps we can embed this as aprt of ```id```?

**Comment by KingArthur0205** [comment]
Data:
[dumas_Organisciak_2022.csv](https://github.com/user-attachments/files/17026694/dumas_Organisciak_2022.csv)

Code:
```
## Paper: https://osf.io/qcmex/
## Data: https://osf.io/qcmex/
library(dplyr)
library(tidyr)
library(haven)

df <- read.csv("dumas_organisciak_doherty_2020.csv")
df <- df |>
  select(participant, prompt, response, starts_with("rater")) |>
  rename(id=prompt, item=response)
df <- pivot_longer(df, cols=-c(id, participant, item), names_to = "rater", values_to="resp")

save(df, file="dumas_Organisciak_2022.Rdata")
write.csv(df, "dumas_Organisciak_2022.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
@KingArthur0205 love the attention to detail. i would largely do what you did but:
1. switch `participant` to `id` (here we are measuring people)
2. switch the current `id` to the `item` (`item=book` for example)
3. the `rater` is the id of the person yes?

**Comment by KingArthur0205** [comment]
> @KingArthur0205 love the attention to detail. i would largely do what you did but:
> 
> 1. switch `participant` to `id` (here we are measuring people)
> 2. switch the current `id` to the `item` (`item=book` for example)
> 3. the `rater` is the id of the person yes?

1 & 2: Sure. What should we do about the ```item``` in the processed dataset then? This is the response that a participant gave to reflect uses of the tool(book, fork, etc.)?

3: The raters are different from the participants. They give a mark in terms of creativity to the participant-provided uses of the tools.

**Comment by ben-domingue** [comment]
1/2: ah, so you are saying that a person is effectively giving multiple responses to an item? that's ok. somewhat unusual but not unheard of. common with lots of cognitive psychology data (see the `trials` tag in fact)
3: yes so `rater=rater1` or `rater=rater3` or whatever is fine

**Comment by KingArthur0205** [comment]
> 1/2: ah, so you are saying that a person is effectively giving multiple responses to an item? that's ok. somewhat unusual but not unheard of. common with lots of cognitive psychology data (see the `trials` tag in fact) 3: yes so `rater=rater1` or `rater=rater3` or whatever is fine

Thanks for the clarification. I will modify this and we can further discuss tomorrow morning. :)

**Comment by ben-domingue** [comment]
the 1/2 bit is a slight pain point. but i think my solution is fine (code downstream will need to accomodate it)
aside: i'm trying to push more frequent updates to redivis. https://redivis.com/datapages/editor/datasets/as2e-cv7jb41fd

**Comment by ben-domingue** [comment]
note i'm adding a new label. we can remove the `data queue` label when we are done and leave the other (and i'll work on code for this at some point).

**Comment by KingArthur0205** [comment]
I have came up with 2 slightly different approaches for the raters and their ratings:
<img width="459" alt="截屏2024-09-17 13 58 31" src="https://github.com/user-attachments/assets/5e1ffb53-39e2-4766-bd4b-d3e528df1018">
Data:
[dumas_Organisciak_2022.csv](https://github.com/user-attachments/files/17028504/dumas_Organisciak_2022.csv)

Or alternatively:
<img width="359" alt="截屏2024-09-17 13 57 52" src="https://github.com/user-attachments/assets/7cb27d57-01b8-4524-978a-280d3e0fbef0">
Data:
[dumas_Organisciak_2022.csv](https://github.com/user-attachments/files/17028525/dumas_Organisciak_2022.csv)

**Comment by ben-domingue** [comment]
i actually don't think either of these will work. we need `resp` to be something we can analyze. so i would have (where the comments are just for clarity and would obv not be a part of the data):
```
id,item,rater,resp
1,book,1,1 ##this is for read
1,book,1,3 ##this is for paperweight
1,book,1,5 ##this is for weapon
```
so you see we have rows where the first three columns are repeated. that is ok. maybe what we can do is add a `verbatim` column with the 'read, paperweight, weapon` info?

**Comment by KingArthur0205** [comment]
> @KingArthur0205 i actually don't think either of these will work. we need `resp` to be something we can analyze. so i would have (where the comments are just for clarity and would obv not be a part of the data):
> 
> ```
> id,item,rater,resp
> 1,book,1,1 ##this is for read
> 1,book,1,3 ##this is for paperweight
> 1,book,1,5 ##this is for weapon
> ```
> 
> so you see we have rows where the first three columns are repeated. that is ok. maybe what we can do is add a `verbatim` column with the `read, paperweight, weapon` info?

I see. I was confused about how to insert the `read, paperweight, weapon` info, so the new dataset will look something like this.

The new dataset and code will look like this:
[dumas_Organisciak_2022.csv](https://github.com/user-attachments/files/17046769/dumas_Organisciak_2022.csv)

Code:
```
## Paper: https://osf.io/qcmex/
## Data: https://osf.io/qcmex/
library(dplyr)
library(tidyr)
library(haven)

df <- read.csv("dumas_organisciak_doherty_2020.csv")
df <- df |>
  select(participant, prompt, response, starts_with("rater")) |>
  rename(id=participant, item=prompt, verbatim=response)
df_long <- df %>%
  gather(key = "rater", value = "resp", rater1:rater4) %>%
  arrange(id, item)

save(df, file="dumas_Organisciak_2022.Rdata")
write.csv(df, "dumas_Organisciak_2022.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
i like it! shipping it.

**Comment by KingArthur0205** [comment]
PR for this issue: https://github.com/ben-domingue/irw/pull/379
