### ISSUE TITLE
Revised Aesthetic Fluency Scale

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#351]
https://osf.io/d9ujk/

**Comment by ben-domingue** [comment]
paper. https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0281547

> the present work develops and evaluates a Revised Aesthetic Fluency Scale using item response theory to broaden its scope (36 items) and refine its response scale. In a large sample (n = 2,089 English-speaking adults), Study 1 found strong evidence for unidimensionality, good item fit, and a difficulty level suitable for its targeted population; Study 2 (n = 392) provided initial evidence for score validity via relationships with art engagement, Openness to Experience, and aesthetic responsiveness; and Study 3 derived a brief, 10-item form for time-constrained projects. Taken together, the revised scales build upon lessons learned from the original and appear promising for the next generation of research.

**Comment by ben-domingue** [comment]
my sense is that we should be able to just use this data: af_study3_osf.csv
which combines item responses from studies 1 & 2. we'll just want the 36 items (but gender and group can be person-level covariates).

**Comment by ben-domingue** [comment]
https://github.com/ben-domingue/irw/blob/main/data/Aesthetic%20Fluency%20scale.do

**Comment by Monicaxichen** [comment]
[aestheticfluency_cotter2023.csv](https://github.com/user-attachments/files/17314957/aestheticfluency_cotter2023.csv)
