### ISSUE TITLE
A short measure of childbearing motivations (CBQ-SF): development and psychometric evaluation in Polish samples of adults and adolescents.

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#357]
License: CC0 1.0 Universal 
https://osf.io/f73jq/

https://link.springer.com/article/10.1007/s10826-022-02497-6

**Comment by KingArthur0205** [comment]
Working on this

**Comment by ben-domingue** [comment]
@KingArthur0205 just flagging the above

**Comment by KingArthur0205** [comment]
Assigned to myself :) @ben-domingue

**Comment by ben-domingue** [comment]
@KingArthur0205 sorry! i just did this and only when closing it out noted you had assigned to yourself! apologies.
