### ISSUE TITLE
LSHS-E comparison between online and paper application

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#366]
License: CC-By Attribution 4.0 International 
https://osf.io/4jb6k/

https://link.springer.com/article/10.1007/s12144-021-02497-7

**Comment by KingArthur0205** [comment]
Working on this

**Comment by KingArthur0205** [comment]
@ben-domingue Hi Ben, I have a quick question regarding the datasets. I’ve noticed that some datasets use a 0-starting Likert scale, while others use a 1-starting scale. Should we standardize the scale to one format, or is this considered trivial and not a concern?

**Comment by KingArthur0205** [comment]
> @KingArthur0205 we have thus far been flexible on this. from my perspective, this kind of flexibility isn't a real problem as the levels themselves are purely ordinal (we could equally well call them a/b/c/d...) and most software is flexible [and, if not, you'd have to convert anyways]. i'm guessing i'd rather do less coercing of the response than is needed given that it isn't likely to cause issues downstream.
> 
> what do you think?

Sure, I also considered this to be minor, but I just wanted to double-check Thanks for clarifying! :)

**Comment by ben-domingue** [comment]
a great question, keep 'em coming :)

**Comment by KingArthur0205** [comment]
Data:
[LSHS-E_Quidaja_2022.csv](https://github.com/user-attachments/files/17043530/LSHS-E_Quidaja_2022.csv)

Code:
```
# Paper: https://link.springer.com/article/10.1007/s12144-021-02497-7#Sec2
# Data: https://osf.io/4jb6k/
library(readxl)
library(dplyr)
library(tidyr)
library(haven)

df <- read_excel("lshse_complete_database.xlsx")
df <- df |>
  select(id, starts_with("alu"))
df <- pivot_longer(df, cols=-id, names_to = "item", values_to = "resp")

save(df, file="LSHS-E_Quidaja_2022.Rdata")
write.csv(df, "LSHS-E_Quidaja_2022.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
PR for this issue: https://github.com/ben-domingue/irw/pull/368
