### ISSUE TITLE
A Psychometric Network Analysis Approach for Detecting Item Wording Effects in Self-Report Measures Across Subgroups

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#372]
https://osf.io/xgqdp/

License: GNU General Public License (GPL) 3.0

**Comment by KingArthur0205** [comment]
@ben-domingue Could be a great starting point for Savira

**Comment by saviranadela** [comment]
working on this today!

**Comment by ben-domingue** [comment]
@saviranadela excellent! and i just 'assigned' this to you mainly out of curiosity if your name would show up ;)

**Comment by saviranadela** [comment]
Data: 
[PNA_Bulut_2024.csv](https://github.com/user-attachments/files/17101239/PNA_Bulut_2024.csv)

Code:
`import pandas as pd

df = pd.read_csv('rse_dataset.csv')
df.columns = df.columns.str.replace('person', 'id')
df_melted = pd.melt(df, id_vars=['id'],
                    value_vars=['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10'],
                    var_name='item',
                    value_name='resp')
df_melted.to_csv('PNA_Bulut_2024.csv', index=False)`

**Comment by ben-domingue** [comment]
paper. https://journals.sagepub.com/doi/full/10.1177/1525822X241247444

@saviranadela the data looks good! i'm now somewhat confused as to where it comes from. they don't really say much about it other than that it is rosenberg self-esteem data taken from a range of ages. i'm almost inclined to email authors asking for clarity unless you or @KingArthur0205 can see something i don't.

**Comment by KingArthur0205** [comment]
@ben-domingue I found this in their repo: 
"In this illustrative example, we analyze a sample dataset from the Rosenberg Self-Esteem (RSE) Scale to identify item wording effects. This data set was obtained via online with an interactive version of the RSE Scale ([Rosenberg, 1965](https://www.jstor.org/stable/j.ctt183pjjh)). The current dataset consists of a random sample of 1000 respondents. The original dataset is available at http://openpsychometrics.org/_rawdata/RSE.zip.

The following items were rated on a 4-point scale where 0=strongly disagree, 1=disagree, 2=agree, and 3=strongly agree:

1. I feel that I am a person of worth, at least on an equal plane with others. (P)
2. I feel that I have a number of good qualities. (P)
3. All in all, I am inclined to feel that I am a failure. (N)
4. I am able to do things as well as most other people. (P)
5. I feel I do not have much to be proud of. (N)
6. I take a positive attitude toward myself. (P)
7. On the whole, I am satisfied with myself. (P)
8. I wish I could have more respect for myself. (N)
9. I certainly feel useless at times. (N)
10. At times, I think I am no good at all. (N)
11. 
where (P) indicates a positively-worded item and (N) indicates a negatively-worded item."

**source:** How the user came to the web page of the RSE scale.
1=front page of personality test website
2=Google search
3=other

**Comment by ben-domingue** [comment]
great find. 
porting to slack
