### ISSUE TITLE
Developing a new vocabulary test

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#38]
https://osf.io/ef3s4/
paper. https://link.springer.com/article/10.3758/s13428-022-01856-x#data-availability

**Comment by anniehang** [comment]
I am working on this

**Comment by anniehang** [comment]
[Tests of vocabulary_study3.csv](https://github.com/ben-domingue/irw/files/15178207/Tests.of.vocabulary_study3.csv)
[Tests of vocabulary_study2.csv](https://github.com/ben-domingue/irw/files/15178212/Tests.of.vocabulary_study2.csv)
[Tests of vocabulary_study4.csv](https://github.com/ben-domingue/irw/files/15178214/Tests.of.vocabulary_study4.csv)
[Tests of vocabulary_study5.csv](https://github.com/ben-domingue/irw/files/15178217/Tests.of.vocabulary_study5.csv)
[Tests of vocabulary_study1.csv](https://github.com/ben-domingue/irw/files/15178218/Tests.of.vocabulary_study1.csv)

**Comment by ben-domingue** [comment]
apologies for delay on this @anniehang ! i've been swamped but will work on this soon :)

**Comment by anniehang** [comment]
No problem, take your time!

**Comment by ben-domingue** [comment]
note to self. https://domingue-lab.slack.com/archives/C05AKJGU3UJ/p1715025447273929

**Comment by anniehang** [comment]
i can't open this website

**Comment by ben-domingue** [comment]
oh, yes, sorry. it was a note for myself related to this one. don't worry about it!

**Comment by ben-domingue** [comment]
i've been thinking about this and have updated my thinking based on this case! see commandment 5:
https://github.com/ben-domingue/irw
what i think we want here is *just* the stuff from study 5 but split into one dataset separately for each measure. i can process the data you posted above if you like; if it'd be easy for you to update what you had that would be great too. sorry for the change; i'm still learning about what i want here i guess! [and i also asked some others what they thought would be better.]

**Comment by ben-domingue** [comment]
@anniehang see ^above

**Comment by anniehang** [comment]
ok, i can try to update it :)

**Comment by anniehang** [comment]
[Tests of vocabulary_TSQ.csv](https://github.com/ben-domingue/irw/files/15321639/Tests.of.vocabulary_TSQ.csv)
[Tests of vocabulary_Vocabulary.csv](https://github.com/ben-domingue/irw/files/15321641/Tests.of.vocabulary_Vocabulary.csv)
[Tests of vocabulary_AFOQT.csv](https://github.com/ben-domingue/irw/files/15321642/Tests.of.vocabulary_AFOQT.csv)
[Tests of vocabulary_ART.csv](https://github.com/ben-domingue/irw/files/15321643/Tests.of.vocabulary_ART.csv)
[Tests of vocabulary_BFI.csv](https://github.com/ben-domingue/irw/files/15321644/Tests.of.vocabulary_BFI.csv)
[Tests of vocabulary_GK.csv](https://github.com/ben-domingue/irw/files/15321646/Tests.of.vocabulary_GK.csv)
[Tests of vocabulary_IceageQ.csv](https://github.com/ben-domingue/irw/files/15321647/Tests.of.vocabulary_IceageQ.csv)
[Tests of vocabulary_ND.csv](https://github.com/ben-domingue/irw/files/15321648/Tests.of.vocabulary_ND.csv)
[Tests of vocabulary_RF.csv](https://github.com/ben-domingue/irw/files/15321649/Tests.of.vocabulary_RF.csv)
[Tests of vocabulary_T.csv](https://github.com/ben-domingue/irw/files/15321650/Tests.of.vocabulary_T.csv)

**Comment by anniehang** [comment]
I would like to know if there are any issues with this processing? :)

**Comment by ben-domingue** [comment]
@anniehang i think i replied to your email but, again, huge apologies for dropping the ball on this. do you still have code around for this one?

**Comment by ben-domingue** [comment]
@anniehang i suspect it is here. is this right? 
https://github.com/ben-domingue/irw/pull/98

**Comment by anniehang** [comment]
Yes, that's right

**Comment by ben-domingue** [comment]
@anniehang again, huge apologies for my falling down on this one! thank you!

**Comment by anniehang** [comment]
No problem at all! I completely understand.
Unfortunately, I need to let you know that I’ll need some time before I can work on this, as I’ve been busy lately.
Thank you for your understanding!
