### ISSUE TITLE
Psychometric Properties of the Portuguese Adolescent Students’ Basic Psychological Needs at School Scale (ASBPNSS) and evidence of differential associations with indicators of subjective wellbeing

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#391]
https://osf.io/khvs9/

https://journals.sagepub.com/doi/full/10.1177/07342829221125843

**Comment by KingArthur0205** [comment]
**NPBE_df**: 1648 particpants, 15 items,  5-point Likert scale ranging from 1 (Totally Disagree) to 3 (Neither Agree nor Disagree) to 5 (Totally Agree)

**EBSV_df**: 1648 particpants, 6 items, scale is 1,2,4,5,6,7. (The items in this scale measure students’ satisfaction with six distinct domains of life: family, friends, school experience, self, environment, and life in general. Responses are given on a 7-point Likert scale from 0 (Terrible) to 6 (Fantastic).) 

**PANAS_df**: 1648 particpants, 20 items, 5-point Likert-type scale from 1 (Very slightly or not at all) to 5 (Extremely).

**Comment by KingArthur0205** [comment]
Data:
[PPPASBPNSSedaisw_Pedro_2022_CSV.zip](https://github.com/user-attachments/files/17319515/PPPASBPNSSedaisw_Pedro_2022_CSV.zip)

Code:
```
# Paper:https://osf.io/khvs9/
# Data: https://journals.sagepub.com/doi/full/10.1177/07342829221125843

library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)
library(readr)
library(readxl)

remove_na <- function(df) {
  df <- df[!(rowSums(is.na(df[, -which(names(df) %in% c("id", "date"))])) == (ncol(df) - 2)), ]
  return(df)
}

data_df <- read_csv("OSF BPNS.csv")
data_df <- data_df %>%
  rename(id = ...1 )

# ------ Process NPBE ------
NPBE_df  <- data_df |>
  select(starts_with("M2_NPBE"), id)

NPBE_df   <- remove_na(NPBE_df )
NPBE_df   <- pivot_longer(NPBE_df  , cols=-c(id), names_to="item", values_to="resp")

save(NPBE_df, file="PPPASBPNSSedaisw_Pedro_2022_NPBE.Rdata")
write.csv(NPBE_df, "PPPASBPNSSedaisw_Pedro_2022_NPBE.csv", row.names=FALSE)

# ------ Process EBSV ------
EBSV_df  <- data_df |>
  select(starts_with("M2_EBSV"), id)

EBSV_df  <- remove_na(EBSV_df )
EBSV_df   <- pivot_longer(EBSV_df  , cols=-c(id), names_to="item", values_to="resp")

save(EBSV_df, file="PPPASBPNSSedaisw_Pedro_2022_EBSV.Rdata")
write.csv(EBSV_df, "PPPASBPNSSedaisw_Pedro_2022_EBSV.csv", row.names=FALSE)

# ------ Process PANAS ------
PANAS_df  <- data_df |>
  select(starts_with("M2_PANAS"), id)

PANAS_df  <- remove_na(PANAS_df )
PANAS_df   <- pivot_longer(PANAS_df  , cols=-c(id), names_to="item", values_to="resp")

save(PANAS_df, file="PPPASBPNSSedaisw_Pedro_2022_PANAS.Rdata")
write.csv(PANAS_df, "PPPASBPNSSedaisw_Pedro_2022_PANAS.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
> There is no "3" in respnoses of this dataset.

very odd!

**Comment by ben-domingue** [comment]
ship PR?

**Comment by ben-domingue** [comment]
and @KingArthur0205 the way you are documenting things above is making it *so easy* on my end. thank you!

**Comment by KingArthur0205** [comment]
:) I will make sure to include both the full names and abbreviations that are used in the final datasets so that they can be mapped.
