### ISSUE TITLE
A large-scale evaluation of Chinese youth purpose and its associations with mental health

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#399]
License: CC-By Attribution 4.0 International 
https://osf.io/jqzbx/
[no paper]

**Comment by ben-domingue** [comment]
data looks good @KingArthur0205. ship PR and finish documentation (which it looks like you are working on)?

**Comment by KingArthur0205** [comment]
@ben-domingue PR for issue: https://github.com/ben-domingue/irw/pull/711
Data entries are added into dictioanry : )
