### ISSUE TITLE
Psychometric properties of the Scientific Reasoning Scale: application to the Italian context.

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#400]
https://osf.io/jk9dp/
License: CC-By Attribution 4.0 International

**Comment by KingArthur0205** [comment]
Poster: https://www.researchgate.net/profile/Rossella-Caliciuri/publication/382182050_Psychometric_Properties_of_the_Scientific_Reasoning_Scale/links/6690f2a1b15ba55907539c5a/Psychometric-Properties-of-the-Scientific-Reasoning-Scale.pdf

**Comment by KingArthur0205** [comment]
**Scientific Reasoning Scale(SRS)**: 337 italian participants. 11 items on a TRUE/FALSE scale.

**Comment by KingArthur0205** [comment]
Data:
[PPSRS_Caliciuri_2024.csv](https://github.com/user-attachments/files/17910095/PPSRS_Caliciuri_2024.csv)


Code:
```
# Poster: https://www.researchgate.net/profile/Rossella-Caliciuri/publication/382182050_Psychometric_Properties_of_the_Scientific_Reasoning_Scale/links/6690f2a1b15ba55907539c5a/Psychometric-Properties-of-the-Scientific-Reasoning-Scale.pdf 
# Data: https://osf.io/jk9dp/
library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)

df <- read_sav("3. CFA&IRT_SRS (n=337).sav")
df <- df |>
  select(ID, starts_with("SRS")) |>
  rename(id=ID)
df <- pivot_longer(df, cols=-id, names_to = "item", values_to="resp")

save(df, file="PPSRS_Caliciuri_2024.Rdata")
write.csv(df, "PPSRS_Caliciuri_2024.csv", row.names=FALSE)

```
