### ISSUE TITLE
Do you know the Wooly Bully? Testing era-based knowledge to verify participant age online

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#41]
https://osf.io/bn4xy/?view_only=7252e963f3bd4c0c981eed6ddd085ee8
paper. https://link.springer.com/article/10.3758/s13428-022-01944-y#Sec34

**Comment by ben-domingue** [comment]
@anniehang is working on this

**Comment by anniehang** [comment]
I think representing the subject's choice for each item with numerical values is not meaningful in practice. Should I still use the numerical values as the response, or should I use correct(1) or incorrect(0) as the response?

**Comment by ben-domingue** [comment]
corerct/incorrect would be great!

**Comment by anniehang** [comment]
ok!

**Comment by anniehang** [comment]
[vertifyage_study1a.csv](https://github.com/ben-domingue/irw/files/14852256/vertifyage_study1a.csv)
[vertifyage_study1b.csv](https://github.com/ben-domingue/irw/files/14852258/vertifyage_study1b.csv)
[vertifyage_study2.csv](https://github.com/ben-domingue/irw/files/14852259/vertifyage_study2.csv)
[vertifyage_study3a.csv](https://github.com/ben-domingue/irw/files/14852260/vertifyage_study3a.csv)
[vertifyage_study3b.csv](https://github.com/ben-domingue/irw/files/14852263/vertifyage_study3b.csv)
[vertifyage_study3c.csv](https://github.com/ben-domingue/irw/files/14852265/vertifyage_study3c.csv)

**Comment by ben-domingue** [comment]
also we should make 'i dont know' NA if we haven't already

**Comment by anniehang** [comment]
Ok, I think that's a good idea.
The number of participants reported in the paper reflects the count after missing values were removed. so I directly eliminated participants with missing data from the analysis.

**Comment by ben-domingue** [comment]
do you want to put together an updated dataset and i can take a look at it? 
and, just to confirm, the 'don't know' responses were already reported as NA values?

**Comment by anniehang** [comment]
ok, i got it!

**Comment by anniehang** [comment]
[vertifyage_study1a1b3b3c.csv](https://github.com/ben-domingue/irw/files/14919241/vertifyage_study1a1b3b3c.csv)
[vertifyage_study2.csv](https://github.com/ben-domingue/irw/files/14919245/vertifyage_study2.csv)
[vertifyage_study3a.csv](https://github.com/ben-domingue/irw/files/14919247/vertifyage_study3a.csv)

**Comment by ben-domingue** [comment]
one question about 1a1b3b3c: there are only 18 items but it looks (from the text) like there should be 19. did one get dropped for some reason?

**Comment by anniehang** [comment]
Oh, I made a mistake; there are 19 items in 1a. I think I should merge 1a and 2 together. However, what confuses me is that the data for 1b, 3b, and 3c only provide 18 items.

**Comment by ben-domingue** [comment]
hm. very strange. if you think that something may be wrong in their data (such that it doesn't map onto what they say), i can email them? i'm sure they'd be happy to know that there is a problem if we are confused.

**Comment by anniehang** [comment]
ok, I can send them an email to inquire about it.

**Comment by anniehang** [comment]
If it's not too much trouble, I would be happy if you could email them. 😃

**Comment by ben-domingue** [comment]
happy to :)

**Comment by ben-domingue** [comment]
second email sent july 2. @ben-domingue

**Comment by ben-domingue** [comment]
They finally got back to me:
`Thanks for reaching out and for your interest in our paper! I’m actually seeing 19 in some and 20 in others, with the 20th extra item being “Tik Tok,” which didn’t make it into our final list of 19 (it was in the original development of the items, which you can see in the supplemental materials). I can’t say why it was dropped in some of the studies since data collection was a long time ago (and I wasn’t involved yet). If you decide to include the items in the IRW, you should include the 19 that are listed in Table S1.`
What I would propose is that we just subset to that final list of 19 if that is easy?

**Comment by ben-domingue** [comment]
@anniehang see above

**Comment by ben-domingue** [comment]
thanks annie. you are the best :)

**Comment by anniehang** [comment]
Apologies! I realized my previous mistake. Some sub-datasets did not provide answers for Q8, while others had increased answers for the 'TikTok' column, so I mixed them up. 
By reviewing the participants' original answers to Q8, I can infer whether their responses were correct. Now each sub-experiment has 19 items.

**Comment by anniehang** [comment]
[AVI-S.csv](https://github.com/user-attachments/files/16116639/AVI-S.csv)

**Comment by ben-domingue** [comment]
great!!
