### ISSUE TITLE
Data for for ”Factors explaining students’ attitudes towards learning in genetics and belief in genetic determinism”

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#414]
https://osf.io/preprints/edarxiv/d5hzg

data. https://figshare.com/articles/dataset/Data_for_for_Factors_explaining_students_attitudes_towards_learning_in_genetics_and_belief_in_genetic_determinism_/12356336

[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)CC BY 4.0

**Comment by Monicaxichen** [comment]
[Gene scale_Aivelo 2020.csv](https://github.com/user-attachments/files/17779323/Gene.scale_Aivelo.2020.csv)

**Comment by Monicaxichen** [comment]
import delimited "/Users/xichen85/Downloads/12356336/gene_likert_aivelo2020.csv", clear 
drop school date course_bi1 course_bi2 course_bi3 course_bi4 course_bi5 course_oth course_tot gender age teacher_app textbook
drop v40
rename form id
foreach i of numlist 1/25 {
    rename X`i' Q`i'
foreach i of numlist 1/25 {
    rename x`i' Q`i'
}
reshape long Q, i(id) j(resp)
rename resp item
rename Q resp
save "/Users/xichen85/Desktop/Gene scale_Aivelo 2020.dta"
export delimited using /Users/xichen85/Desktop/Untitled.csv

**Comment by KingArthur0205** [comment]
@Monicaxichen @ben-domingue 
I think this is good. 421 students answered 25 questions on a 5-point Likert scale, which aligns with the preprint.

**Comment by KingArthur0205** [comment]
Used scales:
5 sub-scales each with 5 items: Self-concept in genetics, Liking genetics, Experiening utility of genetics, Attitude towards gene technology, Genetic determinism

1. **Shortened Sherman Mathematics Attitude Scale (FSMAS)**: From which the author derived Self-concept in genetics, Liking genetics, Experiening utility of genetics
2. **Shortened Biohead-Citizen questionnaire**: From which the author derived Attitude towards gene technology and Genetic determinism

**Comment by KingArthur0205** [comment]
@Monicaxichen Hi Monica, this is great overall. One small tweak that we can make in the future is to try to save the file using a relative file-name and avoid having your absolute path like ```/Users/xichen85/Downloads/12356336/gene_likert_aivelo2020.csv```. See the below modifed code for an example. Nothing wrong with it but it just may cause the code to give errors in the case where other researchers want to reproduce the results.



```
import delimited "gene_likert_aivelo2020.csv", clear 
drop school date course_bi1 course_bi2 course_bi3 course_bi4 course_bi5 course_oth course_tot gender age teacher_app textbook
drop v40
rename form id
foreach i of numlist 1/25 {
    rename X`i' Q`i'
foreach i of numlist 1/25 {
    rename x`i' Q`i'
}
reshape long Q, i(id) j(resp)
rename resp item
rename Q resp
save "Gene_scale_Aivelo_2020.do.dta"
export delimited using Gene_scale_Aivelo_2020.csv
```

**Comment by KingArthur0205** [comment]
@ben-domingue Added to the data dictionary. PR created at https://github.com/ben-domingue/irw/pull/696

**Comment by Monicaxichen** [comment]
> @Monicaxichen Hi Monica, this is great overall. One small tweak that we can make in the future is to try to save the file using a relative file-name and avoid having your absolute path like `/Users/xichen85/Downloads/12356336/gene_likert_aivelo2020.csv`. See the below modifed code for an example. Nothing wrong with it but it just may cause the code to give errors in the case where other researchers want to reproduce the results.
> 
> ```
> import delimited "gene_likert_aivelo2020.csv", clear 
> drop school date course_bi1 course_bi2 course_bi3 course_bi4 course_bi5 course_oth course_tot gender age teacher_app textbook
> drop v40
> rename form id
> foreach i of numlist 1/25 {
>     rename X`i' Q`i'
> foreach i of numlist 1/25 {
>     rename x`i' Q`i'
> }
> reshape long Q, i(id) j(resp)
> rename resp item
> rename Q resp
> save "Gene_scale_Aivelo_2020.do.dta"
> export delimited using Gene_scale_Aivelo_2020.csv
> ```

totally makes sense. Will keep in mind :)
