### ISSUE TITLE
Assessing the validity and reliability of Female Genital Self-Image Scale in a UK population of healthy women over twenty

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#419]
https://osf.io/7mgxk/

License: CC-By Attribution 4.0 International

**Comment by saviranadela** [comment]
hi @ben-domingue I have a question. if the responses look like this, should we encode them (e.g., 1 for Strongly Disagree to 4 for Strongly agree) or leave it as it is?
<img width="840" alt="image" src="https://github.com/user-attachments/assets/fd942e0a-4936-4880-9698-73f7d4d81705">

**Comment by ben-domingue** [comment]
@saviranadela great question. recode them as numbers; just make sure that the numbers are increasing as the responses:
```
1=strongly disagree
2=disagree
3=neutral
4=agree
5=strongly agree
```
kind of obvious but just wanted to flag this as critical. if they do'nt have `neutral` it's fine to just make agree=3 and strongly agree=4 and even having the whole thing reversed such that 1=strongly agree is fine. we just need the order of the numbers to be sensible.

**Comment by KingArthur0205** [comment]
@saviranadela Hi Savira, sharing some code that I used yesterday to process a similar case:
```
likert_map <- c(
  "Strongly Disagree" = 1,
  "Disagree" = 2,
  "Agree" = 3,
  "Strongly Agree" = 4
)

mgsis_df <- pivot_longer(mgsis_df, cols=-id, names_to="item", values_to="resp")
mgsis_df$resp <- likert_map[mgsis_df$resp]
```

**Comment by saviranadela** [comment]
hi Arthur, thank you for that!

**Comment by saviranadela** [comment]
data: 
[FGSIS_Berzeviczy_2018.csv](https://github.com/user-attachments/files/17967502/FGSIS_Berzeviczy_2018.csv)

code:
```
library(readxl)
library(tidyr)
library(dplyr)

df <- read_xlsx("FGSIS Data.xlsx")

df <- df[-c(1, 2), c(1, 13:ncol(df))]

df <- df %>%
  rename(id = UserID)

fgsis <- pivot_longer(df, cols=-id, names_to="item", values_to="resp")

likert_map <- c(
  "Strongly disagree" = 1,
  "Disagree" = 2,
  "Agree" = 3,
  "Strongly agree" = 4,
  "Yes" = 1,
  "No" = 0
)

fgsis$resp <- likert_map[fgsis$resp]

fgsis <- fgsis %>%
  filter(!is.na(resp))

write.csv(df, "FGSIS_Berzeviczy_2018.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
i mapped the likert scale like Arthur did, and also mapped yes/no to 1/0 as well. please let me know if i'm on the right track!

also, should we start to include covariates?

**Comment by ben-domingue** [comment]
@saviranadela apologies. just seeing this. are there still live questions here?

**Comment by saviranadela** [comment]
all good. let me know if you have any feedback!

**Comment by saviranadela** [comment]
PR: https://github.com/ben-domingue/irw/pull/725

**Comment by saviranadela** [comment]
oh not me being careless again :(

this is the right csv 
[FGSIS_Berzeviczy_2018.csv](https://github.com/user-attachments/files/18120134/FGSIS_Berzeviczy_2018.csv)

checked the code as well.

let me know if you have any feedback. and apologize!

**Comment by ben-domingue** [comment]
looks good!

**Comment by saviranadela** [comment]
[fgsis_berzeviczy_2018.csv](https://github.com/user-attachments/files/18199636/fgsis_berzeviczy_2018.csv)

also updated the table name in the PR

**Comment by ben-domingue** [comment]
i had posted this one here i think:
https://redivis.com/datapages/editor/datasets/as2e-cv7jb41fd/tables/58zw-58bcbvtj4?tablesList-search=berz&tablesList-orderDirection=DESC&tablesList-orderBy=relevance&tablesList-tableToken=tablesList

do we need to update? just want to make sure i'm following. i think it is fine that we have it with the caps name. there are plenty like that [my fault!]. i just want to default to lowercase in future
