### ISSUE TITLE
Self-Report Measures of Procrastination Exhibit Inconsistent Concurrent Validity, Predictive Validity, and Psychometric Properties

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#428]
https://osf.io/r7wcx/

**Comment by ben-domingue** [comment]
https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2022.784471/full

**Comment by ben-domingue** [comment]
email permission

**Comment by Nadiayen** [comment]
Processed Data:
[MBPS_Vangsness_2019.csv](https://github.com/user-attachments/files/17794870/MBPS_Vangsness_2019.csv)

Here’s a quick update on the data processing: I’ve selected 122 columns from the original dataset of 187 columns. However, I’m not entirely sure if my selection covers all the necessary columns, so please let me know if any adjustments are needed.

The selected 122 Columns:
MBPS_1 ~ MBPS_14
AFPS_1 ~ AFPS_9
GPS_1 ~ GPS_16
AIP_1 ~ AIP_11
APS_1 ~ APS_16
UPS_1 ~ UPS_7
PASS_1 ~ PASS_12
IPS_1 ~ IPS_9
PPS_1 ~ PPS_12
TPI_1 ~ TPI_16

Python code:
```
## Import data
df1 = pd.read_csv('fullData.csv')

## Select 122 columns to keep
columns_to_keep = [
    "MBPS_1", "MBPS_2", "MBPS_3", "MBPS_4", "MBPS_5", "MBPS_6", "MBPS_7", "MBPS_8", "MBPS_9", "MBPS_10", 
    "MBSP_11", "MBPS_12", "MBPS_13", "MBPS_14", 
    "AFPS_1", "AFPS_2", "AFPS_3", "AFPS_4", "AFPS_5", "AFPS_6", "AFPS_7", "AFPS_8", "AFPS_9", 
    "GPS_1", "GPS_2", "GPS_3", "GPS_4", "GPS_5", "GPS_6", "GPS_7", "GPS_8", "GPS_9", "GPS_10", 
    "GPS_11", "GPS_12", "GPS_13", "GPS_14", "GPS_15", "GPS_16", 
    "AIP_1", "AIP_2", "AIP_3", "AIP_4", "AIP_5", "AIP_6", "AIP_7", "AIP_8", "AIP_9", "AIP_10", "AIP_11", 
    "APS_1", "APS_2", "APS_3", "APS_4", "APS_5", "APS_6", "APS_7", "APS_8", "APS_9", "APS_10", 
    "APS_11", "APS_12", "APS_13", "APS_14", "APS_15", "APS_16", 
    "UPS_1", "UPS_2", "UPS_3", "UPS_4", "UPS_5", "UPS_6", "UPS_7", 
    "PASS_1", "PASS_2", "PASS_3", "PASS_4", "PASS_5", "PASS_6", "PASS_7", "PASS_8", "PASS_9", "PASS_10", 
    "PASS_11", "PASS_12", 
    "IPS_1", "IPS_2", "IPS_3", "IPS_4", "IPS_5", "IPS_6", "IPS_7", "IPS_8", "IPS_9", 
    "PPS_1", "PPS_2", "PPS_3", "PPS_4", "PPS_5", "PPS_6", "PPS_7", "PPS_8", "PPS_9", "PPS_10", 
    "PPS_11", "PPS_12", 
    "TPI_1", "TPI_2", "TPI_3", "TPI_4", "TPI_5", "TPI_6", "TPI_7", "TPI_8", "TPI_9", "TPI_10", 
    "TPI_11", "TPI_12", "TPI_13", "TPI_14", "TPI_15", "TPI_16"
]

df1_filtered = df1[columns_to_keep]
df1_filtered.shape      ## 242 rows × 122 columns
df2 = df1_filtered.copy()

## Check null values
null_counts = df2.isnull().sum()
null_counts

## Remove null values
df2_cleaned = df2.dropna()
df2_cleaned.shape      ## 217 rows × 122 columns

## Check data type
df2_cleaned.dtypes

##Start Convert Vector Here
new_data = []

for index, row in df2_cleaned.iterrows():
    for column in df2_cleaned.columns:
        new_data.append([index + 1, column, row[column]])  

output = pd.DataFrame(new_data, columns=['id', 'item', 'resp'])

## Save the result as csv file
output.to_csv('MBPS_Vangsness_2019.csv', index=False)
```

Please let me know if you notice any issues with my data cleaning process. Thank you!

**Comment by KingArthur0205** [comment]
Hi Nadia! Here's a quick Python tip: you can use ```df.filter(like="AIP", axis=1)``` to easily select columns that contain the substring "AIP". This should save you a lot of effort compared to manual selection while achieving the same result. Thanks for all your hard work, and I hope this helps! 😊

**Comment by KingArthur0205** [comment]
@Nadiayen 

Hi Nadia! This is again a well-done job. A few notes:
1. You used the ```dropna()``` method. As far as I know, this will drop any row that contains one ```NA``` value, which is why we have 217 participants. If we look at the paper, they suggest that "235 participants completed all 10 instruments." I'm thinking maybe we only remove the participants that gave ```NA```s to all the items.

For example, if we look at participant with ```id``` 63, they actually gave responses to the majority of items but still got removed in the cleaned data. In this case, I suggest we only remove those items that with ```NA```s. We can do so after the df is converted into the long format. Would you agree with this approach?

2. I am thinking maybe we can keep all of these scales as one large dataset as they all measure "participants' endorsement on statements about procrastination" or very similar. @ben-domingue Couuld you confirm if this would be a reasonable case to merge these datasets. Thank you for the clarification!

**Comment by KingArthur0205** [comment]
No problem. Perhaps Ben @ben-domingue can help us out and confirm my suggested approach above : )

**Comment by ben-domingue** [comment]
i'm ok with the NA strategy and having all the procrastination items together here. thanks both!

**Comment by ben-domingue** [comment]
@Nadiayen @KingArthur0205 making sure you two get an email note.

**Comment by KingArthur0205** [comment]
Thank you!

**Comment by Nadiayen** [comment]
I've updated the Processed Data and my previous Python code. Thank you all!

**Comment by KingArthur0205** [comment]
Thanks so much, Nadia, for your quick response! I’ll go ahead and close this issue and ensure the code and data are added. : )

**Comment by KingArthur0205** [comment]
Code added. See https://github.com/ben-domingue/irw/pull/702

**Comment by ben-domingue** [comment]
@KingArthur0205 do i just need to upload the csv here?

**Comment by KingArthur0205** [comment]
@ben-domingue Yes. I'm updating the dictionary : )

**Comment by KingArthur0205** [comment]
@ben-domingue Sorry I forgot the license. Could you also add the derived license from email please? Cheers!

**Comment by ben-domingue** [comment]
@KingArthur0205 should be
CC BY 4.0

**Comment by KingArthur0205** [comment]
Added
