### ISSUE TITLE
Elementary school climate through teachers’ eyes: Portuguese adaptation of the Organizational Climate Description Questionnaire Revised for Elementary Schools

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#438]
https://osf.io/zn4fd/

License: CC-By Attribution 4.0 International

**Comment by KingArthur0205** [comment]
**Portuguese adaptation of the Organizational Climate Description Questionnaire Revised for Elementary Schools (OCDQ-RE)**:
42 items responded by 687 participants, which match with data description) The questionnaire applied a 4-point Likert scale(1-4).

Study 2 comprises data from a second trial involving 81 of the 687 participants from Study 1 for confirmatory factor analysis. However, the authors did not clearly label participant IDs, making it challenging to validate the data set's integrity. Given this limitation, I am inclined to **exclude the Study 2 data**.

**Comment by KingArthur0205** [comment]
Data:
[QCDQES_Oliveira_2022.csv](https://github.com/user-attachments/files/17534810/QCDQES_Oliveira_2022.csv)

Code:
```
# Paper:
# Data: https://osf.io/zn4fd/

library(haven)
library(dplyr)
library(tidyr)

df <- read_sav("2021_sample 687.sav")
df[] <- lapply(df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})
df <- df |>
  mutate(id=row_number()) |>
  select(id, starts_with("OCDQ"), -ends_with("R"))

save(df, file="QCDQES_Oliveira_2022.Rdata")
write.csv(df, "QCDQES_Oliveira_2022.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
PR: https://github.com/ben-domingue/irw/pull/647
Entry added into dictionary at row 604. Marked yellow to denote as "unfinished'

**Comment by ben-domingue** [comment]
@KingArthur0205 data still in wide format above.

**Comment by KingArthur0205** [comment]
@ben-domingue I forgot to pivot the dataframe at the end.(sorry) Data, code, and PR are all updated acoordingly. : (

**Comment by ben-domingue** [comment]
@KingArthur0205 still showing up as wide?

**Comment by KingArthur0205** [comment]
@ben-domingue Can you check again please? : (

**Comment by ben-domingue** [comment]
looks good now :)
done

**Comment by KingArthur0205** [comment]
@ben-domingue Merging the code.
