### ISSUE TITLE
Assessing the validity of the Male Genital Self-Image Scale and the Gynaecologic Cancer Lymphedema Questionnaire in a UK population of healthy males over forty

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#442]
https://osf.io/5vhju/

License: CC-By Attribution 4.0 International

**Comment by KingArthur0205** [comment]
48 participants. 9 provided all ```NA``` responses and are hence removed.

The following 2 scales are merged into 1:
1. **Male Genital Self-image Scale (MGSIS)**: 5 items on a 4-point Likert scale. The original responses "Strongly Disagree", "Disagree", "Agree", "Strongly Agree" are encoded to 0-4.
2. **Gynaecologic Cancer Lymphedema Questionnaire (GCLQ)**: 20 items on a Yes/No scale. The responses "No"/"Yes" are encoded to 0/1.

**Comment by KingArthur0205** [comment]
Data:
[MGSISGCLQ_Hollyhead_2018.csv](https://github.com/user-attachments/files/17927860/MGSISGCLQ_Hollyhead_2018.csv)

Code:
```
# Data: https://osf.io/5vhju/
#  Paper: 
library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)

df <- read.xlsx("MGSIS-5 and GCLQ Data.xlsx")
df <- df[, colSums(!is.na(df)) > 0]
df$id <- seq_len(nrow(df))
df <- df |>
  select(-Start.time, -Completion.time, -Email, -`Are.you.a.resident.of.the.UK?`, -`How.old.are.you?`)
df <- df[!apply(df[, -which(names(df) == "id")], 1, function(row) all(is.na(row))), ]

mgsis_df <- df |>
  select(id, starts_with("I"))
GCLQ_df <- df |>
  select(-starts_with("I"), id)

GCLQ_df[] <- lapply(GCLQ_df, function(x) ifelse(x == "Yes", 1, ifelse(x == "No", 0, x)))
GCLQ_df <- GCLQ_df %>%
  mutate(across(everything(), ~ as.numeric(as.character(.))))
GCLQ_df <- pivot_longer(GCLQ_df, cols=-id, names_to="item", values_to="resp")

likert_map <- c(
  "Strongly Disagree" = 1,
  "Disagree" = 2,
  "Agree" = 3,
  "Strongly Agree" = 4
)

mgsis_df <- pivot_longer(mgsis_df, cols=-id, names_to="item", values_to="resp")
mgsis_df$resp <- likert_map[mgsis_df$resp]

final_df <- rbind(mgsis_df, GCLQ_df)

save(final_df, file="MGSISGCLQ_Hollyhead_2018.Rdata")
write.csv(final_df, "MGSISGCLQ_Hollyhead_2018.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
@ben-domingue PR for issue: https://github.com/ben-domingue/irw/pull/715
Data entry is added into the dictionary

**Comment by ben-domingue** [comment]
i see 26 items rather than the 25 there should be?

**Comment by KingArthur0205** [comment]
I think I accidentally included a question for collection of demographic data:
"Do.you.have.a.medical.condition.which.affects.your.lower.body.or.could.impact.how.you.feel.about.your.genitals? "

I will remove this from the dataset. Thanks for pointing this tou!

**Comment by ben-domingue** [comment]
@KingArthur0205 at the risk of being a pain, could we add this info as a covariate. so have 
```
cov_medical_condition=1 (if person has condition) 0 (if not)
```
this will then be constant across the `id` entries?

**Comment by KingArthur0205** [comment]
@ben-domingue Certainly! PR and data modified
