### ISSUE TITLE
Assessing Handwriting Skills in a Web Browser: Development and Validation of an Automated Online Test in Japanese Kanji

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#455]
https://osf.io/gver2/
License: CC-By Attribution 4.0 International 

https://osf.io/preprints/osf/ynm8a

**Comment by saviranadela** [comment]
data: 
[KanjiOAHaS_Inoue_2024.csv](https://github.com/user-attachments/files/17826827/KanjiOAHaS_Inoue_2024.csv)

code:
```
library(dplyr)

df <- read.csv("Raw_Data_20240607.csv")

df <- df %>%
  select(student_id, item, score, total_time) %>%
  rename(id = student_id, resp = score, rt = total_time)


write.csv(df, "KanjiOAHaS_Inoue_2024.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
they have response time here, but since some of the items are paper-and-pencil based, those items have NA rt values.

**Comment by saviranadela** [comment]
PR: https://github.com/ben-domingue/irw/pull/701

**Comment by KingArthur0205** [comment]
Hi Savira, I noticed that there are some ```NA``` values if we run the code below. If we look at the original data, we can see that many rows have basically all ```NA```s. I was thinking perhaps we can get rid of those rows.
```
print(length(is.na((frm_df$resp))))
[1] 9850
```

**Comment by saviranadela** [comment]
oops forgot to check that. updated!

**Comment by KingArthur0205** [comment]
@saviranadela Hi Savira. I'm thinking perhaps those ```rt``` are total response time rather than item-level. Could you kindly provide your insights into this? Thx for the clarification : )

**Comment by saviranadela** [comment]
@KingArthur0205 i see that it’s unique per row, which is at the item level. why did you think it represents the total? i could be wrong, so i’d like to confirm with you as well!

**Comment by KingArthur0205** [comment]
@saviranadela I might be mistaken : ), but my understanding of the ```rt``` column is that each item should have its own associated response time. For instance, if there are 10 items, I would expect 10 unique 'response times' within the row, rather than a single value

**Comment by ben-domingue** [comment]
yeah, this kind of response time isn't quite what we are looking for. thanks all!

**Comment by KingArthur0205** [comment]
@ben-domingue @saviranadela My apologies. I think the way Savira processed the data was correct. I thought there were multiple items in the same row, which led me to believe we needed more ```rt``` values.

But in this dataset, they organized it such that one row only has one item and hence one ```rt```. Thx Savira for educating me on Slack. : )

**Comment by saviranadela** [comment]
oh no problem! thanks @KingArthur0205 and @ben-domingue !

**Comment by ben-domingue** [comment]
yeah excellent eye @saviranadela !

**Comment by ben-domingue** [comment]
one note about the `rt` values @saviranadela : they should be in seconds not milliseconds. nbd, i changd it on my end so you don't need to do anything (just a note for next time)

**Comment by KingArthur0205** [comment]
Apologies, this one's on me as I forgot about this too. I’ll make sure to note it down.

**Comment by saviranadela** [comment]
oh, well noted!
