### ISSUE TITLE
Self-efficacy in Bipolar Disorder: Development and Validation of a Self-Report Scale

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#459]
https://osf.io/c4v7g/

Smith, L. M., Erceg-Hurn, D. M., McEvoy, P. M., & Lim, L. (2019). Self-efficacy in Bipolar Disorder: Development and Validation of a Self-Report Scale. Journal of Affective Disorders. [https://doi.org/10.1016/j.jad.20…](https://doi.org/10.1016/j.jad.2019.10.026)

**Comment by ben-domingue** [comment]
email permission

**Comment by KingArthur0205** [comment]
**Managing Bipolar Disorder Scale**: 22 items on a 10-point Likert scale.

In the paper they said they had 303 participants, but only 302 participants were given in the data.

**Comment by KingArthur0205** [comment]
Data:

Code:
```
# Paper: https://www.sciencedirect.com/science/article/pii/S0165032719302046
# Data: https://osf.io/c4v7g/
library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)

df <- read.table("bpses_pre_for_factor.dat", header = TRUE, sep = ",", stringsAsFactors = FALSE)
colnames(df) <- paste0("MBDS", 1:22)
df$id <- seq_len(nrow(df))
df <- pivot_longer(df, cols=-id, values_to = "resp", names_to = "item")
df$resp[df$resp == 999] <- NA

save(df, file="SBD_Smith_2020.Rdata")
write.csv(df, "SBD_Smith_2020.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
PR for issue: https://github.com/ben-domingue/irw/pull/709

**Comment by ben-domingue** [comment]
@KingArthur0205 you say a 10-point likert scale but we have:
```
  0   1   2   3   4   5   6   7   8   9  10 
249 180 402 526 589 957 665 789 828 445 991 

````
i'm worried the 0s might be errors?

**Comment by KingArthur0205** [comment]
@ben-domingue Sorry about the confusion, I meant "0 (“I cannot do this activity at all”) to 10 (“I am certain I can do this activity”)."

**Comment by ben-domingue** [comment]
so 0-10 is fine here? looks like it, i'll process. thanks!

**Comment by KingArthur0205** [comment]
Confirming 0-10 is fine. : )
