### ISSUE TITLE
A reconsideration of the Self-Compassion Scale's total score: Self-compassion versus self-criticism

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#488]
https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/RIYMFV

**Comment by saviranadela** [comment]
processed data: 
[SCS_Lopez_2015.csv](https://github.com/user-attachments/files/17615202/SCS_Lopez_2015.csv)


code:
```
library(haven)
library(dplyr)
library(tidyr)

df <- read_sav("database López et al (2015)_10411_20525.sav")
df$id <- seq(1, nrow(df))

df <- df %>%
  select(id, SCS1:SCS24) %>%
  pivot_longer(SCS1:SCS24,
               names_to = "item",
               values_to = "resp")

write.csv(df, "SCS_Lopez_2015.csv")
```

**Comment by saviranadela** [comment]
PR: https://github.com/ben-domingue/irw/pull/676

**Comment by ben-domingue** [comment]
@saviranadela looks good. confirm one thing: i think you included row numbers. nbd i just removed them but wanted to confirm that is all it was.

**Comment by ben-domingue** [comment]
wait i'm now seeing a closed PR. everything ok here?

**Comment by saviranadela** [comment]
@ben-domingue hi, i just closed the previous PR (unmerged) and created a new one for the revised code
https://github.com/ben-domingue/irw/pull/680

sorry if i'm doing the wrong steps!

**Comment by saviranadela** [comment]
revised processed data: 
[SCS_Lopez_2015.csv](https://github.com/user-attachments/files/17625321/SCS_Lopez_2015.csv)

**Comment by ben-domingue** [comment]
got it!
