### ISSUE TITLE
Replication Data for: Psychometric properties of the Emotion Regulation Questionnaire

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#503]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/7S6FWB

**Comment by saviranadela** [comment]
paper: https://www.tandfonline.com/doi/full/10.1080/23311908.2022.2053385#d1e388

interesting study but i couldn't locate the item-response level data, the file on Dataverse only includes aggregated data for each item group.
