### ISSUE TITLE
Replication data for: Psychometric properties of the SL-7 scale in academic settings

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#506]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FDDY2N

**Comment by KingArthur0205** [comment]
SL_df: 617 partcipants, 4 items,  scale from 1 to 5.

**Comment by KingArthur0205** [comment]
Data:
[RD_PpSL7as_Ghasemy_2024_SL.csv](https://github.com/user-attachments/files/17319525/RD_PpSL7as_Ghasemy_2024_SL.csv)

Code:
```
# Paper:
# Data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FDDY2N

library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)
library(readr)
library(readxl)

remove_na <- function(df) {
  df <- df[!(rowSums(is.na(df[, -which(names(df) %in% c("id", "date"))])) == (ncol(df) - 2)), ]
  return(df)
}

SL_df <- read_xlsx("Data.xlsx")

SL_df <- SL_df %>%
  mutate(id = row_number() )

SL_df  <- SL_df |>
  select(starts_with("SL"), id)

SL_df  <- remove_na(SL_df)
SL_df  <- pivot_longer(SL_df , cols=-c(id), names_to="item", values_to="resp")

save(SL_df, file="RD_PpSL7as_Ghasemy_2024_SL.Rdata")
write.csv(SL_df, "RD_PpSL7as_Ghasemy_2024_SL.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
any guesses as to what the sl-7 scale is? i can't quite figure that part out.

**Comment by KingArthur0205** [comment]
> any guesses as to what the sl-7 scale is? i can't quite figure that part out.

@ben-domingue It is servant-leadership 7-item version.
The original SL-7 scale has 7 items, but this study only used 4 items: 2, 3, 4, 5 in that scale.

More info at: https://www.sciencedirect.com/science/article/abs/pii/S1048984314001313

**Comment by ben-domingue** [comment]
Perfect, thank you! how on earth did you figure that out!

**Comment by KingArthur0205** [comment]
I searched this author's recent papers and found that he's fond of this scale. His most recent research and many previous papers involve using this scale. ;)
