### ISSUE TITLE
Replication Data for: Psychometric Properties and Measurement Invariance of the Lecturers' Academic Motivation Scale

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#508]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FGNOHV

**Comment by KingArthur0205** [comment]
There is no paper associated with this dataset. I couldn't find it on either the author's Google Scholar or personal web page. 
The scale is Academic Motivation Scale, but the original scale had 28 items within 4 sub-scales yet this questionnaire only had 5 items. As these 5 questions can be from any of the 4 sub-scales, we cannot map them to the exact questions.

I suggest we may need to close this one unfortunately. :(
