### ISSUE TITLE
Psychometric evaluation of the Polish adaptation of the Body Appreciation Scale-2 for Children (BAS-2C)

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#510]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LGXP5A

**Comment by KingArthur0205** [comment]
**Self-Perception Profile(SPP_df)**: 202 partcipants, 12 items, ranging form 1 to 4.
**Body Appreciation Scale for Children(BAS_df)**:202 partcipants, 10 items, 5-point Likert scale(1 to 5)
**Body satisfaction(Body_df)**:201 partcipants, 2 items, ranging from underweight (1) to obese (7).

**Comment by ben-domingue** [comment]
@KingArthur0205 all 24 items are about body satisfaction here? your above comment had me confused.

**Comment by KingArthur0205** [comment]
Yes, they measure the participants' feelings towards their bodies with different aspects. 

That's why I wanted to merge these together.:)

**Comment by ben-domingue** [comment]
ah i see i had missed the original note. make sense.
