### ISSUE TITLE
Patient acceptance of implantable cardioverter-defibrillator: initial psychometric investigation of the Florida Patient Acceptance Survey

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#511]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/3UHKUM
look for PROM

**Comment by saviranadela** [comment]
processed data: 
[FPAS_Silva_2022.csv](https://github.com/user-attachments/files/17639524/FPAS_Silva_2022.csv)

code:
```
library(dplyr)
library(tidyr)

df <- read.csv("DATA_FPAS_2022.csv")

df <- df %>%
  select(record_id, fpas_1:fpas_18) %>%
  rename(id = record_id)

df <- df %>%
  pivot_longer(fpas_1:fpas_18,
               names_to = "item",
               values_to = "resp")

write.csv(df, "FPAS_Silva_2022.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
https://github.com/ben-domingue/irw/pull/685

cc: @KingArthur0205 @ben-domingue

**Comment by KingArthur0205** [comment]
Hi Savira. This looks great! I'll ship it to Ben

Note: I've implemented an issue classifier, so the notifications that you saw above is a bot and isn't really me lol.
