### ISSUE TITLE
TC-CHEXI

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#518]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YRLEAY

is there any documentation of what this is?

**Comment by KingArthur0205** [comment]
I think this one is the **CHEXI parent/teacher report in Chinese**. The questionnaires can be found here: https://chexi.se/translations

The scale has 24 items on a 5-point Likert scale(1-5). In the original dataset, 999 was used as place-holder for missign data.

**Comment by KingArthur0205** [comment]
Data:
[CHEXI_Lin_2019.csv](https://github.com/user-attachments/files/17933731/CHEXI_Lin_2019.csv)

Code:
```
# Data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YRLEAY
library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)
library(readxl)

df <- read_excel("no_Names_coding-0623_forupload.xlsx", sheet = "data")
df$id <- seq_len(nrow(df))
df <- df |>
  select(id, starts_with("item"))
df[df == 9999] <- NA
df <- df[!apply(df[, -which(names(df) == "id")], 1, function(row) all(is.na(row))), ]
df <- pivot_longer(df, col=-id, values_to="resp", names_to="item")

save(df, file="CHEXI_Lin_2019.Rdata")
write.csv(df, "CHEXI_Lin_2019.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
@ben-domingue PR for issue: https://github.com/ben-domingue/irw/pull/717
Data entry is added to the dictionary
