### ISSUE TITLE
Multi-Sensory Integration Impairment in Patients with Minimal Hepatic Encephalopathy

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#519]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/53W4LE

**Comment by saviranadela** [comment]
paper: https://www.nature.com/articles/s41598-017-15113-1

another interesting study, but the data seems to have aggregated responses only

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/9f1bbe9a-5b32-49a6-8a9e-3d2a47935b68">
<img width="802" alt="image" src="https://github.com/user-attachments/assets/ff8c6722-b3e0-43af-94ef-9598ea3abd1c">

cc: @KingArthur0205

**Comment by ben-domingue** [comment]
good eye @saviranadela
