### ISSUE TITLE
Multidimensional nonadditivity in one-facet g-theory designs: A profile analytic approach.

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#53]
https://psycnet.apa.org/record/2022-19009-001

**Comment by rn2407stanford** [comment]
I am not sure the data is available. The article says they used Parkinson’s Progressive Markers Initiative (PPMI) data, but when I use their website they require data access request https://www.ppmi-info.org/access-data-specimens/download-data .
