### ISSUE TITLE
Experience of introducing an electronic health records station in an objective structured clinical examination to evaluate medical students’ communication skills in Canada: a descriptive study

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#530]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IFMDCC

**Comment by KingArthur0205** [comment]
**Questionnaire on Electronic Medical Record developed on OpenLabyrinth**:
10 items with 99 participants. The responses were on 1 0-5 scale.

**Comment by KingArthur0205** [comment]
Data:
[EMSC_Kuan-chin_2023.csv](https://github.com/user-attachments/files/17533253/EMSC_Kuan-chin_2023.csv)

Code:
```
# Paper: https://jeehp.org/journal/view.php?doi=10.3352/jeehp.2023.20.22
# Dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IFMDCC

library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)

df <- read.xlsx("jeehp-20-22-dataset1.xlsx")
df <- df %>%
  rename(id=OttawaU_ID) %>%
  select(id, starts_with("STN10"), -Stn1010)

df <- pivot_longer(df, cols=-id, values_to="resp", names_to = "item")

save(df, file="EMSC_Kuan-chin_2023.Rdata")
write.csv(df, "EMSC_Kuan-chin_2023.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
weird distribution of rseponses but seems like it is legit.

```
  1   2   3   4   5 
  1  53 199 337  95 
```

**Comment by ben-domingue** [comment]
send pr @KingArthur0205

**Comment by KingArthur0205** [comment]
The "1"s represent not being empathetic at all for the patients. I guess it makes sense that less people would select that option.

**Comment by ben-domingue** [comment]
gotcha

**Comment by KingArthur0205** [comment]
@ben-domingue PR created: https://github.com/ben-domingue/irw/pull/645.: )
