### ISSUE TITLE
Evidence for Conserved Strategies in Cost-Benefit Decision-Making in Rodents and Humans

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#537]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/OZARPL

**Comment by saviranadela** [comment]
the data file is empty. are you facing the same issue Ben, Arthur? @ben-domingue @KingArthur0205

**Comment by KingArthur0205** [comment]
Wait this zipped file is 5G?! I may not have enough storage to download it at the moment. Let me clean some space and try later ;(

**Comment by saviranadela** [comment]
i know right :')
