### ISSUE TITLE
Development and Pyschometric Validation of Measures for Vaginal Ring Adherence Survey

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#540]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/5W9HXM

**Comment by saviranadela** [comment]
working on this

**Comment by saviranadela** [comment]
hi @ben-domingue i just wanted to double-check again. Continuous data and string/free-text data types shouldn’t be included in the item-response, correct? It should only consist of scale-like or yes/no responses, right?
example: 
![image](https://github.com/user-attachments/assets/8906e155-1b60-4a95-a1f5-d5f4b009ce74)

also, do you think these kind of data about trials should be included in our final data?
![image](https://github.com/user-attachments/assets/76eb2b86-0568-4d2f-9fef-d383e26d40b7)
![image](https://github.com/user-attachments/assets/0c85da78-83ff-42c5-9b79-270059555f29)

**Comment by ben-domingue** [comment]
a few notes:
- continuous data (e.g., the position of a slider on a slider scale) are ok. string text are not. 
- the first two are not relevant as they are demographic info. we just want things from psychometric scales, *let's chat about this today?* @saviranadela 
- last two also out of bounds. 

what we really want here is the adhernece scale

**Comment by saviranadela** [comment]
Processed data: 
[Adherence_Zissette_2018.csv](https://github.com/user-attachments/files/17271192/Adherence_Zissette_2018.csv)

Code:
```
library(tidyr)
library(dplyr)

df <- read.csv("Adherence_Measurement_ARV_Rings_Psychometrics.csv")
df$time_start <- as.POSIXct(df$time_start, format = "%m/%d/%Y %H:%M")
df$time_stop <- as.POSIXct(df$time_stop, format = "%m/%d/%Y %H:%M")

df$rt <- as.numeric(difftime(df$time_stop, df$time_start, units = "secs"))

df <- df %>%
  select(KEY, rt, matches("q_f_ring|q_f_gel|q_f_pill")) %>%
  pivot_longer(c(matches("q_f_ring|q_f_gel|q_f_pill")),
               names_to = "item",
               values_to = "resp") %>%
  filter(!(resp %in% c(99, 0)) & !is.na(resp)) %>%
  rename(id = KEY)

# print(unique(df$resp)) #checking resp

write.csv(df, "Adherence_Zissette_2018.csv", row.names=FALSE)
```

still asking something to Arthur, will do the PR once everything's clear!

**Comment by ben-domingue** [comment]
1. i wanted to check on the numbers here. we have 143 items in total. i think i'm ok with that given that they discuss 76 +26 + 48 items on the dataverse page. but we only have 425 people which seems low given that they talk about 709 people. any thoughts? 

2. i think `rt` here must be in miilliseconds? should be in seconds. i'm actually confused as to how it ends up in milliseconds given that you got things in unix time so maybe we should investigate further?

**Comment by saviranadela** [comment]
hi Ben,

1. Oops, I made a mistake. I misunderstood the survey and didn’t include the 76+26 items. Instead, I only included the 3 sets of 48 additional product-related items, most of which had null responses since these were optional questions (and I excluded the null responses, which is why we ended up with only 425 participants). I’ll make sure to do better next time! (Code has been updated).

2. Apparently rt shown here represents the total survey time for each participant, not the time for each individual item. I think it might not be the rt we should include, right?

**Comment by saviranadela** [comment]
thanks for your encouraging words Ben! will try to be more thorough.

PR: https://github.com/ben-domingue/irw/pull/606

**Comment by ben-domingue** [comment]
@saviranadela i think something went wrong as we now have 263 items which seems like too many. ;)
I think we want these items:

> Assess content and construct validity of draft measures. The survey was divided into three sections. All women regardless of trial experience responded to 76 “screener” items measuring potential predictors of adherence; 26 items from the Crowne-Marlowe social desirability scale were also distributed in groups within this section. Only former trial participants responded to an additional set of 48 monitoring items assessing product-specific adherence attitudes and behaviors.

and, honestly, I think we'd want to split adherence and the social desirability scales into two files (so social desirability with 26 items and the adherence scales with 76+48 items). does that make sense?

**Comment by ben-domingue** [comment]
note also that i inadvertently accepted the PR so we need to revisit that.

**Comment by saviranadela** [comment]
Thanks for catching that! This is indeed a bit confusing to me. I rechecked, and you're right, it should be below 263 items (I mistakenly included 8 unnecessary ones). However, it’s still more than the number stated in the description. They don’t clearly specify which are the 76 items and which are the 26, so I did the math, but it still doesn’t add up. I'll take another look at it, and I may need to contact the data owner as well.

And I’m really sorry about the PR :(

**Comment by ben-domingue** [comment]
don't worry about the PR! it's easy to fix when we are ready :)
let me take a look at the raw data tomorrow. we can further debrief after.

**Comment by ben-domingue** [comment]
OK I looked at this. I think the crowne-marlowe social desirability bias scale is SDB parts I, II, and III. it is these items:
```
c("q_s_025_SDB", "q_s_026_SDB", "q_s_027_SDB", "q_s_028_SDB", 
"q_s_029_SDB", "q_s_030_SDB", "q_s_031_SDB", "q_s_032_SDB", "q_s_056_SDB", 
"q_s_057_SDB", "q_s_058_SDB", "q_s_059_SDB", "q_s_060_SDB", "q_s_061_SDB", 
"q_s_062_SDB", "q_s_063_SDB", "q_s_084_SDB", "q_s_085_SDB", "q_s_086_SDB", 
"q_s_087_SDB", "q_s_088_SDB", "q_s_089_SDB", "q_s_090_SDB", "q_s_091_SDB", 
"q_s_092_SDB", "q_s_093_SDB")
```
why don't we do this:
- read the original csv in. 
- process just the social desirability bias scale
- we'll just post that. the rest is more complicated. 
that an ok plan @saviranadela ?

**Comment by saviranadela** [comment]
Processed data (SDB): 
[Adherence_Zissette_2018_SDB.csv](https://github.com/user-attachments/files/17337317/Adherence_Zissette_2018_SDB.csv)

Code:
```
library(tidyr)
library(dplyr)

df <- read.csv("Adherence_Measurement_ARV_Rings_Psychometrics.csv")

df <- df %>%
  select(KEY, matches("SDB")) %>%
  pivot_longer(c(matches("SDB")),
               names_to = "item",
               values_to = "resp") %>%
  filter(!(resp %in% c(99, 0)) & !(is.na(resp)))  %>%
  rename(id = KEY)


write.csv(df, "Adherence_Zissette_2018_SDB.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
@ben-domingue i revisited the data and reviewed each item. it appears that the 'screener' items measuring potential predictors of adherence total 75, not 76. it seems they miscalculated the 'reasons for trial participation' items, where 17 items were counted, but it should be 16 (items 40 to 55).

in total, there are 112 items, broken down as follows:
75 screener items
26 SDB items
11 new items (Disclosure, as noted on page 8 of the codebook)

plus 48 x 3 additional monitoring items

would you like me to proceed with processing the 75 + (48 x 3) data, or would you prefer I focus elsewhere? apologies if the numbers cause any confusion! i'm happy to clarify or adjust as needed based on your guidance

also, should I create a new PR for the SDB?

**Comment by ben-domingue** [comment]
let's just do the 26 SDB items. the rest are much weirder. 
and i think when we are done we can 'edit' the existing bit of code. shouldn't be challenging for us to figure out when we get there :)

**Comment by saviranadela** [comment]
updated PR: https://github.com/ben-domingue/irw/pull/612 !

**Comment by ben-domingue** [comment]
@saviranadela this is great, thank you! 
@KingArthur0205 note that i'm closing this one. i got it ;)
