### ISSUE TITLE
Measuring the feeling of distant intimacy with political figures across cultures: Development, construct validity, factor replicability, and measurement invariance of parasocial relationship with political figures (PSR-P) scale

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#542]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/F3KS7M

Paper: https://osf.io/preprints/psyarxiv/mcwsg

**Comment by KingArthur0205** [comment]
Working on this

**Comment by KingArthur0205** [comment]
@ben-domingue The study 2 assesses "latent factor of parasocial relationship with a political figure." Each participant is assigned a figure while doing the questionnaries.

Should we include this figure as well? I think leaving it out might result in missing informative details. Perhaps we can simply label it as 'Figure'?

**Comment by KingArthur0205** [comment]
Zipped Versions(CSV and RData):
[PSR-P_Scale_Intimacy_Hakim_2018_CSV.zip](https://github.com/user-attachments/files/17143036/PSR-P_Scale_Intimacy_Hakim_2018_CSV.zip)
[PSR-P_Scale_Intimacy_Hakim_2018_RData.zip](https://github.com/user-attachments/files/17143037/PSR-P_Scale_Intimacy_Hakim_2018_RData.zip)


Individual Datasets:
[PSR-P_Scale_Intimacy_Hakim_2018_Study2_PPSR.csv](https://github.com/user-attachments/files/17143027/PSR-P_Scale_Intimacy_Hakim_2018_Study2_PPSR.csv)
[PSR-P_Scale_Intimacy_Hakim_2018_Study2_PSI.csv](https://github.com/user-attachments/files/17143028/PSR-P_Scale_Intimacy_Hakim_2018_Study2_PSI.csv)
[PSR-P_Scale_Intimacy_Hakim_2018_Study2_PSR.csv](https://github.com/user-attachments/files/17143029/PSR-P_Scale_Intimacy_Hakim_2018_Study2_PSR.csv)
[PSR-P_Scale_Intimacy_Hakim_2018_Study3.csv](https://github.com/user-attachments/files/17143030/PSR-P_Scale_Intimacy_Hakim_2018_Study3.csv)

Code:
```
# Paper: https://osf.io/preprints/psyarxiv/mcwsg
# Data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/F3KS7M
library(haven)
library(dplyr)
library(tidyr)
library(readxl)

scale_to_7 <- function(x) {
  return(round(1 + (x / 10) * 6))
}

study2_df_path <- "./Dataset/Study2/Study2Data.sav"
study2_df <- read_sav(study2_df_path)

study3_df_path <- "./Dataset/Study3/DataStudy_3.sav"
study3_df <- read_sav(study3_df_path)

# ------ Process Study 2 Dataset ------
study2_df[] <- lapply(study2_df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})
study2_df <- study2_df |>
  select(-Usia, -JK, -Universitas, -Angkatan, -Email, -PSRP, -PPSR, -PSIP) |>
  rename(id=Nama, figure=Tokoh)

study2_psr_df <- study2_df |>
  select(id, figure, starts_with("a"))
study2_ppsr_df <- study2_df |>
  select(id, figure, starts_with("b"))
study2_psi_df <- study2_df |>
  select(id, figure, starts_with("c"))

study2_psr_df <- pivot_longer(study2_psr_df, cols=-c(id, figure), names_to="item", values_to="resp")
study2_ppsr_df <- pivot_longer(study2_ppsr_df, cols=-c(id, figure), names_to="item", values_to="resp")
study2_psi_df <- pivot_longer(study2_psi_df, cols=-c(id, figure), names_to="item", values_to="resp")

save(study2_psr_df, file="PSR-P_Scale_Intimacy_Hakim_2018_Study2_PSR.Rdata")
write.csv(study2_psr_df, "PSR-P_Scale_Intimacy_Hakim_2018_Study2_PSR.csv", row.names=FALSE)
save(study2_psi_df, file="PSR-P_Scale_Intimacy_Hakim_2018_Study2_PSI.Rdata")
write.csv(study2_psi_df, "PSR-P_Scale_Intimacy_Hakim_2018_Study2_PSI.csv", row.names=FALSE)
save(study2_ppsr_df, file="PSR-P_Scale_Intimacy_Hakim_2018_Study2_PPSR.Rdata")
write.csv(study2_ppsr_df, "PSR-P_Scale_Intimacy_Hakim_2018_Study2_PPSR.csv", row.names=FALSE)

# ------ Process Study 3 Dataset ------
study3_df[] <- lapply(study3_df, function(col){
  attr(col, "label") <- NULL
  return(col)
})
study3_df <- study3_df |>
  select(-Age, -Favpol, -RWA, -BA, -IDEO, -ELAB, -PolEff, 
         -PSRP, -Country, -Gender) |>
  rename(id=ID, fav_pol=PI1)
study3_df$fav_pol <- tolower(study3_df$fav_pol)

study3_lib_df <- study3_df |>
  select(id, fav_pol, starts_with("Lib"))
study3_df <- study3_df |>
  select(-starts_with("Lib"))

study3_lib_df[] <- lapply(study3_lib_df, function(column) {
  if (is.numeric(column) && !identical(column, study3_lib_df$id)) {
    scale_to_7(column)
  } else {
    column  # Return 'id' or non-numeric columns unchanged
  }
})

study3_lib_df <- pivot_longer(study3_lib_df, cols=-c(id, fav_pol), names_to="item", values_to="resp")
study3_df <- pivot_longer(study3_df, cols=-c(id, fav_pol), names_to="item", values_to="resp")
study3_df <- rbind(study3_df, study3_lib_df)

save(study3_df, file="PSR-P_Scale_Intimacy_Hakim_2018_Study3.Rdata")
write.csv(study3_df, "PSR-P_Scale_Intimacy_Hakim_2018_Study3.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
@ben-domingue @KingArthur0205 The above work may need adjustments before creating PR.

**Comment by ben-domingue** [comment]
so each person is assigned a different figure (or one figure from some set of figures)? looking at the paper, my sense is that a person responds to items in the context of a figure, so can we do something like:
```
id,item,figure,resp
1,i1,f1,X
1,i2,f,X
...
1,i1,f2,X
```
i'm not sure if the person answers `i1` twice (first for `f1` and then for `f2`) but even if not i think we should just add the figure info like this? it's a delicate one...

**Comment by ben-domingue** [comment]
actually, let me ask a question: do we think they are measuring:
a. person X's parasocial relationship with figure Y
b. the degree to which figure Y generates feelings of a parasocial relationship in people

**Comment by KingArthur0205** [comment]
Sorry I didn't make this clear. The person first "declares" a political figure and answered questions with reference to the nominated figure.

I would say both are measured

> a. person X's parasocial relationship with figure Y 

This is measured by asking participants to respond to the PSR-P and PPSR items, such as how they feel about the figure and how the figure influences their views. For example, one PPSR item states, "when [the figure] expresses how he feels about the news, it helps me make up my own mind about the media."

> b. the degree to which figure Y generates feelings of a parasocial relationship in people

This is measured by PSI-Process. (e.g., PSI-Process items like "Sometimes I felt like speaking out on [the figure]").

**Comment by ben-domingue** [comment]
does this seem right to you? it seems to me like if the person is picking their own 'figure' then i'm ok with that as a bit of metadata (and keeping items fixed across people)

**Comment by KingArthur0205** [comment]
PR for issue: https://github.com/ben-domingue/irw/pull/582
