### ISSUE TITLE
FACIT Dyspnea (PROMIS Dyspnea)

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#544]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IBFK5H

**Comment by KingArthur0205** [comment]
working on this

**Comment by KingArthur0205** [comment]
Zipped Version:
[NAMPRB_Siwiak_2024_CSV.zip](https://github.com/user-attachments/files/17212394/NAMPRB_Siwiak_2024_CSV.zip)
[NAMPRB_Siwiak_2024_Rdata.zip](https://github.com/user-attachments/files/17212395/NAMPRB_Siwiak_2024_Rdata.zip)

Code
```
# Paper: 
# Data: https://osf.io/txn2y/
library(haven)
library(dplyr)
library(tidyr)

remove_na <- function(df) {
  df <- df[!(rowSums(is.na(df[, -which(names(df) %in% c("id", "date"))])) == (ncol(df) - 2)), ]
  return(df)
}

FACIT_df <- read_sav("NWHR0004_FINAL_OUTPUT.sav")

# ------ Dataset Pre-process ------
FACIT_df <- FACIT_df |>
  rename(id=CaseID)

FACIT_df[] <- lapply(FACIT_df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})

FACIT_df <- FACIT_df |>
  rename(date=STARTTIME)
FACIT_df$date <- as.numeric(as.POSIXct(FACIT_df$date, format="%a %b %d %H:%M:%S %Y", tz="UTC"))

FACIT_clinic10now1_df <- FACIT_df |>
  select(starts_with("clinic10now1"), id, date, -clinic10now1_t)
FACIT_clinic10now1_df <- remove_na(FACIT_clinic10now1_df)
FACIT_clinic10now1_df <- pivot_longer(FACIT_clinic10now1_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_clinic10now1_df[FACIT_clinic10now1_df == 2] <- 0
FACIT_clinic10now1_df[FACIT_clinic10now1_df == 8] <- NA
FACIT_clinic10now1_df[FACIT_clinic10now1_df == 9] <- NA


FACIT_clinic10ever1_df <- FACIT_df |>
  select(starts_with("clinic10ever1"), id, date,-clinic10ever1_t)
FACIT_clinic10ever1_df <- remove_na(FACIT_clinic10ever1_df)
FACIT_clinic10ever1_df <- pivot_longer(FACIT_clinic10ever1_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_clinic10ever1_df[FACIT_clinic10ever1_df == 2] <- 0
FACIT_clinic10ever1_df[FACIT_clinic10ever1_df == 8] <- NA
FACIT_clinic10ever1_df[FACIT_clinic10ever1_df == 9] <- NA

FACIT_clinic10_df <- rbind(FACIT_clinic10ever1_df, FACIT_clinic10now1_df)

save(FACIT_clinic10_df, file="FACIT_YOUNT_2021_clinic10.Rdata")
write.csv(FACIT_clinic10_df, "FACIT_YOUNT_2021_clinic10.csv", row.names=FALSE)

FACIT_othermeds_df <- FACIT_df |>
  select(starts_with("othermeds"), id, date, -othermeds1_t)
FACIT_othermeds_df  <- remove_na(FACIT_othermeds_df )
FACIT_othermeds_df  <- pivot_longer(FACIT_othermeds_df , cols=-c(id, date), names_to="item", values_to="resp")

#FACIT_othermeds_df [FACIT_othermeds_df == 2] <- 0
#FACIT_othermeds_df[FACIT_othermeds_df  == 8] <- NA
#FACIT_othermeds_df [FACIT_othermeds_df == 9] <- NA

#save(FACIT_othermeds_df , file="FACIT_YOUNT_2021_clinic10othermeds.Rdata")
#write.csv(FACIT_othermeds_df , "FACIT_YOUNT_2021_clinic10othermeds.csv", row.names=FALSE)

#---------facitx data
FACIT_facitx_df <- FACIT_df |>
  select(starts_with("facitx"), id, date)
FACIT_facitx_df  <- remove_na(FACIT_facitx_df )
FACIT_facitx_df <- pivot_longer(FACIT_facitx_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_a2facitx_df <- FACIT_df |>
  select(starts_with("a2_facitx"), id, date)
FACIT_a2facitx_df  <- remove_na(FACIT_a2facitx_df )
FACIT_a2facitx_df <- pivot_longer(FACIT_a2facitx_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_facitx_df $wave <- 0
FACIT_a2facitx_df$wave <- 1

Facitx_df <- rbind(FACIT_facitx_df,FACIT_a2facitx_df )

Facitx_df[Facitx_df == 8] <- NA
Facitx_df[Facitx_df == 9] <- NA

save(Facitx_df, file="FACIT_YOUNT_2021_Facitx.Rdata")
write.csv(Facitx_df, "FACIT_YOUNT_2021_Facitx.csv", row.names=FALSE)

#---------facit2x data
FACIT_facit2x_df <- FACIT_df |>
  select(starts_with("facit2x"), id, date)
FACIT_facit2x_df  <- remove_na(FACIT_facit2x_df )
FACIT_facit2x_df <- pivot_longer(FACIT_facit2x_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_a2facit2x_df <- FACIT_df |>
  select(starts_with("a2_facit2x"), id, date)
FACIT_a2facit2x_df  <- remove_na(FACIT_a2facit2x_df )
FACIT_a2facit2x_df <- pivot_longer(FACIT_a2facit2x_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_facit2x_df $wave <- 0
FACIT_a2facit2x_df$wave <- 1

Facit2x_df <- rbind(FACIT_facit2x_df,FACIT_a2facit2x_df )
Facit2x_df[Facit2x_df == 8] <- NA
Facit2x_df[Facit2x_df == 9] <- NA

save(Facit2x_df, file="FACIT_YOUNT_2021_Facit2x.Rdata")
write.csv(Facit2x_df, "FACIT_YOUNT_2021_Facit2x.csv", row.names=FALSE)

#---------facit3x data
FACIT_facit3x_df <- FACIT_df |>
  select(starts_with("facit3x"), id, date)
FACIT_facit3x_df  <- remove_na(FACIT_facit3x_df )
FACIT_facit3x_df <- pivot_longer(FACIT_facit3x_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_a2facit3x_df <- FACIT_df |>
  select(starts_with("a2_facit3x"), id, date)
FACIT_a2facit3x_df  <- remove_na(FACIT_a2facit3x_df )
FACIT_a2facit3x_df <- pivot_longer(FACIT_a2facit3x_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_facit3x_df $wave <- 0
FACIT_a2facit3x_df$wave <- 1

Facit3x_df <- rbind(FACIT_facit3x_df,FACIT_a2facit3x_df )
Facit3x_df[Facit3x_df == 8] <- NA
Facit3x_df[Facit3x_df == 9] <- NA

save(Facit3x_df, file="FACIT_YOUNT_2021_Facit3x.Rdata")
write.csv(Facit3x_df, "FACIT_YOUNT_2021_Facit3x.csv", row.names=FALSE)

#---------facitox data
FACIT_facitox_df <- FACIT_df |>
  select(starts_with("facitox"), id, date)
FACIT_facitox_df  <- remove_na(FACIT_facitox_df )
FACIT_facitox_df <- pivot_longer(FACIT_facitox_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_a2facitox_df <- FACIT_df |>
  select(starts_with("a2_facitox"), id, date)
FACIT_a2facitox_df  <- remove_na(FACIT_a2facitox_df )
FACIT_a2facitox_df <- pivot_longer(FACIT_a2facitox_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_facitox_df $wave <- 0
FACIT_a2facitox_df$wave <- 1

Facitox_df <- rbind(FACIT_facitox_df,FACIT_a2facitox_df )

Facitox_df[Facitox_df == 8] <- NA
Facitox_df[Facitox_df == 9] <- NA

save(Facitox_df, file="FACIT_YOUNT_2021_Facitox.Rdata")
write.csv(Facitox_df, "FACIT_YOUNT_2021_Facitox.csv", row.names=FALSE)

#-------randx data
FACIT_randx_df <- FACIT_df |>
  select(starts_with("randx"), id,date)
FACIT_randx_df <- remove_na(FACIT_randx_df)
FACIT_randx_df<- pivot_longer(FACIT_randx_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_randx_df[FACIT_randx_df == 8] <- NA
FACIT_randx_df[FACIT_randx_df == 9] <- NA

save(FACIT_randx_df, file="FACIT_YOUNT_2021_randx.Rdata")
write.csv(FACIT_randx_df, "FACIT_YOUNT_2021_randx.csv", row.names=FALSE)

#-------hadsx data
FACIT_hadsx_df <- FACIT_df |>
  select(starts_with("hadsx"), id, date)
FACIT_hadsx_df <- remove_na(FACIT_hadsx_df)
FACIT_hadsx_df <- pivot_longer(FACIT_hadsx_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_hadsx_df[FACIT_hadsx_df == 8] <- NA
FACIT_hadsx_df[FACIT_hadsx_df == 9] <- NA

save(FACIT_hadsx_df, file="FACIT_YOUNT_2021_hadsx.Rdata")
write.csv(FACIT_hadsx_df, "FACIT_YOUNT_2021_hadsx.csv", row.names=FALSE)

#------crqsasx data
FACIT_crqsasx_df <- FACIT_df |>
  select(starts_with("crqsasx"), id, date)
FACIT_crqsasx_df <- remove_na(FACIT_crqsasx_df )
FACIT_crqsasx_df <- pivot_longer(FACIT_crqsasx_df, cols=-c(id, date), names_to="item", values_to="resp")

FACIT_crqsasx_df[FACIT_crqsasx_df == 8] <- NA
FACIT_crqsasx_df[FACIT_crqsasx_df == 9] <- NA
FACIT_crqsasx_df[FACIT_crqsasx_df == 98] <- NA
FACIT_crqsasx_df[FACIT_crqsasx_df == 99] <- NA


save(FACIT_crqsasx_df, file="FACIT_YOUNT_2021_crqsasx.Rdata")
write.csv(FACIT_crqsasx_df, "FACIT_YOUNT_2021_crqsasx.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
flagging a few things that don't seem quite right. wanted to confirm

- this looks funky
```
[1] "FACIT_YOUNT_2021_Facitox.Rdata"
       id       date      item resp wave
1 2524824 1172600976 facitox01    1    0
2 2524824 1172600976 facitox02    1    0
3 2524824 1172600976 facitox03    2    0
4 2524824 1172600976 facitox04    0    0
5 2524824 1172600976 facitox05    0    0
6 2524824 1172600976 facitox06    0    0

    0     1     2     3     4     5     6     7    10 
29770 17654  4004  2223  1654  1625   333   327    81 
```
you say something should be on a scale going up to 10, but no 8 or 9 values? 
- FACIT_crqsasx_df: this never goes up to 8.

**Comment by KingArthur0205** [comment]
@ben-domingue 
1. FACIT_crqsasx_df: Sorry that I made a typo in the comment. The 8 suggests that the users didn't do the question(as shwon in figure), so I set them to ```NA```. The actual scale is from 1-7.
<img width="1502" alt="截屏2024-10-02 21 16 55" src="https://github.com/user-attachments/assets/859fea60-03c3-4121-a5f6-bfb87f34ce95">
2. FACIT_YOUNT_2021_Facitox: Apologies for the confusion; this was due to an oversight on my part when copying and pasting the code. They have switched from using 8/9 for "not done" to 88/99, which I missed updating. I will correct it right away. Thank you for your understanding, and I apologize again for the mistake.

**Comment by ben-domingue** [comment]
1. yeah 8=NA is perfect. 
2. no problem at all!! :)

**Comment by KingArthur0205** [comment]
PR for this issue: https://github.com/ben-domingue/irw/pull/590

**Comment by ben-domingue** [comment]
@KingArthur0205 this one is challenging! i think i have 10 datasets but you only documented 8 scales above. i need to map these below filenames to a brief description of the scales. if you could help with this at all i'd be super grateful! 

FACIT_YOUNT_2021_clinic10ever1.csv
FACIT_YOUNT_2021_Facit3x.csv
FACIT_YOUNT_2021_clinic10now1.csv
FACIT_YOUNT_2021_Facitox.csv
FACIT_YOUNT_2021_clinic10othermeds.csv
FACIT_YOUNT_2021_Facitx.csv
FACIT_YOUNT_2021_crqsasx.csv
FACIT_YOUNT_2021_hadsx.csv
FACIT_YOUNT_2021_Facit2x.csv
FACIT_YOUNT_2021_randx.csv

**Comment by KingArthur0205** [comment]
@ben-domingue Certainly! I should be more grateful for the careful checking of my work.

The 2 clinic10 datasets(```FACIT_YOUNT_2021_clinic10ever1.csv``` and ```FACIT_YOUNT_2021_clinic10now1.csv```) share similar structures, questions, and scales. For example:
```FACIT_YOUNT_2021_clinic10ever1.csv``` : Ever had - Diabetes
```FACIT_YOUNT_2021_clinic10now1.csv```: Current condition - Diabetes

Shall we merge them into one? I considered doing so but decided to keep them separate due to their time differences and original structures as two distinct scales

```FACIT_YOUNT_2021_clinic10othermeds.csv```
This shouldn't be in there as I believe this is mostly metadata.(as this records participants' medical conditions) I have removed them from the code/data.
<img width="1200" alt="截屏2024-10-04 10 09 26" src="https://github.com/user-attachments/assets/477ba3fc-b6b3-40b9-8f84-8e4fd1b72056">

**Comment by ben-domingue** [comment]
i'd vote we merge what we can! thank you :heart: 
i'm going to cut the FACIT stuff i have and wait for an update

**Comment by ben-domingue** [comment]
opening this as i think we will be updating, right @KingArthur0205

**Comment by KingArthur0205** [comment]
Yes, I have one question: If we merge the 'now' and 'ever' data, how should we mark the differences?

I believe we shouldn't use group or wave indicators here, as the item names already imply whether they come from 'now' or 'ever'.（e.g. clinic10ever_Anxiety) It seems we could simply merge them without additional labels. Could you please review this approach and let me know if it works? :) @ben-domingue

**Comment by ben-domingue** [comment]
let me make sure i follow: there are a sequence of questions (18 items) whether you have had a condition (a) ever and (b) now. we need to figure out how to manage those. that right? 

*i would just keep them separate*. there is some redundancy (e.g., a violation of local independence) but that is ok. so i'd process that set of 18 items as, well, 18 items!

**Comment by KingArthur0205** [comment]
@ben-domingue Thank you for clarifying. That is exactly what I meant and did in the code above. I guess we don't have to make changes then.

**Comment by ben-domingue** [comment]
@KingArthur0205 this one is a pain. i'm sorry! i think we can tidy this up further
after spending time with [this](https://dataverse.harvard.edu/file.xhtml?fileId=4824539&version=1.2) i think we just want 4 datasets here: 
1. clinic (which is clinic10ever1 + clinic10now1: the) items are kind of dependent but they are all assessing the same basic construct [overall infirmity]
2. hadsx: basic depression scale
3. limitations (facit2x+facitx): these are all basic limitation items. note that we do NOT want facit3 (if you look at those items, they ask about why you don't do things now whether you can do them)
4. crqsasx: a shortness of breath scale

again, apologies. does this make sense?

**Comment by KingArthur0205** [comment]
@ben-domingue Thank you for pointing this out as it also helps clarify my understanding. I'll make the adjustments and we can review this later. ; )

**Comment by ben-domingue** [comment]
woohoo! done.

**Comment by KingArthur0205** [comment]
Finally : )

**Comment by ben-domingue** [comment]
yeah this one was tough!
