### ISSUE TITLE
PROMIS EC Wave 1

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#546]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HYPW4B

**Comment by KingArthur0205** [comment]
Data on the site is restricted.(for my account) May need to contact owner for access.

**Comment by KingArthur0205** [comment]
They replied and asked me for details and purpose of use of data. Should we follow up with this?

**Comment by ben-domingue** [comment]
yeah forward me the email?

**Comment by KingArthur0205** [comment]
Just sent!
