### ISSUE TITLE
Inital testing of the Household Exposure to Wood Smoke (HEWS)

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#551]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/B0OGCE

(Edited by Artrur) Paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10022189/

**Comment by KingArthur0205** [comment]
This paper includes 1 dataset of responses from **12-item HEWS** on a 4-point scale sampled from 149 participants. 

The paper also includes a report of "baseline symptoms experienced was obtained, including: chest congestion, cough,
phlegm, wheeze, chest discomfort, shortness of breath, and tiredness" recorded on a 1 to 5 scale

This paper studies on pollution from wood smoke. Since items from these 2 scales are copmlementary, I have decided to merge them into 1 dataset.

**Comment by KingArthur0205** [comment]
Data:
[HEWS_Meek_2020.csv](https://github.com/user-attachments/files/17178664/HEWS_Meek_2020.csv)

Code:
```
# Paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10022189/
# Data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/B0OGCE
library(haven)
library(dplyr)
library(tidyr)

df <- read.csv("hews_data.csv")
df <- df |>
  select(id, starts_with("hews"), starts_with("t1"))
df <- pivot_longer(df, cols=-id, names_to = "item", values_to = "resp")

save(df, file="HEWS_Meek_2020.Rdata")
write.csv(df, "HEWS_Meek_2020.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
it's a 1-4 scale i think (noted above and i confirmed in the paper) but we have 0-4:
```
  0   1   2   3   4 
925 715 430 333 158 
```
the 0s could be NAs but they could also be potentially questions that got skipped? it isn't really clear but i think we need to cut those responses. thoughts @KingArthur0205

**Comment by KingArthur0205** [comment]
@ben-domingue Thanks for flagging this! The 0s had 2 different origins:
1. HEWS: You are right that this questionnarie had 1-4 scale. I will change the 0s to ```NA``` in this case. :)
2. Health Condition: The respondents also reported their health conditions(aside from the questionnaire ) to help examine if the wood smoke is affecting their health. However, the paper also suggested taht it had a 1-5 scale.

It's strange that they are having too many 0s in the dataset. I will change them to ```NA```s. :|

**Comment by ben-domingue** [comment]
@KingArthur0205 i'm also happy to reach out to the authors. if they are doing something mysterious i'd rather ask!

**Comment by KingArthur0205** [comment]
> @KingArthur0205 i'm also happy to reach out to the authors. if they are doing something mysterious i'd rather ask!

Yes, I think it would be better if we can figure out what the mysterious zeros represent.

**Comment by ben-domingue** [comment]
email sent to author, will reopen with response
