### ISSUE TITLE
Pre-job loss grief reactions and work attachment among sick-listed employees: Introduction of the imminent job loss scale

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#557]
https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/FDDFTJ

**Comment by saviranadela** [comment]
working on this

**Comment by saviranadela** [comment]
Processed data: 
[IJLS_Eersel_2024.csv](https://github.com/user-attachments/files/17125849/IJLS_Eersel_2024.csv)

Code:
```
library(dplyr)
library(tidyr)

df <- read.table("IJLS [dataset].dat", header = TRUE, sep = "\t")

col_remove <- c("Participation", "Gender", "Age", "Education", "Employment", "Ext_job", "Com_employ")
col_with_sum <- grep("Sum", names(df), value = TRUE, ignore.case = TRUE)

all_col_to_remove <- c(col_remove, col_with_sum)

df <- df[, !(names(df) %in% all_col_to_remove)]

df <- df %>%
  dplyr::rename(id = ID) %>%
  pivot_longer(cols = Lim_Phys:IJLS_9_T2,
                        names_to = "item",
                        values_to = "resp")

# Check if all rows are unique
duplicated_rows <- duplicated(df)
all_rows_unique <- !any(duplicated_rows)
all_rows_unique

write.csv(df, "IJLS_Eersel_2024.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
ok so this one is a little more complicated. two things:
1. we need to split out the items into different datasets. we have lots of scales:
```
> unique(df$item)
 [1] "Lim_Phys"      "Lim_Mental"    "Lim_Energ"     "Lim_Other"     "Work_status"  
 [6] "Finance"       "WorkCen_1"     "WorkCen_2"     "WorkCen_3R"    "UWES_1"       
[11] "UWES_2"        "UWES_3"        "commit_1"      "commit_2"      "commit_3"     
[16] "work_orient_3" "IJLS_1"        "IJLS_2"        "IJLS_3"        "IJLS_4"       
[21] "IJLS_5"        "IJLS_6"        "IJLS_7"        "IJLS_8"        "IJLS_9"       
[26] "Lot_r_1"       "Lot_r_2"       "Lot_r_3"       "Lot_r_4"       "Lot_r_5"      
[31] "Lot_r_6"       "A1"            "A2"            "A3"            "A4"           
[36] "A5"            "A6"            "A7"            "D1"            "D2"           
[41] "D3"            "D4"            "D5"            "D6"            "D7"           
[46] "ICECAP1r"      "ICECAP2r"      "ICECAP3r"      "ICECAP4r"      "ICECAP5r"     
[51] "IUS_1"         "IUS_2"         "IUS_3"         "IUS_4"         "IUS_5"        
[56] "IUS_6"         "IUS_7"         "IUS_8"         "IUS_9"         "IUS_10"       
[61] "IUS_11"        "IUS_12"        "BC_2"          "BC_7"          "BC_10"        
[66] "BC_12"         "com_1"         "com_2"         "IJLS_1_T2"     "IJLS_2_T2"    
[71] "IJLS_3_T2"     "IJLS_4_T2"     "IJLS_5_T2"     "IJLS_6_T2"     "IJLS_7_T2"    
[76] "IJLS_8_T2"     "IJLS_9_T2"    
```
looking at the [paper](https://bmcpsychology.biomedcentral.com/articles/10.1186/s40359-024-01626-8), i think we want to split out into the different scales listed in table 1:
![image](https://github.com/user-attachments/assets/e700bcd7-0ccb-427a-b565-ac2d463c3c47)

2. now the other thing is that i think they ask the IJLS questions twice (see `IJLS_1_T2` and the other `_T2` columns). i think we want to reformat those. we should have:
```
id item wave resp
1 IJLS_1 0 1
1 IJLS_1 1 0
``` 
for that scale. does that make sense? this one is a little messy so absolutely nbd that we're having to iterate a little. a great opportunity to make sure we're all on the same page!

**Comment by saviranadela** [comment]
oh this is another learning curve to me. totally make sense. thanks for making things clearer! updating this

**Comment by saviranadela** [comment]
hi @ben-domingue for the items that weren't repeated, should we put the wave to N/A or 1?

**Comment by ben-domingue** [comment]
just some of the IJLS items were repeated at one of the waves? in that case you can have something like:
```
id item wave resp
1 _1 0 1
1 _1 1 0
1 _2 0 1
1 _2 1 NA ## this row could be NA or removed
1 _3 0 1
```

**Comment by saviranadela** [comment]
Processed Data:
[IJLS_Eersel_2024_Acceptance.csv](https://github.com/user-attachments/files/17143085/IJLS_Eersel_2024_Acceptance.csv)
[IJLS_Eersel_2024_Anxiety.csv](https://github.com/user-attachments/files/17143086/IJLS_Eersel_2024_Anxiety.csv)
[IJLS_Eersel_2024_Denial.csv](https://github.com/user-attachments/files/17143087/IJLS_Eersel_2024_Denial.csv)
[IJLS_Eersel_2024_Depression.csv](https://github.com/user-attachments/files/17143088/IJLS_Eersel_2024_Depression.csv)
[IJLS_Eersel_2024_Finance.csv](https://github.com/user-attachments/files/17143089/IJLS_Eersel_2024_Finance.csv)
[IJLS_Eersel_2024_ICECAP.csv](https://github.com/user-attachments/files/17143090/IJLS_Eersel_2024_ICECAP.csv)
[IJLS_Eersel_2024_IJLSreaction.csv](https://github.com/user-attachments/files/17143091/IJLS_Eersel_2024_IJLSreaction.csv)
[IJLS_Eersel_2024_IUS.csv](https://github.com/user-attachments/files/17143092/IJLS_Eersel_2024_IUS.csv)
[IJLS_Eersel_2024_Optimism.csv](https://github.com/user-attachments/files/17143093/IJLS_Eersel_2024_Optimism.csv)

Code:
```
library(dplyr)
library(tidyr)

df <- read.table("IJLS [dataset].dat", header = TRUE, sep = "\t")

df <- df %>%
  rename(id = ID)

# --------- IJLS reactions
df_ijls <- df %>%
  select(id, contains("IJLS")) %>%
  pivot_longer(cols = IJLS_1:IJLS_9_T2,
               names_to = "item",
               values_to = "resp")
df_ijls$wave <- 0
df_ijls$wave[grepl("T2", df_ijls$item)] <- 1
df_ijls$item[grepl("T2", df_ijls$item)] <- substr(df_ijls$item[grepl("T2", df_ijls$item)], 1, 6)

df_ijls <- df_ijls %>%
  select(id, item, wave, resp)

# --------- Optimism
df_lot <- df %>%
  select(id, contains("Lot"), -matches("Sum|sum")) %>%
  pivot_longer(cols = Lot_r_1:Lot_r_6,
               names_to = "item",
               values_to = "resp")


# --------- Depression
df_d <- df %>%
  select(id, D1:D7) %>%
  pivot_longer(cols = D1:D7,
               names_to = "item",
               values_to = "resp")

# --------- Anxiety
df_a <- df %>%
  select(id, A1:A7) %>%
  pivot_longer(cols = A1:A7,
               names_to = "item",
               values_to = "resp")

# --------- Denial
df_bc <- df %>%
  select(id, BC_2, BC_7) %>%
  pivot_longer(c(BC_2,BC_7),
               names_to = "item",
               values_to = "resp")

# --------- Intolerance of uncertainty
df_ius <- df %>%
  select(id, contains("IUS")) %>%
  pivot_longer(cols = IUS_1:IUS_12,
               names_to = "item",
               values_to = "resp")

# --------- Quality of life
df_icecap <- df %>%
  select(id, contains("ICECAP"), -matches("Sum|sum")) %>%
  pivot_longer(cols = ICECAP1r:ICECAP5r,
               names_to = "item",
               values_to = "resp")

# --------- Acceptance
df_ac <- df %>%
  select(id, BC_10, BC_12) %>%
  pivot_longer(c(BC_10,BC_12),
               names_to = "item",
               values_to = "resp")

# --------- Finance 
df_fin <- df %>%
  select(id, Finance) %>%
  pivot_longer(Finance,
               names_to = "item",
               values_to = "resp")

write.csv(df_ijls, "IJLS_Eersel_2024_IJLSreaction.csv", row.names=FALSE)
write.csv(df_lot, "IJLS_Eersel_2024_Optimism.csv", row.names=FALSE)
write.csv(df_d, "IJLS_Eersel_2024_Depression.csv", row.names=FALSE)
write.csv(df_a, "IJLS_Eersel_2024_Anxiety.csv", row.names=FALSE)
write.csv(df_bc, "IJLS_Eersel_2024_Denial.csv", row.names=FALSE)
write.csv(df_ius, "IJLS_Eersel_2024_IUS.csv", row.names=FALSE)
write.csv(df_icecap, "IJLS_Eersel_2024_ICECAP.csv", row.names=FALSE)
write.csv(df_ac, "IJLS_Eersel_2024_Acceptance.csv", row.names=FALSE)
write.csv(df_fin, "IJLS_Eersel_2024_Finance.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
@ben-domingue the above work may not be final. I have questions in the middle of the work:

1. Based on Table 1 on the paper, we should have item "Perceived health (EQ-5D-NL)" 
 _Participants were asked to rate their perceived health over the last three months on a scale from 0 (worst possible health they can image) to 100 (best possible health they can image)_
However, I couldn't find this kind of scale in their raw data.

2. I had doubts and spent a while considering if one is an item. For example, do "perceived limitations" qualify as an item? 

Hope this will build my sense even better moving forward!

**Comment by ben-domingue** [comment]
1. that's no problem. if you can't find it, that's ok. it's also perhaps a one-item scale which isn't what we want anyways.
2. can you say more? i might need an example to know what to do with that one. 

also, one thing that is useful: when there are this many CSV files, it's perhaps easier for everyone if you want to just upload a zip file with all of them

**Comment by saviranadela** [comment]
@ben-domingue 
2. sorry of the lack of clarity! perceived limitations are limitations that the participants experienced due to health issues. items and scale:
<img width="615" alt="image" src="https://github.com/user-attachments/assets/d7a2d5be-d765-4a36-a6e9-8e8ac9d2dd98">

**Comment by ben-domingue** [comment]
i think having responses to these 4 questions as 4 items is totally fine

**Comment by saviranadela** [comment]
That's where I had some doubts. I was thinking this variable is similar to age, education, or gender, rather than being something measured as an 'item.' Does that make sense?

Codebook:
https://dataverse.nl/file.xhtml?fileId=378452&version=1.0

**Comment by ben-domingue** [comment]
Great observation. I think you're right, you can include those as 'demographic' covariates but they aren't items. 
now that i'm looking at the codebook, what i would propose is grouping:
1. workcen, UWES, Commit
2. IJLS
3. optimism
4. anxiety
5. depression
6. quality of life
7. intolerance of uncertainty
8. denial, acceptance

that seem right? so we'd have 8 files in total for this study under my suggestion

**Comment by saviranadela** [comment]
nice, thanks Ben! file and code updated!
PR: https://github.com/ben-domingue/irw/pull/579 :)

**Comment by ben-domingue** [comment]
one question; what are icecap and IUS? @saviranadela

**Comment by saviranadela** [comment]
ICECAP-A stands for Investigating Choice Experiments Capability – Adult, it was used to measure quality of life.

```
Item #1 ICECAP1r - Feeling comfortable and safe
Resp - 4. I feel secure and at ease in all areas of my life; 3 = I feel secure and at ease in many areas of my life; 2 = In some areas of my life, I am able to feel secure and at ease; 1 = On no area of my life, I am able to feel secure and at ease

Item #2 ICECAP2r - Love, friendship, and support
Resp - 4 = I am able to have a lot of love, friendship, and support; 3 = I am capable of having quite a lot of love, friendship, and support; 2 = I am capable of having a little love, friendship, and support; 1 = I am not capable of having love, friendship, and support

Item #3 ICECAP3r - Being independent
Resp - 4 = I am able to be completely independent; 3 = I am able to be independent in many things; 2 = I am able to be independent in some things; 1 = I am not able to be independent at all

Item #4 ICECAP4r - Achievements and progress
Resp - 4 = I am able to perform and make progress in all aspects of my life; 3 = I am able to perform and make progress in many aspects of my life; 2 = I am able to perform and make progress in some aspects of my life; 1 = I am unable to perform and make progress in any aspect of my life

Item #5 ICECAP5r - Having fun and enjoying life	
Resp - 4 = I am capable of having a lot of fun and enjoying myself; 3 = I am capable of having quite a bit of fun and enjoying myself; 2 = I am capable of having some fun and enjoying myself; 1 = I am not capable of having fun and enjoying myself.
```

While IUS stands for Intolerance of Uncertainty Scale (scale 1-5, with 1 as strongly disagree and 5 as strongly agree), basically how participants would feel/react when facing uncertainties. 
<img width="721" alt="image" src="https://github.com/user-attachments/assets/8efca634-8c3f-4860-9aaf-fcfb320accbf">

hope this answers! @ben-domingue
