### ISSUE TITLE
Achieving mental wellness in school-aged children: Validating a questionnaire to measure developmental task completion (QADT)

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#576]
https://osf.io/6vqp3/

**Comment by ben-domingue** [comment]
email permission 10-4-2024

**Comment by saviranadela** [comment]
A total of 453 children participated, including 207 boys and 246 girls. The QADT, Brief Multidimensional Students' Life Satisfaction Scale (BMSLSS) and Center for Epidemiological Studies Depression Scale for Children - (CES-DC) were used to measure variables.

[QADT_anon.pdf](https://github.com/user-attachments/files/17338991/QADT_anon.pdf)

**Comment by saviranadela** [comment]
Processed data: 
[QADT_Kleka_2023.csv](https://github.com/user-attachments/files/17338996/QADT_Kleka_2023.csv)

Code:
```
library(tidyverse)

load('zr_cleaned.rda')

df <- zr |>
  select(OSOBA, fala, ZR_1:ZR_12) |>
  pivot_longer(c(ZR_1:ZR_12),
               names_to = "item",
               values_to = "resp") |>
  filter(!is.na(resp))  |>
  rename(id = OSOBA, wave = fala)

write.csv(df, "QADT_Kleka_2023.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
PR: https://github.com/ben-domingue/irw/pull/612

**Comment by KingArthur0205** [comment]
Hii Savira! I think this one looks great! I'm not sure what "klasa" is tho but I guess that is ok.

Some translations for column names in case we want to further review later:
fala: wave
plec: gender
ZR_SUMA: sum score
OSOBA: person = id

**Comment by ben-domingue** [comment]
tagging @saviranadela about the above

**Comment by ben-domingue** [comment]
actually @saviranadela ignore. i think we are all good. i am closing this one. well done team!!!
