### ISSUE TITLE
gilbert data

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#581]
i’ve also added TOT variables for 7 studies where that was possible. so you can update 41, 4, 7, 8, 44, 56, 60, 61. csvs are in dropbox as before.

@ben-domingue

**Comment by joshgilbert1994** [comment]
also FYI I had all the treatment variables as "treat" but I think elsewhere you have it as "treatment" so you might want to double check this

**Comment by ben-domingue** [comment]
@joshgilbert1994 added this to my todo list #583
