### ISSUE TITLE
Do data from mechanical Turk subjects replicate accuracy, response time, and diffusion modeling results?

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#60]
https://osf.io/za9y8/
paper. https://link.springer.com/article/10.3758/s13428-021-01573-x#additional-information

**Comment by KingArthur0205** [comment]
Working on this

**Comment by KingArthur0205** [comment]
Paper contains 2 datasets of participants involved in lexical decision/recognition tasks. I have put down some simple documentations for ease of review:

1. ```block_number```: The experiment is split into multiple blocks. This column is removed as the same meausres are carried out in every block.
2. ```stimulus_number```: This is the order in which words are presented. Deleted.
3. ```response_key_id```: The key pressed(response). Renamed to ```resp```
4. ```task_number```: 1 for lexical and 2 for recognition. Re-coded to "lexical" and "recognition" for better understanding.
5. ```column_7_value``` and ```column_8_value```: Descriptive info for the items.(frequency, word/no word, studied/no studied). Deleted

Some minor columns(```word_length```, ```test_word_string```) are removed.

**Comment by KingArthur0205** [comment]
The paper also includes an additional dataset, but I am encountering some difficulty processing it. 
Link to description of the test: https://link.springer.com/article/10.3758/s13428-021-01573-x#Sec12

In this dataset, participants responded to images of varying sizes, each containing a different sets of dots. Unfortunately, the item column cannot be directly extracted from the data.

Would it be appropriate to encode item values to reflect the number of dots and the area of the pattern, using a format like d30_s50 (where d30 represents 30 dots and s50 represents size 50)?

**Comment by ben-domingue** [comment]
Let's discuss the two datasets separately:

- Numerosity: "In this dataset, participants responded to images of varying sizes, each containing a different sets of dots. Unfortunately, the item column cannot be directly extracted from the data." Let's leave this data to the side. I think what you want to do is reasonable, but let's backburner it. It is related to the trials issue discussed here (https://groups.google.com/g/irwdata/c/b3z5Mzxv_i8). I want to create a standard and then will have a variety of data to deposit based on the 'trials' standard. Once we've finished the other dataset, I'll change the label on this to the newly created 'trials' label.

- Lexical decision task: I have several questions:
a. We should cut *practice_word*
b. We have ~4696 items. This seems about right (800+800+741 words, one paired pseudoword, in combination this puts us at 4682 which i'm mostly comfortable with). Do you agree with my logic? Might help to read first paragraph of 'the task' here (https://en.wikipedia.org/wiki/Lexical_decision_task). 
c. I don't understand the coding of 'resp'. We have 0/1/2 values but they should probably be only two categories: (correct=a respondent appropriately recognizes a real word as real or a pseudoword as fake versus the alternative). Can you say how we got 3 categories here?

**Comment by KingArthur0205** [comment]
Lexical decision task:
a. I have made the corrections. I now realize that practice trials should not be included—my apologies for the oversight.

b. I think we are having more than 4682 because **some words are paired with more than one pseudoword**.  For example, "crib" is paired with both "creb" and "crob."

c. We have three values here because "0" indicates when the respondent presses an invalid key other than the two specified keys (```z``` and ```/```). I created a new version where these "0" responses are treated as false. However, I’m unsure if this is the appropriate approach, as **pressing the wrong key may be different** from making an incorrect judgment. Could you provide guidance on this?

For task 1 lexical decision, resp==1 if ```response_key_id==column_7_value```. 
For task 2 memorization, resp==1 if ```(response_key_id==1 & column_8_value==1 or 2) | (response_key_id==0 & column_8_value==3)```

**Comment by ben-domingue** [comment]
Man you are *so* thorough. I love it. Let's just call the 'incorrect' keys NA values. I don't think we can really make a meaningful inference with them so let's just exclude them.

**Comment by KingArthur0205** [comment]
Thank you so much for your kind words! ：）））））））I’m really glad you found the approach thorough. 

I've changed the invalid key presses to NA.(changes made in the previous comments) One other small point I think I didn't make clear is that I have left a column called "subtest" to indicate if the participants was in "lexical" or "recognition" task.

If you think this is good, I will make a PR about this :)

**Comment by KingArthur0205** [comment]
Sure, task completed :)

**Comment by ben-domingue** [comment]
README change: excellent
