### ISSUE TITLE
Academic Motivation Scale: Validity in Portuguese Public Higher Education

### ISSUE THREAD

**Issue by joshgilbert1994** [ben-domingue/irw#626]
public domain: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/KWTMWT

**Comment by saviranadela** [comment]
done this before here: https://github.com/ben-domingue/irw/issues/535

shall i close? @ben-domingue :)

**Comment by ben-domingue** [comment]
great catch @saviranadela
