### ISSUE TITLE
Adaptation and validation of simple tools to screen and monitor for oral PrEP adherence

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#628]
Data Availability: The data can be found on the Harvard Dataverse Repository at https://doi.org/10.7910/DVN/NI4ZQA.

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0251823

**Comment by saviranadela** [comment]
processed data: 
[PrEPAdherence_Zissette_2021.zip](https://github.com/user-attachments/files/17675064/PrEPAdherence_Zissette_2021.zip)

code:
```
library(tidyr)
library(dplyr)

df <- read.table("Screening and adherence monitoring for oral PrEP.tab", header=TRUE, sep="\t")

df$id <- seq(1, nrow(df))

df_s <- df %>%
  select(id, starts_with("q_s_")) %>%
  pivot_longer(-id,
               names_to = 'item',
               values_to = 'resp') %>%
  filter(!is.na(resp))


df_m_all <- df %>%
  select(id, matches("^q_m_.*all")) %>%
  pivot_longer(-id,
               names_to = 'item',
               values_to = 'resp') %>%
  filter(!is.na(resp))


df_m_ntp <- df %>%
  select(id, matches("^q_m_.*ntp")) %>%
  pivot_longer(-id,
               names_to = 'item',
               values_to = 'resp') %>%
  filter(!is.na(resp))


df_m_ftp <- df %>%
  select(id, matches("^q_m_.*ftp")) %>%
  pivot_longer(-id,
               names_to = 'item',
               values_to = 'resp') %>%
  filter(!is.na(resp))


write.csv(df_s, "PrEPAdherence_Zissette_2021_Screening.csv", row.names=FALSE)
write.csv(df_m_all, "PrEPAdherence_Zissette_2021_Monitoring_all.csv", row.names=FALSE)
write.csv(df_m_ntp, "PrEPAdherence_Zissette_2021_Monitoring_ntp.csv", row.names=FALSE)
write.csv(df_m_ftp, "PrEPAdherence_Zissette_2021_Monitoring_ftp.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
_the first section included 54 items in random order making up the six subscales of the screening tool. The same items were administered uniformly to all women. The second section comprised of 45 monitoring items in random order adapted for oral PrEP. There were two versions of this section; one focused on oral PrEP and administered only to women who had or were participating in oral PrEP trials, the other version adapted oral PrEP-specific items to other types of oral pill use to better fit the experiences of trial-naïve women._

based on that, I split them this way:
a. items from screening tool
b. items from monitoring tool with all participants combined
c. items from monitoring tool with former trial participants (FTP) only --> subset of b
d. items from monitoring tool with trial-naïve participants (TNP) only --> subset of b

@KingArthur0205 @ben-domingue please let me know if you guys have any input on the splitting! :)

**Comment by ben-domingue** [comment]
wait i don't think we need to split here. we could maybe have a column that captures this set of distinctions but if the items are the same across a-d no need to split i don't think

**Comment by saviranadela** [comment]
i am thinking to distinguish them in the item name instead of making a new column, since this distinction applies to monitoring items only. feel free if you have further input! :)

file: 
[PrEPAdherence_Zissette_2021.csv](https://github.com/user-attachments/files/17683437/PrEPAdherence_Zissette_2021.csv)

code:
```
library(tidyr)
library(dplyr)

df <- read.table("Screening and adherence monitoring for oral PrEP.tab", header=TRUE, sep="\t")

df$id <- seq(1, nrow(df))

df_final <- df %>%
  select(id, starts_with("q_s_"), matches("^q_m_.*ftp"), matches("^q_m_.*ntp")) %>%
  pivot_longer(-id,
               names_to = 'item',
               values_to = 'resp') %>%
  filter(!is.na(resp))


write.csv(df_final, "PrEPAdherence_Zissette_2021.csv", row.names=FALSE)
```

**Comment by saviranadela** [comment]
PR: https://github.com/ben-domingue/irw/pull/688

**Comment by saviranadela** [comment]
or actually I can also compile it like

id, item, resp, former_participant (N/A for screening items, 0 for no in monitoring items, 1 for yes in monitoring items)

**Comment by ben-domingue** [comment]
hm. i'm inclined at this point to simplify this data and maybe just take a single set of responses for each person? seems like kind of a mess otherwise? @saviranadela what do you think would be the right way of going if our goal is to get something a little simpler?

**Comment by ben-domingue** [comment]
@saviranadela yes let's keep it simple :)

**Comment by saviranadela** [comment]
thanks for the input! i have updated the file, code, and PR :)

**Comment by ben-domingue** [comment]
one comment: should one of these be dropped: q_s_048_original  q_s_048_reverse

**Comment by saviranadela** [comment]
oh yeah right. updated!

**Comment by ben-domingue** [comment]
added, thanks @saviranadela
