### ISSUE TITLE
Dataset of the initial validation of Questionnaire for the Self-assessment of University Service-learning Experiences (QaSLu)

### ISSUE THREAD

**Issue by joshgilbert1994** [ben-domingue/irw#632]
Public domain

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LUUDQC

**Comment by KingArthur0205** [comment]
**Questionnaire for the Self-assessment of University Service-learning Experiences（QaSLU)**
45 items with 118 participants(align with description). The items were on a 0-starting 5-point Likert scale.(0-4)

**Comment by KingArthur0205** [comment]
Data:
[QaSLU_Prado_2024.csv](https://github.com/user-attachments/files/17535705/QaSLU_Prado_2024.csv)

Code:
```
# Paper:
# Data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LUUDQC
library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)

df <- read.xlsx("Qaslu.xlsx")
df <- df |>
  mutate(id=row_number()) |>
  select(starts_with("Item"), id)
df <- pivot_longer(df, cols=-id, names_to="item", values_to="resp")

save(df, file="QaSLU_Prado_2024.Rdata")
write.csv(df, "QaSLU_Prado_2024.csv", row.names=FALSE)
````

**Comment by KingArthur0205** [comment]
Data dictionary entry added at row 605.
PR for this issue: https://github.com/ben-domingue/irw/pull/648
