### ISSUE TITLE
Reliability and Validity of the Korean version of the Pornography Craving Questionnaire (K-PCQ) Based on the Classical Test Theory and Item Response Theory

### ISSUE THREAD

**Issue by joshgilbert1994** [ben-domingue/irw#633]
Public domain

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SHCUI4

**Comment by saviranadela** [comment]
@ben-domingue @KingArthur0205 

processed data: 
[K-PCQ_Huh_2022.csv](https://github.com/user-attachments/files/17471452/K-PCQ_Huh_2022.csv)

code:
```
library(tidyr)
library(dplyr)

df <- read.table("Suppl_2_response_data_358.tab", header=TRUE, sep="\t")

df <- df %>% select(Crav1:Crav12)

df$id <- seq(1, nrow(df))

df <- df %>%
  pivot_longer(c(Crav1:Crav12),
               names_to = "item",
               values_to = "resp") %>%
  filter(!is.na(resp))

write.csv(df, "K-PCQ_Huh_2022.csv", row.names=FALSE)
```

**Comment by ben-domingue** [comment]
@saviranadela 
looking at table 1, i think we need to cut the `resp=0` options? 
https://pmc.ncbi.nlm.nih.gov/articles/PMC8256136/

**Comment by saviranadela** [comment]
oh thanks for catching that @ben-domingue totally right! I assumed 0 means unanswered, but we can take that out.

updated in the comment above

**Comment by ben-domingue** [comment]
so easy! thanks @saviranadela
