### ISSUE TITLE
Item development process and analysis of 50 case-based items for implementation on the Korean Nursing Licensing Examination

### ISSUE THREAD

**Issue by joshgilbert1994** [ben-domingue/irw#634]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ECDLXG

public domain

**Comment by saviranadela** [comment]
@ben-domingue @KingArthur0205 

processed data: 
[KoreanNursing_Park_2017.csv](https://github.com/user-attachments/files/17471308/KoreanNursing_Park_2017.csv)

code:
```
library(tidyr)
library(dplyr)

df <- read.table("Jeehp-14-20_raw data.tab", header=TRUE)

df$id <- seq(1, nrow(df))

df <- df %>%
  pivot_longer(c(-id),
               names_to = "item",
               values_to = "resp") %>%
  filter(!is.na(resp))

write.csv(df, "KoreanNursing_Park_2017.csv", row.names=FALSE)
```

**Comment by KingArthur0205** [comment]
740 student particiants with 50 items on a 0/1 scale. All match with the paper.

I think this is good to be uploaded:). @ben-domingue  Adding it to the data dictionary.

**Comment by saviranadela** [comment]
PR: https://github.com/ben-domingue/irw/pull/638

**Comment by ben-domingue** [comment]
data on redivis. closing issue
