### ISSUE TITLE
RealPic: Picture norms of real-world common items

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#66]
https://osf.io/qn35s/?view_only=9c209e9236b94b2cb74f77f47e7ff390
paper. https://link.springer.com/article/10.3758/s13428-020-01523-z

picture might be the id. debrief with ben on this one.

**Comment by ben-domingue** [comment]
i think that might work. i would do something like:
```
id,item,resp
<picture number>,<dimension name>, <resp>

```
where the second row is meant to describe the info in each column. would that work?

**Comment by anniehang** [comment]
ok, get it. then i can process this one

**Comment by anniehang** [comment]
[RealPic.csv](https://github.com/user-attachments/files/15974780/RealPic.csv)
