### ISSUE TITLE
Face identification proficiency test designed using item response theory

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#76]
data. Face identification proficiency test designed using item response theory
paper. https://link.springer.com/article/10.3758/s13428-023-02092-7

**Comment by rn2407stanford** [comment]
Data here: 
[responses.csv](https://github.com/ben-domingue/irw/files/15286403/responses.csv)

**Comment by ben-domingue** [comment]
@rn2407stanford just confirming that we still need to process this data, correct?

**Comment by rn2407stanford** [comment]
Oh, no. For this one I sent a pull request. https://github.com/ben-domingue/irw/pull/95

**Comment by ben-domingue** [comment]
ah, cool! so i would just need to run this data through the code?

**Comment by rn2407stanford** [comment]
yes. Isn't it how I am supposed to do the pull request? Is there something else I should do?

**Comment by ben-domingue** [comment]
this was great! i just added the data and emailed the authors :)
the pull was perfect. next time if you didn't mind running the code on the original data and just attaching the output here that'd be great. but this worked fine too so no worries. thanks *so much* roza!!! :1st_place_medal:
