### ISSUE TITLE
An item response theory approach to the measurement of working memory capacity

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#77]
paper. https://link.springer.com/article/10.3758/s13428-023-02115-3
data. https://osf.io/bhw87/

**Comment by rn2407stanford** [comment]
[WMI_Rot_Han_Wide.csv](https://github.com/ben-domingue/irw/files/15284970/WMI_Rot_Han_Wide.csv)
[WMI_Read_Han_Wide.csv](https://github.com/ben-domingue/irw/files/15284971/WMI_Read_Han_Wide.csv)



```{r}
read=read.csv("WMI_Read_Han_Wide.csv")[,-1]
x<-read
id<-1:nrow(x)
L<-list()
for (i in 2:ncol(x)) L[[i]]<-data.frame(id=x[,1],item=colnames(x)[i],resp=x[,i])
df<-data.frame(do.call("rbind",L)); df; x
save(df,file='WMI_Read_Han.Rdata')
```

```{r}
rot=read.csv("WMI_Rot_Han_Wide.csv")[,-1]
x<-rot
id<-1:nrow(x)
L<-list()
for (i in 2:ncol(x)) L[[i]]<-data.frame(id=x[,1],item=colnames(x)[i],resp=x[,i])
df<-data.frame(do.call("rbind",L)); df; x
save(df,file='WMI_Rot_Han.Rdata')
```

**Comment by rn2407stanford** [comment]
So, for the  WMI_Rot_Han_Wide.csv Some of the items have non-interger values, such as 0.3333, 0.6667 etc. What should I do?
( instead of 0, 1, 2)... Should I delete those items or just leave as it is?

**Comment by ben-domingue** [comment]
all values are 0,1/3,2/3,and 1?

**Comment by rn2407stanford** [comment]
Just sent the request and this is the output.
[WMI_Read_Han.xlsx](https://github.com/ben-domingue/irw/files/15301019/WMI_Read_Han.xlsx)
[WMI_Rot_Han.xlsx](https://github.com/ben-domingue/irw/files/15301020/WMI_Rot_Han.xlsx)

**Comment by ben-domingue** [comment]
i think that maybe one of the files got doubled? in particular, i think the ROT file may not be right (seems a duplicate of the READ file?).

**Comment by rn2407stanford** [comment]
Hi Professor, I think the pull request codes are correct. And yes, it seem I exported the same file into excel. But just updated above. Thanks for noticing it.
