### ISSUE TITLE
Online assessment of musical ability in 10 minutes: Development and validation of the Micro-PROMS

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#79]
paper. https://link.springer.com/article/10.3758/s13428-023-02130-4
data. https://osf.io/au6m5/

**Comment by anniehang** [comment]
[MicroPROMS_data_S1.csv](https://github.com/ben-domingue/irw/files/14932422/MicroPROMS_data_S1.csv)
[MicroPROMS_data_S2.csv](https://github.com/ben-domingue/irw/files/14932425/MicroPROMS_data_S2.csv)
[MicroPROMS_data_S3.csv](https://github.com/ben-domingue/irw/files/14932427/MicroPROMS_data_S3.csv)

**Comment by ben-domingue** [comment]
OK this is great. I have two questions. 
1. I am looking at S3 and there are 3 items missing from the microproms:
 [1] "TB14_cod" "TB16_cod" "A3_cod"   "A5_cod"   "A12_cod" 
Do you have any insight into those? 
2. What are the resp=.5 values?

**Comment by anniehang** [comment]
The paper says:“To improve the psychometric efficiency of the instrument, we removed three trials that had not added to reliability or validity.”, and I think this is the reason

**Comment by anniehang** [comment]
For each correct answer, participants received 1 point for high confidence ratings (i.e., “Definitely same/different”) and 0.5 points for lower confidence ratings (i.e., “Probably same/ different”). Wrong answers and “I don’t know” answers were scored with 0 points.
