### ISSUE TITLE
DEMOS_data

### ISSUE THREAD

**Issue by anniehang** [ben-domingue/irw#8]
[DEMOS.csv](https://github.com/ben-domingue/irw/files/14473520/DEMOS.csv)
This is the source of the data: https://link.springer.com/article/10.3758/s13428-022-01887-4

**Comment by ben-domingue** [comment]
@ben-domingue todo

**Comment by ben-domingue** [comment]
@anniehang hi i wanted to ask a question. so each video has responses to these items:
`accuracy_mean intensity_mean obj_move_mean subj_move_mean`
i'm struggling to undersatnd what the 'resp' variable actually means here. let's look at one example:

`                id           item   resp
3637 F01A0V2_0.mp4  accuracy_mean   0.69
3638 F01A0V2_0.mp4 intensity_mean   7.17
3639 F01A0V2_0.mp4 subj_move_mean   7.10
3640 F01A0V2_0.mp4  obj_move_mean 941.46
`
did you have a sense for what those 4 numbers are?

**Comment by anniehang** [comment]
let me explain these variables
accuracy_mean: This represents the average accuracy with which participants in the study were able to recognize the intended emotions from the movement videos.
intensity_mean: This refers to the mean emotional intensity as rated by participants, indicating how strongly they perceived the emotion expressed in each video.
obj_move_mean (objective movement mean): This quantifies the average amount of movement detected in the videos, calculated using a mathematical model that assesses changes in pixel luminance between frames to represent motion.
subj_move_mean (subjective movement mean): This is the average rating given by participants on the perceived amount of movement in the videos, reflecting their personal assessment of how much motion they think each video contains.

**Comment by anniehang** [comment]
[DEMOS.csv](https://github.com/ben-domingue/irw/files/14488235/DEMOS.csv)
this is the output

**Comment by ben-domingue** [comment]
morning! i am trying to decide whether i think this data fits what i have in mind as the IRW inclusion criteria. it is kind of an interesting edge case. i'm stuck teaching and in meetings today but i am thinking about this!
