### ISSUE TITLE
PREVIC: An adaptive parent report measure of expressive vocabulary in children between 3 and 8 years of age

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#82]
https://osf.io/preprints/psyarxiv/hvncp

**Comment by sophchun** [comment]
working on this one!

**Comment by sophchun** [comment]
`# -*- coding: utf-8 -*-
"""Previc_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rHGarjcHtyAYP12F9XHfmlL2kcVrKzoV
"""

import pandas as pd

url = 'https://raw.githubusercontent.com/manuelbohn/previc/main/data/previc_data.csv'

df = pd.read_csv(url)

df = df.rename(columns={
    'subjID': 'id',  # Person ID
    'trial': 'item',  # Item ID
    'score': 'resp'  # Coded response
})

output_path = 'previc_data_processed.csv'

df.to_csv(output_path, index=False)

pd.read_csv('previc_data_processed.csv')`

**Comment by ben-domingue** [comment]
@sophchun can you upload the output data here as a CSV file?

**Comment by sophchun** [comment]
[previc_data_processed.csv.zip](https://github.com/user-attachments/files/16062037/previc_data_processed.csv.zip)

**Comment by sophchun** [comment]
Just uploaded it as a compressed zip file because it was a bit too large!
________________________________

**Comment by ben-domingue** [comment]
closed. i have emailed authors about copyright.
